// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: beehive-m-friend.proto

package server

import (
	"context"

	"github.com/HappyLadySauce/Beehive-M/services/friend/internal/logic/friendservice"
	"github.com/HappyLadySauce/Beehive-M/services/friend/internal/svc"
	"github.com/HappyLadySauce/Beehive-M/services/friend/pb"
)

type FriendServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedFriendServiceServer
}

func NewFriendServiceServer(svcCtx *svc.ServiceContext) *FriendServiceServer {
	return &FriendServiceServer{
		svcCtx: svcCtx,
	}
}

// 好友
func (s *FriendServiceServer) ListFriends(ctx context.Context, in *pb.ListFriendsRequest) (*pb.ListFriendsResponse, error) {
	l := friendservicelogic.NewListFriendsLogic(ctx, s.svcCtx)
	return l.ListFriends(in)
}

func (s *FriendServiceServer) DeleteFriend(ctx context.Context, in *pb.DeleteFriendRequest) (*pb.DeleteFriendResponse, error) {
	l := friendservicelogic.NewDeleteFriendLogic(ctx, s.svcCtx)
	return l.DeleteFriend(in)
}

func (s *FriendServiceServer) UpdateRemark(ctx context.Context, in *pb.UpdateRemarkRequest) (*pb.UpdateRemarkResponse, error) {
	l := friendservicelogic.NewUpdateRemarkLogic(ctx, s.svcCtx)
	return l.UpdateRemark(in)
}

func (s *FriendServiceServer) SetFriendMuted(ctx context.Context, in *pb.SetFriendMutedRequest) (*pb.SetFriendMutedResponse, error) {
	l := friendservicelogic.NewSetFriendMutedLogic(ctx, s.svcCtx)
	return l.SetFriendMuted(in)
}

func (s *FriendServiceServer) SetFriendSpecial(ctx context.Context, in *pb.SetFriendSpecialRequest) (*pb.SetFriendSpecialResponse, error) {
	l := friendservicelogic.NewSetFriendSpecialLogic(ctx, s.svcCtx)
	return l.SetFriendSpecial(in)
}

// 申请
func (s *FriendServiceServer) SendFriendRequest(ctx context.Context, in *pb.SendFriendRequestRequest) (*pb.SendFriendRequestResponse, error) {
	l := friendservicelogic.NewSendFriendRequestLogic(ctx, s.svcCtx)
	return l.SendFriendRequest(in)
}

func (s *FriendServiceServer) ListReceivedRequests(ctx context.Context, in *pb.ListReceivedRequestsRequest) (*pb.ListReceivedRequestsResponse, error) {
	l := friendservicelogic.NewListReceivedRequestsLogic(ctx, s.svcCtx)
	return l.ListReceivedRequests(in)
}

func (s *FriendServiceServer) ListSentRequests(ctx context.Context, in *pb.ListSentRequestsRequest) (*pb.ListSentRequestsResponse, error) {
	l := friendservicelogic.NewListSentRequestsLogic(ctx, s.svcCtx)
	return l.ListSentRequests(in)
}

func (s *FriendServiceServer) HandleFriendRequest(ctx context.Context, in *pb.HandleFriendRequestRequest) (*pb.HandleFriendRequestResponse, error) {
	l := friendservicelogic.NewHandleFriendRequestLogic(ctx, s.svcCtx)
	return l.HandleFriendRequest(in)
}

// 黑名单
func (s *FriendServiceServer) AddBlacklist(ctx context.Context, in *pb.AddBlacklistRequest) (*pb.AddBlacklistResponse, error) {
	l := friendservicelogic.NewAddBlacklistLogic(ctx, s.svcCtx)
	return l.AddBlacklist(in)
}

func (s *FriendServiceServer) RemoveBlacklist(ctx context.Context, in *pb.RemoveBlacklistRequest) (*pb.RemoveBlacklistResponse, error) {
	l := friendservicelogic.NewRemoveBlacklistLogic(ctx, s.svcCtx)
	return l.RemoveBlacklist(in)
}

func (s *FriendServiceServer) ListBlacklist(ctx context.Context, in *pb.ListBlacklistRequest) (*pb.ListBlacklistResponse, error) {
	l := friendservicelogic.NewListBlacklistLogic(ctx, s.svcCtx)
	return l.ListBlacklist(in)
}

func (s *FriendServiceServer) CheckBlacklist(ctx context.Context, in *pb.CheckBlacklistRequest) (*pb.CheckBlacklistResponse, error) {
	l := friendservicelogic.NewCheckBlacklistLogic(ctx, s.svcCtx)
	return l.CheckBlacklist(in)
}

// 推荐
func (s *FriendServiceServer) ListRecommendations(ctx context.Context, in *pb.ListRecommendationsRequest) (*pb.ListRecommendationsResponse, error) {
	l := friendservicelogic.NewListRecommendationsLogic(ctx, s.svcCtx)
	return l.ListRecommendations(in)
}

func (s *FriendServiceServer) IgnoreRecommendation(ctx context.Context, in *pb.IgnoreRecommendationRequest) (*pb.IgnoreRecommendationResponse, error) {
	l := friendservicelogic.NewIgnoreRecommendationLogic(ctx, s.svcCtx)
	return l.IgnoreRecommendation(in)
}
