// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: beehive-m-message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         int64                  `protobuf:"varint,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	SceneType     int32                  `protobuf:"varint,2,opt,name=scene_type,json=sceneType,proto3" json:"scene_type,omitempty"` // 1私聊 2群聊
	SenderId      int64                  `protobuf:"varint,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	FileUrl       string                 `protobuf:"bytes,5,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`
	FileName      string                 `protobuf:"bytes,6,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileSize      int64                  `protobuf:"varint,7,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	SendTime      int64                  `protobuf:"varint,8,opt,name=send_time,json=sendTime,proto3" json:"send_time,omitempty"`
	IsRecalled    int32                  `protobuf:"varint,9,opt,name=is_recalled,json=isRecalled,proto3" json:"is_recalled,omitempty"`          // 0否 1是
	ReceiverId    int64                  `protobuf:"varint,10,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`         // 私聊时使用
	GroupId       int64                  `protobuf:"varint,11,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`                  // 群聊时使用
	AtUserIds     string                 `protobuf:"bytes,12,opt,name=at_user_ids,json=atUserIds,proto3" json:"at_user_ids,omitempty"`           // JSON 数组，@ 的用户 ID 列表
	ContentType   int32                  `protobuf:"varint,13,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`      // 1文本 2图片 3文件 4表情
	RefMsgId      int64                  `protobuf:"varint,14,opt,name=ref_msg_id,json=refMsgId,proto3" json:"ref_msg_id,omitempty"`             // 引用消息ID，可选
	RefSceneType  int32                  `protobuf:"varint,15,opt,name=ref_scene_type,json=refSceneType,proto3" json:"ref_scene_type,omitempty"` // 引用消息场景，可选：1私聊 2群聊
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_beehive_m_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_beehive_m_message_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetMsgId() int64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *Message) GetSceneType() int32 {
	if x != nil {
		return x.SceneType
	}
	return 0
}

func (x *Message) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

func (x *Message) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *Message) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *Message) GetSendTime() int64 {
	if x != nil {
		return x.SendTime
	}
	return 0
}

func (x *Message) GetIsRecalled() int32 {
	if x != nil {
		return x.IsRecalled
	}
	return 0
}

func (x *Message) GetReceiverId() int64 {
	if x != nil {
		return x.ReceiverId
	}
	return 0
}

func (x *Message) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *Message) GetAtUserIds() string {
	if x != nil {
		return x.AtUserIds
	}
	return ""
}

func (x *Message) GetContentType() int32 {
	if x != nil {
		return x.ContentType
	}
	return 0
}

func (x *Message) GetRefMsgId() int64 {
	if x != nil {
		return x.RefMsgId
	}
	return 0
}

func (x *Message) GetRefSceneType() int32 {
	if x != nil {
		return x.RefSceneType
	}
	return 0
}

// 会话（与 conversations 表对齐）
type Conversation struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ConversationId   int64                  `protobuf:"varint,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	UserId           int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TargetType       int32                  `protobuf:"varint,3,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"` // 1用户 2群组
	TargetId         int64                  `protobuf:"varint,4,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	LastMsgId        int64                  `protobuf:"varint,5,opt,name=last_msg_id,json=lastMsgId,proto3" json:"last_msg_id,omitempty"`
	LastMsgPreview   string                 `protobuf:"bytes,6,opt,name=last_msg_preview,json=lastMsgPreview,proto3" json:"last_msg_preview,omitempty"`
	UnreadCount      int32                  `protobuf:"varint,7,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"`
	IsPinned         int32                  `protobuf:"varint,8,opt,name=is_pinned,json=isPinned,proto3" json:"is_pinned,omitempty"` // 0否 1是
	IsMuted          int32                  `protobuf:"varint,9,opt,name=is_muted,json=isMuted,proto3" json:"is_muted,omitempty"`    // 0否 1是
	LastInteractTime int64                  `protobuf:"varint,10,opt,name=last_interact_time,json=lastInteractTime,proto3" json:"last_interact_time,omitempty"`
	CreateTime       int64                  `protobuf:"varint,11,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Conversation) Reset() {
	*x = Conversation{}
	mi := &file_beehive_m_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Conversation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conversation) ProtoMessage() {}

func (x *Conversation) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conversation.ProtoReflect.Descriptor instead.
func (*Conversation) Descriptor() ([]byte, []int) {
	return file_beehive_m_message_proto_rawDescGZIP(), []int{1}
}

func (x *Conversation) GetConversationId() int64 {
	if x != nil {
		return x.ConversationId
	}
	return 0
}

func (x *Conversation) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Conversation) GetTargetType() int32 {
	if x != nil {
		return x.TargetType
	}
	return 0
}

func (x *Conversation) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *Conversation) GetLastMsgId() int64 {
	if x != nil {
		return x.LastMsgId
	}
	return 0
}

func (x *Conversation) GetLastMsgPreview() string {
	if x != nil {
		return x.LastMsgPreview
	}
	return ""
}

func (x *Conversation) GetUnreadCount() int32 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

func (x *Conversation) GetIsPinned() int32 {
	if x != nil {
		return x.IsPinned
	}
	return 0
}

func (x *Conversation) GetIsMuted() int32 {
	if x != nil {
		return x.IsMuted
	}
	return 0
}

func (x *Conversation) GetLastInteractTime() int64 {
	if x != nil {
		return x.LastInteractTime
	}
	return 0
}

func (x *Conversation) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

type SendPrivateMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderId      int64                  `protobuf:"varint,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	ReceiverId    int64                  `protobuf:"varint,2,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	ContentType   int32                  `protobuf:"varint,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"` // 1文本 2图片 3文件 4表情
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	FileUrl       string                 `protobuf:"bytes,5,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`
	FileName      string                 `protobuf:"bytes,6,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileSize      int64                  `protobuf:"varint,7,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	RefMsgId      int64                  `protobuf:"varint,8,opt,name=ref_msg_id,json=refMsgId,proto3" json:"ref_msg_id,omitempty"`
	RefSceneType  int32                  `protobuf:"varint,9,opt,name=ref_scene_type,json=refSceneType,proto3" json:"ref_scene_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendPrivateMessageRequest) Reset() {
	*x = SendPrivateMessageRequest{}
	mi := &file_beehive_m_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPrivateMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPrivateMessageRequest) ProtoMessage() {}

func (x *SendPrivateMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPrivateMessageRequest.ProtoReflect.Descriptor instead.
func (*SendPrivateMessageRequest) Descriptor() ([]byte, []int) {
	return file_beehive_m_message_proto_rawDescGZIP(), []int{2}
}

func (x *SendPrivateMessageRequest) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *SendPrivateMessageRequest) GetReceiverId() int64 {
	if x != nil {
		return x.ReceiverId
	}
	return 0
}

func (x *SendPrivateMessageRequest) GetContentType() int32 {
	if x != nil {
		return x.ContentType
	}
	return 0
}

func (x *SendPrivateMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendPrivateMessageRequest) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

func (x *SendPrivateMessageRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *SendPrivateMessageRequest) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *SendPrivateMessageRequest) GetRefMsgId() int64 {
	if x != nil {
		return x.RefMsgId
	}
	return 0
}

func (x *SendPrivateMessageRequest) GetRefSceneType() int32 {
	if x != nil {
		return x.RefSceneType
	}
	return 0
}

type SendPrivateMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         int64                  `protobuf:"varint,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendPrivateMessageResponse) Reset() {
	*x = SendPrivateMessageResponse{}
	mi := &file_beehive_m_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPrivateMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPrivateMessageResponse) ProtoMessage() {}

func (x *SendPrivateMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPrivateMessageResponse.ProtoReflect.Descriptor instead.
func (*SendPrivateMessageResponse) Descriptor() ([]byte, []int) {
	return file_beehive_m_message_proto_rawDescGZIP(), []int{3}
}

func (x *SendPrivateMessageResponse) GetMsgId() int64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

type ListPrivateMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderId      int64                  `protobuf:"varint,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	ReceiverId    int64                  `protobuf:"varint,2,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	BeforeMsgId   int64                  `protobuf:"varint,3,opt,name=before_msg_id,json=beforeMsgId,proto3" json:"before_msg_id,omitempty"` // 取此 msg_id 之前的消息，0 表示最新
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`                                  // 条数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPrivateMessagesRequest) Reset() {
	*x = ListPrivateMessagesRequest{}
	mi := &file_beehive_m_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPrivateMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPrivateMessagesRequest) ProtoMessage() {}

func (x *ListPrivateMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPrivateMessagesRequest.ProtoReflect.Descriptor instead.
func (*ListPrivateMessagesRequest) Descriptor() ([]byte, []int) {
	return file_beehive_m_message_proto_rawDescGZIP(), []int{4}
}

func (x *ListPrivateMessagesRequest) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *ListPrivateMessagesRequest) GetReceiverId() int64 {
	if x != nil {
		return x.ReceiverId
	}
	return 0
}

func (x *ListPrivateMessagesRequest) GetBeforeMsgId() int64 {
	if x != nil {
		return x.BeforeMsgId
	}
	return 0
}

func (x *ListPrivateMessagesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListPrivateMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPrivateMessagesResponse) Reset() {
	*x = ListPrivateMessagesResponse{}
	mi := &file_beehive_m_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPrivateMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPrivateMessagesResponse) ProtoMessage() {}

func (x *ListPrivateMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPrivateMessagesResponse.ProtoReflect.Descriptor instead.
func (*ListPrivateMessagesResponse) Descriptor() ([]byte, []int) {
	return file_beehive_m_message_proto_rawDescGZIP(), []int{5}
}

func (x *ListPrivateMessagesResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ListPrivateMessagesResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type MarkPrivateReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReceiverId    int64                  `protobuf:"varint,1,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"` // 当前用户
	MsgId         int64                  `protobuf:"varint,2,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`                // 已读到该 msg_id（含）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkPrivateReadRequest) Reset() {
	*x = MarkPrivateReadRequest{}
	mi := &file_beehive_m_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkPrivateReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkPrivateReadRequest) ProtoMessage() {}

func (x *MarkPrivateReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkPrivateReadRequest.ProtoReflect.Descriptor instead.
func (*MarkPrivateReadRequest) Descriptor() ([]byte, []int) {
	return file_beehive_m_message_proto_rawDescGZIP(), []int{6}
}

func (x *MarkPrivateReadRequest) GetReceiverId() int64 {
	if x != nil {
		return x.ReceiverId
	}
	return 0
}

func (x *MarkPrivateReadRequest) GetMsgId() int64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

type MarkPrivateReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkPrivateReadResponse) Reset() {
	*x = MarkPrivateReadResponse{}
	mi := &file_beehive_m_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkPrivateReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkPrivateReadResponse) ProtoMessage() {}

func (x *MarkPrivateReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkPrivateReadResponse.ProtoReflect.Descriptor instead.
func (*MarkPrivateReadResponse) Descriptor() ([]byte, []int) {
	return file_beehive_m_message_proto_rawDescGZIP(), []int{7}
}

type GetPrivateUnreadCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReceiverId    int64                  `protobuf:"varint,1,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"` // 当前用户
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPrivateUnreadCountRequest) Reset() {
	*x = GetPrivateUnreadCountRequest{}
	mi := &file_beehive_m_message_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPrivateUnreadCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPrivateUnreadCountRequest) ProtoMessage() {}

func (x *GetPrivateUnreadCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_message_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPrivateUnreadCountRequest.ProtoReflect.Descriptor instead.
func (*GetPrivateUnreadCountRequest) Descriptor() ([]byte, []int) {
	return file_beehive_m_message_proto_rawDescGZIP(), []int{8}
}

func (x *GetPrivateUnreadCountRequest) GetReceiverId() int64 {
	if x != nil {
		return x.ReceiverId
	}
	return 0
}

type GetPrivateUnreadCountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPrivateUnreadCountResponse) Reset() {
	*x = GetPrivateUnreadCountResponse{}
	mi := &file_beehive_m_message_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPrivateUnreadCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPrivateUnreadCountResponse) ProtoMessage() {}

func (x *GetPrivateUnreadCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_message_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPrivateUnreadCountResponse.ProtoReflect.Descriptor instead.
func (*GetPrivateUnreadCountResponse) Descriptor() ([]byte, []int) {
	return file_beehive_m_message_proto_rawDescGZIP(), []int{9}
}

func (x *GetPrivateUnreadCountResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type SendGroupMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	SenderId      int64                  `protobuf:"varint,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	ContentType   int32                  `protobuf:"varint,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"` // 1文本 2图片 3文件 4表情
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	FileUrl       string                 `protobuf:"bytes,5,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`
	FileName      string                 `protobuf:"bytes,6,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileSize      int64                  `protobuf:"varint,7,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	AtUserIds     string                 `protobuf:"bytes,8,opt,name=at_user_ids,json=atUserIds,proto3" json:"at_user_ids,omitempty"` // JSON 数组
	RefMsgId      int64                  `protobuf:"varint,9,opt,name=ref_msg_id,json=refMsgId,proto3" json:"ref_msg_id,omitempty"`
	RefSceneType  int32                  `protobuf:"varint,10,opt,name=ref_scene_type,json=refSceneType,proto3" json:"ref_scene_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendGroupMessageRequest) Reset() {
	*x = SendGroupMessageRequest{}
	mi := &file_beehive_m_message_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendGroupMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendGroupMessageRequest) ProtoMessage() {}

func (x *SendGroupMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_message_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendGroupMessageRequest.ProtoReflect.Descriptor instead.
func (*SendGroupMessageRequest) Descriptor() ([]byte, []int) {
	return file_beehive_m_message_proto_rawDescGZIP(), []int{10}
}

func (x *SendGroupMessageRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *SendGroupMessageRequest) GetSenderId() int64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *SendGroupMessageRequest) GetContentType() int32 {
	if x != nil {
		return x.ContentType
	}
	return 0
}

func (x *SendGroupMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendGroupMessageRequest) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

func (x *SendGroupMessageRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *SendGroupMessageRequest) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *SendGroupMessageRequest) GetAtUserIds() string {
	if x != nil {
		return x.AtUserIds
	}
	return ""
}

func (x *SendGroupMessageRequest) GetRefMsgId() int64 {
	if x != nil {
		return x.RefMsgId
	}
	return 0
}

func (x *SendGroupMessageRequest) GetRefSceneType() int32 {
	if x != nil {
		return x.RefSceneType
	}
	return 0
}

type SendGroupMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         int64                  `protobuf:"varint,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendGroupMessageResponse) Reset() {
	*x = SendGroupMessageResponse{}
	mi := &file_beehive_m_message_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendGroupMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendGroupMessageResponse) ProtoMessage() {}

func (x *SendGroupMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_message_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendGroupMessageResponse.ProtoReflect.Descriptor instead.
func (*SendGroupMessageResponse) Descriptor() ([]byte, []int) {
	return file_beehive_m_message_proto_rawDescGZIP(), []int{11}
}

func (x *SendGroupMessageResponse) GetMsgId() int64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

type ListGroupMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	BeforeMsgId   int64                  `protobuf:"varint,2,opt,name=before_msg_id,json=beforeMsgId,proto3" json:"before_msg_id,omitempty"` // 0 表示最新
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupMessagesRequest) Reset() {
	*x = ListGroupMessagesRequest{}
	mi := &file_beehive_m_message_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupMessagesRequest) ProtoMessage() {}

func (x *ListGroupMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_message_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupMessagesRequest.ProtoReflect.Descriptor instead.
func (*ListGroupMessagesRequest) Descriptor() ([]byte, []int) {
	return file_beehive_m_message_proto_rawDescGZIP(), []int{12}
}

func (x *ListGroupMessagesRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *ListGroupMessagesRequest) GetBeforeMsgId() int64 {
	if x != nil {
		return x.BeforeMsgId
	}
	return 0
}

func (x *ListGroupMessagesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListGroupMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupMessagesResponse) Reset() {
	*x = ListGroupMessagesResponse{}
	mi := &file_beehive_m_message_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupMessagesResponse) ProtoMessage() {}

func (x *ListGroupMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_message_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupMessagesResponse.ProtoReflect.Descriptor instead.
func (*ListGroupMessagesResponse) Descriptor() ([]byte, []int) {
	return file_beehive_m_message_proto_rawDescGZIP(), []int{13}
}

func (x *ListGroupMessagesResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ListGroupMessagesResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type MarkGroupReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GroupId       int64                  `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	LastReadMsgId int64                  `protobuf:"varint,3,opt,name=last_read_msg_id,json=lastReadMsgId,proto3" json:"last_read_msg_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkGroupReadRequest) Reset() {
	*x = MarkGroupReadRequest{}
	mi := &file_beehive_m_message_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkGroupReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkGroupReadRequest) ProtoMessage() {}

func (x *MarkGroupReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_message_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkGroupReadRequest.ProtoReflect.Descriptor instead.
func (*MarkGroupReadRequest) Descriptor() ([]byte, []int) {
	return file_beehive_m_message_proto_rawDescGZIP(), []int{14}
}

func (x *MarkGroupReadRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MarkGroupReadRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *MarkGroupReadRequest) GetLastReadMsgId() int64 {
	if x != nil {
		return x.LastReadMsgId
	}
	return 0
}

type MarkGroupReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkGroupReadResponse) Reset() {
	*x = MarkGroupReadResponse{}
	mi := &file_beehive_m_message_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkGroupReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkGroupReadResponse) ProtoMessage() {}

func (x *MarkGroupReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_message_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkGroupReadResponse.ProtoReflect.Descriptor instead.
func (*MarkGroupReadResponse) Descriptor() ([]byte, []int) {
	return file_beehive_m_message_proto_rawDescGZIP(), []int{15}
}

type GetGroupUnreadCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupUnreadCountRequest) Reset() {
	*x = GetGroupUnreadCountRequest{}
	mi := &file_beehive_m_message_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupUnreadCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupUnreadCountRequest) ProtoMessage() {}

func (x *GetGroupUnreadCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_message_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupUnreadCountRequest.ProtoReflect.Descriptor instead.
func (*GetGroupUnreadCountRequest) Descriptor() ([]byte, []int) {
	return file_beehive_m_message_proto_rawDescGZIP(), []int{16}
}

func (x *GetGroupUnreadCountRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetGroupUnreadCountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupUnreadCountResponse) Reset() {
	*x = GetGroupUnreadCountResponse{}
	mi := &file_beehive_m_message_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupUnreadCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupUnreadCountResponse) ProtoMessage() {}

func (x *GetGroupUnreadCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_message_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupUnreadCountResponse.ProtoReflect.Descriptor instead.
func (*GetGroupUnreadCountResponse) Descriptor() ([]byte, []int) {
	return file_beehive_m_message_proto_rawDescGZIP(), []int{17}
}

func (x *GetGroupUnreadCountResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type RecallMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         int64                  `protobuf:"varint,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	SceneType     int32                  `protobuf:"varint,2,opt,name=scene_type,json=sceneType,proto3" json:"scene_type,omitempty"` // 1私聊 2群聊
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecallMessageRequest) Reset() {
	*x = RecallMessageRequest{}
	mi := &file_beehive_m_message_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecallMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecallMessageRequest) ProtoMessage() {}

func (x *RecallMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_message_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecallMessageRequest.ProtoReflect.Descriptor instead.
func (*RecallMessageRequest) Descriptor() ([]byte, []int) {
	return file_beehive_m_message_proto_rawDescGZIP(), []int{18}
}

func (x *RecallMessageRequest) GetMsgId() int64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *RecallMessageRequest) GetSceneType() int32 {
	if x != nil {
		return x.SceneType
	}
	return 0
}

type RecallMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecallMessageResponse) Reset() {
	*x = RecallMessageResponse{}
	mi := &file_beehive_m_message_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecallMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecallMessageResponse) ProtoMessage() {}

func (x *RecallMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_message_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecallMessageResponse.ProtoReflect.Descriptor instead.
func (*RecallMessageResponse) Descriptor() ([]byte, []int) {
	return file_beehive_m_message_proto_rawDescGZIP(), []int{19}
}

type GetMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         int64                  `protobuf:"varint,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	SceneType     int32                  `protobuf:"varint,2,opt,name=scene_type,json=sceneType,proto3" json:"scene_type,omitempty"` // 1私聊 2群聊
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageRequest) Reset() {
	*x = GetMessageRequest{}
	mi := &file_beehive_m_message_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageRequest) ProtoMessage() {}

func (x *GetMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_message_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageRequest.ProtoReflect.Descriptor instead.
func (*GetMessageRequest) Descriptor() ([]byte, []int) {
	return file_beehive_m_message_proto_rawDescGZIP(), []int{20}
}

func (x *GetMessageRequest) GetMsgId() int64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *GetMessageRequest) GetSceneType() int32 {
	if x != nil {
		return x.SceneType
	}
	return 0
}

type GetMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *Message               `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessageResponse) Reset() {
	*x = GetMessageResponse{}
	mi := &file_beehive_m_message_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessageResponse) ProtoMessage() {}

func (x *GetMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_message_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessageResponse.ProtoReflect.Descriptor instead.
func (*GetMessageResponse) Descriptor() ([]byte, []int) {
	return file_beehive_m_message_proto_rawDescGZIP(), []int{21}
}

func (x *GetMessageResponse) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type MessageReference struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ReferenceId       int64                  `protobuf:"varint,1,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`
	MsgId             int64                  `protobuf:"varint,2,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	SceneType         int32                  `protobuf:"varint,3,opt,name=scene_type,json=sceneType,proto3" json:"scene_type,omitempty"` // 当前消息场景：1私聊 2群聊
	RefMsgId          int64                  `protobuf:"varint,4,opt,name=ref_msg_id,json=refMsgId,proto3" json:"ref_msg_id,omitempty"`
	RefSceneType      int32                  `protobuf:"varint,5,opt,name=ref_scene_type,json=refSceneType,proto3" json:"ref_scene_type,omitempty"` // 被引用消息场景：1私聊 2群聊
	RefSenderId       int64                  `protobuf:"varint,6,opt,name=ref_sender_id,json=refSenderId,proto3" json:"ref_sender_id,omitempty"`
	RefContentPreview string                 `protobuf:"bytes,7,opt,name=ref_content_preview,json=refContentPreview,proto3" json:"ref_content_preview,omitempty"`
	CreateTime        int64                  `protobuf:"varint,8,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MessageReference) Reset() {
	*x = MessageReference{}
	mi := &file_beehive_m_message_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageReference) ProtoMessage() {}

func (x *MessageReference) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_message_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageReference.ProtoReflect.Descriptor instead.
func (*MessageReference) Descriptor() ([]byte, []int) {
	return file_beehive_m_message_proto_rawDescGZIP(), []int{22}
}

func (x *MessageReference) GetReferenceId() int64 {
	if x != nil {
		return x.ReferenceId
	}
	return 0
}

func (x *MessageReference) GetMsgId() int64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *MessageReference) GetSceneType() int32 {
	if x != nil {
		return x.SceneType
	}
	return 0
}

func (x *MessageReference) GetRefMsgId() int64 {
	if x != nil {
		return x.RefMsgId
	}
	return 0
}

func (x *MessageReference) GetRefSceneType() int32 {
	if x != nil {
		return x.RefSceneType
	}
	return 0
}

func (x *MessageReference) GetRefSenderId() int64 {
	if x != nil {
		return x.RefSenderId
	}
	return 0
}

func (x *MessageReference) GetRefContentPreview() string {
	if x != nil {
		return x.RefContentPreview
	}
	return ""
}

func (x *MessageReference) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

type ListMessageReferencesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MsgId         int64                  `protobuf:"varint,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	SceneType     int32                  `protobuf:"varint,2,opt,name=scene_type,json=sceneType,proto3" json:"scene_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMessageReferencesRequest) Reset() {
	*x = ListMessageReferencesRequest{}
	mi := &file_beehive_m_message_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessageReferencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessageReferencesRequest) ProtoMessage() {}

func (x *ListMessageReferencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_message_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessageReferencesRequest.ProtoReflect.Descriptor instead.
func (*ListMessageReferencesRequest) Descriptor() ([]byte, []int) {
	return file_beehive_m_message_proto_rawDescGZIP(), []int{23}
}

func (x *ListMessageReferencesRequest) GetMsgId() int64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *ListMessageReferencesRequest) GetSceneType() int32 {
	if x != nil {
		return x.SceneType
	}
	return 0
}

type ListMessageReferencesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	References    []*MessageReference    `protobuf:"bytes,1,rep,name=references,proto3" json:"references,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMessageReferencesResponse) Reset() {
	*x = ListMessageReferencesResponse{}
	mi := &file_beehive_m_message_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessageReferencesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessageReferencesResponse) ProtoMessage() {}

func (x *ListMessageReferencesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_message_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessageReferencesResponse.ProtoReflect.Descriptor instead.
func (*ListMessageReferencesResponse) Descriptor() ([]byte, []int) {
	return file_beehive_m_message_proto_rawDescGZIP(), []int{24}
}

func (x *ListMessageReferencesResponse) GetReferences() []*MessageReference {
	if x != nil {
		return x.References
	}
	return nil
}

type ListConversationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConversationsRequest) Reset() {
	*x = ListConversationsRequest{}
	mi := &file_beehive_m_message_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConversationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConversationsRequest) ProtoMessage() {}

func (x *ListConversationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_message_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConversationsRequest.ProtoReflect.Descriptor instead.
func (*ListConversationsRequest) Descriptor() ([]byte, []int) {
	return file_beehive_m_message_proto_rawDescGZIP(), []int{25}
}

func (x *ListConversationsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListConversationsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListConversationsRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListConversationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conversations []*Conversation        `protobuf:"bytes,1,rep,name=conversations,proto3" json:"conversations,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListConversationsResponse) Reset() {
	*x = ListConversationsResponse{}
	mi := &file_beehive_m_message_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListConversationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListConversationsResponse) ProtoMessage() {}

func (x *ListConversationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_message_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListConversationsResponse.ProtoReflect.Descriptor instead.
func (*ListConversationsResponse) Descriptor() ([]byte, []int) {
	return file_beehive_m_message_proto_rawDescGZIP(), []int{26}
}

func (x *ListConversationsResponse) GetConversations() []*Conversation {
	if x != nil {
		return x.Conversations
	}
	return nil
}

func (x *ListConversationsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type SetConversationPinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TargetType    int32                  `protobuf:"varint,2,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	TargetId      int64                  `protobuf:"varint,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	IsPinned      int32                  `protobuf:"varint,4,opt,name=is_pinned,json=isPinned,proto3" json:"is_pinned,omitempty"` // 0否 1是
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetConversationPinRequest) Reset() {
	*x = SetConversationPinRequest{}
	mi := &file_beehive_m_message_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetConversationPinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConversationPinRequest) ProtoMessage() {}

func (x *SetConversationPinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_message_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetConversationPinRequest.ProtoReflect.Descriptor instead.
func (*SetConversationPinRequest) Descriptor() ([]byte, []int) {
	return file_beehive_m_message_proto_rawDescGZIP(), []int{27}
}

func (x *SetConversationPinRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SetConversationPinRequest) GetTargetType() int32 {
	if x != nil {
		return x.TargetType
	}
	return 0
}

func (x *SetConversationPinRequest) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *SetConversationPinRequest) GetIsPinned() int32 {
	if x != nil {
		return x.IsPinned
	}
	return 0
}

type SetConversationPinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetConversationPinResponse) Reset() {
	*x = SetConversationPinResponse{}
	mi := &file_beehive_m_message_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetConversationPinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConversationPinResponse) ProtoMessage() {}

func (x *SetConversationPinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_message_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetConversationPinResponse.ProtoReflect.Descriptor instead.
func (*SetConversationPinResponse) Descriptor() ([]byte, []int) {
	return file_beehive_m_message_proto_rawDescGZIP(), []int{28}
}

type SetConversationMuteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TargetType    int32                  `protobuf:"varint,2,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"`
	TargetId      int64                  `protobuf:"varint,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	IsMuted       int32                  `protobuf:"varint,4,opt,name=is_muted,json=isMuted,proto3" json:"is_muted,omitempty"` // 0否 1是
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetConversationMuteRequest) Reset() {
	*x = SetConversationMuteRequest{}
	mi := &file_beehive_m_message_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetConversationMuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConversationMuteRequest) ProtoMessage() {}

func (x *SetConversationMuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_message_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetConversationMuteRequest.ProtoReflect.Descriptor instead.
func (*SetConversationMuteRequest) Descriptor() ([]byte, []int) {
	return file_beehive_m_message_proto_rawDescGZIP(), []int{29}
}

func (x *SetConversationMuteRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SetConversationMuteRequest) GetTargetType() int32 {
	if x != nil {
		return x.TargetType
	}
	return 0
}

func (x *SetConversationMuteRequest) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *SetConversationMuteRequest) GetIsMuted() int32 {
	if x != nil {
		return x.IsMuted
	}
	return 0
}

type SetConversationMuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetConversationMuteResponse) Reset() {
	*x = SetConversationMuteResponse{}
	mi := &file_beehive_m_message_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetConversationMuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConversationMuteResponse) ProtoMessage() {}

func (x *SetConversationMuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_message_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetConversationMuteResponse.ProtoReflect.Descriptor instead.
func (*SetConversationMuteResponse) Descriptor() ([]byte, []int) {
	return file_beehive_m_message_proto_rawDescGZIP(), []int{30}
}

type GetOrCreateConversationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TargetType    int32                  `protobuf:"varint,2,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"` // 1用户 2群组
	TargetId      int64                  `protobuf:"varint,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrCreateConversationRequest) Reset() {
	*x = GetOrCreateConversationRequest{}
	mi := &file_beehive_m_message_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrCreateConversationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrCreateConversationRequest) ProtoMessage() {}

func (x *GetOrCreateConversationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_message_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrCreateConversationRequest.ProtoReflect.Descriptor instead.
func (*GetOrCreateConversationRequest) Descriptor() ([]byte, []int) {
	return file_beehive_m_message_proto_rawDescGZIP(), []int{31}
}

func (x *GetOrCreateConversationRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetOrCreateConversationRequest) GetTargetType() int32 {
	if x != nil {
		return x.TargetType
	}
	return 0
}

func (x *GetOrCreateConversationRequest) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

type GetOrCreateConversationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conversation  *Conversation          `protobuf:"bytes,1,opt,name=conversation,proto3" json:"conversation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrCreateConversationResponse) Reset() {
	*x = GetOrCreateConversationResponse{}
	mi := &file_beehive_m_message_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrCreateConversationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrCreateConversationResponse) ProtoMessage() {}

func (x *GetOrCreateConversationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_message_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrCreateConversationResponse.ProtoReflect.Descriptor instead.
func (*GetOrCreateConversationResponse) Descriptor() ([]byte, []int) {
	return file_beehive_m_message_proto_rawDescGZIP(), []int{32}
}

func (x *GetOrCreateConversationResponse) GetConversation() *Conversation {
	if x != nil {
		return x.Conversation
	}
	return nil
}

type GetSyncCursorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSyncCursorRequest) Reset() {
	*x = GetSyncCursorRequest{}
	mi := &file_beehive_m_message_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSyncCursorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSyncCursorRequest) ProtoMessage() {}

func (x *GetSyncCursorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_message_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSyncCursorRequest.ProtoReflect.Descriptor instead.
func (*GetSyncCursorRequest) Descriptor() ([]byte, []int) {
	return file_beehive_m_message_proto_rawDescGZIP(), []int{33}
}

func (x *GetSyncCursorRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetSyncCursorRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type GetSyncCursorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LastSyncMsgId int64                  `protobuf:"varint,1,opt,name=last_sync_msg_id,json=lastSyncMsgId,proto3" json:"last_sync_msg_id,omitempty"`
	SyncOffset    int64                  `protobuf:"varint,2,opt,name=sync_offset,json=syncOffset,proto3" json:"sync_offset,omitempty"`
	LastSyncTime  int64                  `protobuf:"varint,3,opt,name=last_sync_time,json=lastSyncTime,proto3" json:"last_sync_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSyncCursorResponse) Reset() {
	*x = GetSyncCursorResponse{}
	mi := &file_beehive_m_message_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSyncCursorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSyncCursorResponse) ProtoMessage() {}

func (x *GetSyncCursorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_message_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSyncCursorResponse.ProtoReflect.Descriptor instead.
func (*GetSyncCursorResponse) Descriptor() ([]byte, []int) {
	return file_beehive_m_message_proto_rawDescGZIP(), []int{34}
}

func (x *GetSyncCursorResponse) GetLastSyncMsgId() int64 {
	if x != nil {
		return x.LastSyncMsgId
	}
	return 0
}

func (x *GetSyncCursorResponse) GetSyncOffset() int64 {
	if x != nil {
		return x.SyncOffset
	}
	return 0
}

func (x *GetSyncCursorResponse) GetLastSyncTime() int64 {
	if x != nil {
		return x.LastSyncTime
	}
	return 0
}

type PullMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	LastSyncMsgId int64                  `protobuf:"varint,3,opt,name=last_sync_msg_id,json=lastSyncMsgId,proto3" json:"last_sync_msg_id,omitempty"` // 客户端已有最新消息 id，拉取此之后的增量
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullMessagesRequest) Reset() {
	*x = PullMessagesRequest{}
	mi := &file_beehive_m_message_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullMessagesRequest) ProtoMessage() {}

func (x *PullMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_message_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullMessagesRequest.ProtoReflect.Descriptor instead.
func (*PullMessagesRequest) Descriptor() ([]byte, []int) {
	return file_beehive_m_message_proto_rawDescGZIP(), []int{35}
}

func (x *PullMessagesRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PullMessagesRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *PullMessagesRequest) GetLastSyncMsgId() int64 {
	if x != nil {
		return x.LastSyncMsgId
	}
	return 0
}

func (x *PullMessagesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type PullMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	NextCursor    int64                  `protobuf:"varint,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"` // 更新后的 last_sync_msg_id
	NextOffset    int64                  `protobuf:"varint,3,opt,name=next_offset,json=nextOffset,proto3" json:"next_offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullMessagesResponse) Reset() {
	*x = PullMessagesResponse{}
	mi := &file_beehive_m_message_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullMessagesResponse) ProtoMessage() {}

func (x *PullMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_message_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullMessagesResponse.ProtoReflect.Descriptor instead.
func (*PullMessagesResponse) Descriptor() ([]byte, []int) {
	return file_beehive_m_message_proto_rawDescGZIP(), []int{36}
}

func (x *PullMessagesResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *PullMessagesResponse) GetNextCursor() int64 {
	if x != nil {
		return x.NextCursor
	}
	return 0
}

func (x *PullMessagesResponse) GetNextOffset() int64 {
	if x != nil {
		return x.NextOffset
	}
	return 0
}

var File_beehive_m_message_proto protoreflect.FileDescriptor

const file_beehive_m_message_proto_rawDesc = "" +
	"\n" +
	"\x17beehive-m-message.proto\x12\amessage\"\xcc\x03\n" +
	"\aMessage\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\x03R\x05msgId\x12\x1d\n" +
	"\n" +
	"scene_type\x18\x02 \x01(\x05R\tsceneType\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\x03R\bsenderId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x19\n" +
	"\bfile_url\x18\x05 \x01(\tR\afileUrl\x12\x1b\n" +
	"\tfile_name\x18\x06 \x01(\tR\bfileName\x12\x1b\n" +
	"\tfile_size\x18\a \x01(\x03R\bfileSize\x12\x1b\n" +
	"\tsend_time\x18\b \x01(\x03R\bsendTime\x12\x1f\n" +
	"\vis_recalled\x18\t \x01(\x05R\n" +
	"isRecalled\x12\x1f\n" +
	"\vreceiver_id\x18\n" +
	" \x01(\x03R\n" +
	"receiverId\x12\x19\n" +
	"\bgroup_id\x18\v \x01(\x03R\agroupId\x12\x1e\n" +
	"\vat_user_ids\x18\f \x01(\tR\tatUserIds\x12!\n" +
	"\fcontent_type\x18\r \x01(\x05R\vcontentType\x12\x1c\n" +
	"\n" +
	"ref_msg_id\x18\x0e \x01(\x03R\brefMsgId\x12$\n" +
	"\x0eref_scene_type\x18\x0f \x01(\x05R\frefSceneType\"\x82\x03\n" +
	"\fConversation\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\x03R\x0econversationId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vtarget_type\x18\x03 \x01(\x05R\n" +
	"targetType\x12\x1b\n" +
	"\ttarget_id\x18\x04 \x01(\x03R\btargetId\x12\x1e\n" +
	"\vlast_msg_id\x18\x05 \x01(\x03R\tlastMsgId\x12(\n" +
	"\x10last_msg_preview\x18\x06 \x01(\tR\x0elastMsgPreview\x12!\n" +
	"\funread_count\x18\a \x01(\x05R\vunreadCount\x12\x1b\n" +
	"\tis_pinned\x18\b \x01(\x05R\bisPinned\x12\x19\n" +
	"\bis_muted\x18\t \x01(\x05R\aisMuted\x12,\n" +
	"\x12last_interact_time\x18\n" +
	" \x01(\x03R\x10lastInteractTime\x12\x1f\n" +
	"\vcreate_time\x18\v \x01(\x03R\n" +
	"createTime\"\xaf\x02\n" +
	"\x19SendPrivateMessageRequest\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\x03R\bsenderId\x12\x1f\n" +
	"\vreceiver_id\x18\x02 \x01(\x03R\n" +
	"receiverId\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\x05R\vcontentType\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x19\n" +
	"\bfile_url\x18\x05 \x01(\tR\afileUrl\x12\x1b\n" +
	"\tfile_name\x18\x06 \x01(\tR\bfileName\x12\x1b\n" +
	"\tfile_size\x18\a \x01(\x03R\bfileSize\x12\x1c\n" +
	"\n" +
	"ref_msg_id\x18\b \x01(\x03R\brefMsgId\x12$\n" +
	"\x0eref_scene_type\x18\t \x01(\x05R\frefSceneType\"3\n" +
	"\x1aSendPrivateMessageResponse\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\x03R\x05msgId\"\x94\x01\n" +
	"\x1aListPrivateMessagesRequest\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\x03R\bsenderId\x12\x1f\n" +
	"\vreceiver_id\x18\x02 \x01(\x03R\n" +
	"receiverId\x12\"\n" +
	"\rbefore_msg_id\x18\x03 \x01(\x03R\vbeforeMsgId\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"f\n" +
	"\x1bListPrivateMessagesResponse\x12,\n" +
	"\bmessages\x18\x01 \x03(\v2\x10.message.MessageR\bmessages\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\"P\n" +
	"\x16MarkPrivateReadRequest\x12\x1f\n" +
	"\vreceiver_id\x18\x01 \x01(\x03R\n" +
	"receiverId\x12\x15\n" +
	"\x06msg_id\x18\x02 \x01(\x03R\x05msgId\"\x19\n" +
	"\x17MarkPrivateReadResponse\"?\n" +
	"\x1cGetPrivateUnreadCountRequest\x12\x1f\n" +
	"\vreceiver_id\x18\x01 \x01(\x03R\n" +
	"receiverId\"5\n" +
	"\x1dGetPrivateUnreadCountResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\"\xc7\x02\n" +
	"\x17SendGroupMessageRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\x03R\bsenderId\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\x05R\vcontentType\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x19\n" +
	"\bfile_url\x18\x05 \x01(\tR\afileUrl\x12\x1b\n" +
	"\tfile_name\x18\x06 \x01(\tR\bfileName\x12\x1b\n" +
	"\tfile_size\x18\a \x01(\x03R\bfileSize\x12\x1e\n" +
	"\vat_user_ids\x18\b \x01(\tR\tatUserIds\x12\x1c\n" +
	"\n" +
	"ref_msg_id\x18\t \x01(\x03R\brefMsgId\x12$\n" +
	"\x0eref_scene_type\x18\n" +
	" \x01(\x05R\frefSceneType\"1\n" +
	"\x18SendGroupMessageResponse\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\x03R\x05msgId\"o\n" +
	"\x18ListGroupMessagesRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12\"\n" +
	"\rbefore_msg_id\x18\x02 \x01(\x03R\vbeforeMsgId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"d\n" +
	"\x19ListGroupMessagesResponse\x12,\n" +
	"\bmessages\x18\x01 \x03(\v2\x10.message.MessageR\bmessages\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\"s\n" +
	"\x14MarkGroupReadRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\x03R\agroupId\x12'\n" +
	"\x10last_read_msg_id\x18\x03 \x01(\x03R\rlastReadMsgId\"\x17\n" +
	"\x15MarkGroupReadResponse\"5\n" +
	"\x1aGetGroupUnreadCountRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"3\n" +
	"\x1bGetGroupUnreadCountResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\"L\n" +
	"\x14RecallMessageRequest\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\x03R\x05msgId\x12\x1d\n" +
	"\n" +
	"scene_type\x18\x02 \x01(\x05R\tsceneType\"\x17\n" +
	"\x15RecallMessageResponse\"I\n" +
	"\x11GetMessageRequest\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\x03R\x05msgId\x12\x1d\n" +
	"\n" +
	"scene_type\x18\x02 \x01(\x05R\tsceneType\"@\n" +
	"\x12GetMessageResponse\x12*\n" +
	"\amessage\x18\x01 \x01(\v2\x10.message.MessageR\amessage\"\xa4\x02\n" +
	"\x10MessageReference\x12!\n" +
	"\freference_id\x18\x01 \x01(\x03R\vreferenceId\x12\x15\n" +
	"\x06msg_id\x18\x02 \x01(\x03R\x05msgId\x12\x1d\n" +
	"\n" +
	"scene_type\x18\x03 \x01(\x05R\tsceneType\x12\x1c\n" +
	"\n" +
	"ref_msg_id\x18\x04 \x01(\x03R\brefMsgId\x12$\n" +
	"\x0eref_scene_type\x18\x05 \x01(\x05R\frefSceneType\x12\"\n" +
	"\rref_sender_id\x18\x06 \x01(\x03R\vrefSenderId\x12.\n" +
	"\x13ref_content_preview\x18\a \x01(\tR\x11refContentPreview\x12\x1f\n" +
	"\vcreate_time\x18\b \x01(\x03R\n" +
	"createTime\"T\n" +
	"\x1cListMessageReferencesRequest\x12\x15\n" +
	"\x06msg_id\x18\x01 \x01(\x03R\x05msgId\x12\x1d\n" +
	"\n" +
	"scene_type\x18\x02 \x01(\x05R\tsceneType\"Z\n" +
	"\x1dListMessageReferencesResponse\x129\n" +
	"\n" +
	"references\x18\x01 \x03(\v2\x19.message.MessageReferenceR\n" +
	"references\"[\n" +
	"\x18ListConversationsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x05R\x04size\"n\n" +
	"\x19ListConversationsResponse\x12;\n" +
	"\rconversations\x18\x01 \x03(\v2\x15.message.ConversationR\rconversations\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\x8f\x01\n" +
	"\x19SetConversationPinRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vtarget_type\x18\x02 \x01(\x05R\n" +
	"targetType\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\x03R\btargetId\x12\x1b\n" +
	"\tis_pinned\x18\x04 \x01(\x05R\bisPinned\"\x1c\n" +
	"\x1aSetConversationPinResponse\"\x8e\x01\n" +
	"\x1aSetConversationMuteRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vtarget_type\x18\x02 \x01(\x05R\n" +
	"targetType\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\x03R\btargetId\x12\x19\n" +
	"\bis_muted\x18\x04 \x01(\x05R\aisMuted\"\x1d\n" +
	"\x1bSetConversationMuteResponse\"w\n" +
	"\x1eGetOrCreateConversationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vtarget_type\x18\x02 \x01(\x05R\n" +
	"targetType\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\x03R\btargetId\"\\\n" +
	"\x1fGetOrCreateConversationResponse\x129\n" +
	"\fconversation\x18\x01 \x01(\v2\x15.message.ConversationR\fconversation\"L\n" +
	"\x14GetSyncCursorRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\"\x87\x01\n" +
	"\x15GetSyncCursorResponse\x12'\n" +
	"\x10last_sync_msg_id\x18\x01 \x01(\x03R\rlastSyncMsgId\x12\x1f\n" +
	"\vsync_offset\x18\x02 \x01(\x03R\n" +
	"syncOffset\x12$\n" +
	"\x0elast_sync_time\x18\x03 \x01(\x03R\flastSyncTime\"\x8a\x01\n" +
	"\x13PullMessagesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12'\n" +
	"\x10last_sync_msg_id\x18\x03 \x01(\x03R\rlastSyncMsgId\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"\x86\x01\n" +
	"\x14PullMessagesResponse\x12,\n" +
	"\bmessages\x18\x01 \x03(\v2\x10.message.MessageR\bmessages\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\x03R\n" +
	"nextCursor\x12\x1f\n" +
	"\vnext_offset\x18\x03 \x01(\x03R\n" +
	"nextOffset2\x9d\f\n" +
	"\x0eMessageService\x12]\n" +
	"\x12SendPrivateMessage\x12\".message.SendPrivateMessageRequest\x1a#.message.SendPrivateMessageResponse\x12`\n" +
	"\x13ListPrivateMessages\x12#.message.ListPrivateMessagesRequest\x1a$.message.ListPrivateMessagesResponse\x12T\n" +
	"\x0fMarkPrivateRead\x12\x1f.message.MarkPrivateReadRequest\x1a .message.MarkPrivateReadResponse\x12f\n" +
	"\x15GetPrivateUnreadCount\x12%.message.GetPrivateUnreadCountRequest\x1a&.message.GetPrivateUnreadCountResponse\x12W\n" +
	"\x10SendGroupMessage\x12 .message.SendGroupMessageRequest\x1a!.message.SendGroupMessageResponse\x12Z\n" +
	"\x11ListGroupMessages\x12!.message.ListGroupMessagesRequest\x1a\".message.ListGroupMessagesResponse\x12N\n" +
	"\rMarkGroupRead\x12\x1d.message.MarkGroupReadRequest\x1a\x1e.message.MarkGroupReadResponse\x12`\n" +
	"\x13GetGroupUnreadCount\x12#.message.GetGroupUnreadCountRequest\x1a$.message.GetGroupUnreadCountResponse\x12N\n" +
	"\rRecallMessage\x12\x1d.message.RecallMessageRequest\x1a\x1e.message.RecallMessageResponse\x12E\n" +
	"\n" +
	"GetMessage\x12\x1a.message.GetMessageRequest\x1a\x1b.message.GetMessageResponse\x12f\n" +
	"\x15ListMessageReferences\x12%.message.ListMessageReferencesRequest\x1a&.message.ListMessageReferencesResponse\x12Z\n" +
	"\x11ListConversations\x12!.message.ListConversationsRequest\x1a\".message.ListConversationsResponse\x12]\n" +
	"\x12SetConversationPin\x12\".message.SetConversationPinRequest\x1a#.message.SetConversationPinResponse\x12`\n" +
	"\x13SetConversationMute\x12#.message.SetConversationMuteRequest\x1a$.message.SetConversationMuteResponse\x12l\n" +
	"\x17GetOrCreateConversation\x12'.message.GetOrCreateConversationRequest\x1a(.message.GetOrCreateConversationResponse\x12N\n" +
	"\rGetSyncCursor\x12\x1d.message.GetSyncCursorRequest\x1a\x1e.message.GetSyncCursorResponse\x12K\n" +
	"\fPullMessages\x12\x1c.message.PullMessagesRequest\x1a\x1d.message.PullMessagesResponseB\x15Z\x13services/message/pbb\x06proto3"

var (
	file_beehive_m_message_proto_rawDescOnce sync.Once
	file_beehive_m_message_proto_rawDescData []byte
)

func file_beehive_m_message_proto_rawDescGZIP() []byte {
	file_beehive_m_message_proto_rawDescOnce.Do(func() {
		file_beehive_m_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_beehive_m_message_proto_rawDesc), len(file_beehive_m_message_proto_rawDesc)))
	})
	return file_beehive_m_message_proto_rawDescData
}

var file_beehive_m_message_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_beehive_m_message_proto_goTypes = []any{
	(*Message)(nil),                         // 0: message.Message
	(*Conversation)(nil),                    // 1: message.Conversation
	(*SendPrivateMessageRequest)(nil),       // 2: message.SendPrivateMessageRequest
	(*SendPrivateMessageResponse)(nil),      // 3: message.SendPrivateMessageResponse
	(*ListPrivateMessagesRequest)(nil),      // 4: message.ListPrivateMessagesRequest
	(*ListPrivateMessagesResponse)(nil),     // 5: message.ListPrivateMessagesResponse
	(*MarkPrivateReadRequest)(nil),          // 6: message.MarkPrivateReadRequest
	(*MarkPrivateReadResponse)(nil),         // 7: message.MarkPrivateReadResponse
	(*GetPrivateUnreadCountRequest)(nil),    // 8: message.GetPrivateUnreadCountRequest
	(*GetPrivateUnreadCountResponse)(nil),   // 9: message.GetPrivateUnreadCountResponse
	(*SendGroupMessageRequest)(nil),         // 10: message.SendGroupMessageRequest
	(*SendGroupMessageResponse)(nil),        // 11: message.SendGroupMessageResponse
	(*ListGroupMessagesRequest)(nil),        // 12: message.ListGroupMessagesRequest
	(*ListGroupMessagesResponse)(nil),       // 13: message.ListGroupMessagesResponse
	(*MarkGroupReadRequest)(nil),            // 14: message.MarkGroupReadRequest
	(*MarkGroupReadResponse)(nil),           // 15: message.MarkGroupReadResponse
	(*GetGroupUnreadCountRequest)(nil),      // 16: message.GetGroupUnreadCountRequest
	(*GetGroupUnreadCountResponse)(nil),     // 17: message.GetGroupUnreadCountResponse
	(*RecallMessageRequest)(nil),            // 18: message.RecallMessageRequest
	(*RecallMessageResponse)(nil),           // 19: message.RecallMessageResponse
	(*GetMessageRequest)(nil),               // 20: message.GetMessageRequest
	(*GetMessageResponse)(nil),              // 21: message.GetMessageResponse
	(*MessageReference)(nil),                // 22: message.MessageReference
	(*ListMessageReferencesRequest)(nil),    // 23: message.ListMessageReferencesRequest
	(*ListMessageReferencesResponse)(nil),   // 24: message.ListMessageReferencesResponse
	(*ListConversationsRequest)(nil),        // 25: message.ListConversationsRequest
	(*ListConversationsResponse)(nil),       // 26: message.ListConversationsResponse
	(*SetConversationPinRequest)(nil),       // 27: message.SetConversationPinRequest
	(*SetConversationPinResponse)(nil),      // 28: message.SetConversationPinResponse
	(*SetConversationMuteRequest)(nil),      // 29: message.SetConversationMuteRequest
	(*SetConversationMuteResponse)(nil),     // 30: message.SetConversationMuteResponse
	(*GetOrCreateConversationRequest)(nil),  // 31: message.GetOrCreateConversationRequest
	(*GetOrCreateConversationResponse)(nil), // 32: message.GetOrCreateConversationResponse
	(*GetSyncCursorRequest)(nil),            // 33: message.GetSyncCursorRequest
	(*GetSyncCursorResponse)(nil),           // 34: message.GetSyncCursorResponse
	(*PullMessagesRequest)(nil),             // 35: message.PullMessagesRequest
	(*PullMessagesResponse)(nil),            // 36: message.PullMessagesResponse
}
var file_beehive_m_message_proto_depIdxs = []int32{
	0,  // 0: message.ListPrivateMessagesResponse.messages:type_name -> message.Message
	0,  // 1: message.ListGroupMessagesResponse.messages:type_name -> message.Message
	0,  // 2: message.GetMessageResponse.message:type_name -> message.Message
	22, // 3: message.ListMessageReferencesResponse.references:type_name -> message.MessageReference
	1,  // 4: message.ListConversationsResponse.conversations:type_name -> message.Conversation
	1,  // 5: message.GetOrCreateConversationResponse.conversation:type_name -> message.Conversation
	0,  // 6: message.PullMessagesResponse.messages:type_name -> message.Message
	2,  // 7: message.MessageService.SendPrivateMessage:input_type -> message.SendPrivateMessageRequest
	4,  // 8: message.MessageService.ListPrivateMessages:input_type -> message.ListPrivateMessagesRequest
	6,  // 9: message.MessageService.MarkPrivateRead:input_type -> message.MarkPrivateReadRequest
	8,  // 10: message.MessageService.GetPrivateUnreadCount:input_type -> message.GetPrivateUnreadCountRequest
	10, // 11: message.MessageService.SendGroupMessage:input_type -> message.SendGroupMessageRequest
	12, // 12: message.MessageService.ListGroupMessages:input_type -> message.ListGroupMessagesRequest
	14, // 13: message.MessageService.MarkGroupRead:input_type -> message.MarkGroupReadRequest
	16, // 14: message.MessageService.GetGroupUnreadCount:input_type -> message.GetGroupUnreadCountRequest
	18, // 15: message.MessageService.RecallMessage:input_type -> message.RecallMessageRequest
	20, // 16: message.MessageService.GetMessage:input_type -> message.GetMessageRequest
	23, // 17: message.MessageService.ListMessageReferences:input_type -> message.ListMessageReferencesRequest
	25, // 18: message.MessageService.ListConversations:input_type -> message.ListConversationsRequest
	27, // 19: message.MessageService.SetConversationPin:input_type -> message.SetConversationPinRequest
	29, // 20: message.MessageService.SetConversationMute:input_type -> message.SetConversationMuteRequest
	31, // 21: message.MessageService.GetOrCreateConversation:input_type -> message.GetOrCreateConversationRequest
	33, // 22: message.MessageService.GetSyncCursor:input_type -> message.GetSyncCursorRequest
	35, // 23: message.MessageService.PullMessages:input_type -> message.PullMessagesRequest
	3,  // 24: message.MessageService.SendPrivateMessage:output_type -> message.SendPrivateMessageResponse
	5,  // 25: message.MessageService.ListPrivateMessages:output_type -> message.ListPrivateMessagesResponse
	7,  // 26: message.MessageService.MarkPrivateRead:output_type -> message.MarkPrivateReadResponse
	9,  // 27: message.MessageService.GetPrivateUnreadCount:output_type -> message.GetPrivateUnreadCountResponse
	11, // 28: message.MessageService.SendGroupMessage:output_type -> message.SendGroupMessageResponse
	13, // 29: message.MessageService.ListGroupMessages:output_type -> message.ListGroupMessagesResponse
	15, // 30: message.MessageService.MarkGroupRead:output_type -> message.MarkGroupReadResponse
	17, // 31: message.MessageService.GetGroupUnreadCount:output_type -> message.GetGroupUnreadCountResponse
	19, // 32: message.MessageService.RecallMessage:output_type -> message.RecallMessageResponse
	21, // 33: message.MessageService.GetMessage:output_type -> message.GetMessageResponse
	24, // 34: message.MessageService.ListMessageReferences:output_type -> message.ListMessageReferencesResponse
	26, // 35: message.MessageService.ListConversations:output_type -> message.ListConversationsResponse
	28, // 36: message.MessageService.SetConversationPin:output_type -> message.SetConversationPinResponse
	30, // 37: message.MessageService.SetConversationMute:output_type -> message.SetConversationMuteResponse
	32, // 38: message.MessageService.GetOrCreateConversation:output_type -> message.GetOrCreateConversationResponse
	34, // 39: message.MessageService.GetSyncCursor:output_type -> message.GetSyncCursorResponse
	36, // 40: message.MessageService.PullMessages:output_type -> message.PullMessagesResponse
	24, // [24:41] is the sub-list for method output_type
	7,  // [7:24] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_beehive_m_message_proto_init() }
func file_beehive_m_message_proto_init() {
	if File_beehive_m_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_beehive_m_message_proto_rawDesc), len(file_beehive_m_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_beehive_m_message_proto_goTypes,
		DependencyIndexes: file_beehive_m_message_proto_depIdxs,
		MessageInfos:      file_beehive_m_message_proto_msgTypes,
	}.Build()
	File_beehive_m_message_proto = out.File
	file_beehive_m_message_proto_goTypes = nil
	file_beehive_m_message_proto_depIdxs = nil
}
