// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.4
// source: group.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GroupService_CreateGroup_FullMethodName          = "/group.GroupService/CreateGroup"
	GroupService_GetGroup_FullMethodName             = "/group.GroupService/GetGroup"
	GroupService_UpdateGroup_FullMethodName          = "/group.GroupService/UpdateGroup"
	GroupService_DissolveGroup_FullMethodName        = "/group.GroupService/DissolveGroup"
	GroupService_SearchGroups_FullMethodName         = "/group.GroupService/SearchGroups"
	GroupService_ListMyGroups_FullMethodName         = "/group.GroupService/ListMyGroups"
	GroupService_JoinGroup_FullMethodName            = "/group.GroupService/JoinGroup"
	GroupService_LeaveGroup_FullMethodName           = "/group.GroupService/LeaveGroup"
	GroupService_KickMember_FullMethodName           = "/group.GroupService/KickMember"
	GroupService_ListMembers_FullMethodName          = "/group.GroupService/ListMembers"
	GroupService_UpdateMyNickname_FullMethodName     = "/group.GroupService/UpdateMyNickname"
	GroupService_SetMemberMuted_FullMethodName       = "/group.GroupService/SetMemberMuted"
	GroupService_SetMemberRole_FullMethodName        = "/group.GroupService/SetMemberRole"
	GroupService_ApplyJoin_FullMethodName            = "/group.GroupService/ApplyJoin"
	GroupService_InviteJoin_FullMethodName           = "/group.GroupService/InviteJoin"
	GroupService_ListGroupRequests_FullMethodName    = "/group.GroupService/ListGroupRequests"
	GroupService_ListInvitations_FullMethodName      = "/group.GroupService/ListInvitations"
	GroupService_HandleGroupRequest_FullMethodName   = "/group.GroupService/HandleGroupRequest"
	GroupService_HandleInvitation_FullMethodName     = "/group.GroupService/HandleInvitation"
	GroupService_CreateAnnouncement_FullMethodName   = "/group.GroupService/CreateAnnouncement"
	GroupService_ListAnnouncements_FullMethodName    = "/group.GroupService/ListAnnouncements"
	GroupService_MarkAnnouncementRead_FullMethodName = "/group.GroupService/MarkAnnouncementRead"
	GroupService_ListAdminRoles_FullMethodName       = "/group.GroupService/ListAdminRoles"
	GroupService_GrantRole_FullMethodName            = "/group.GroupService/GrantRole"
	GroupService_RevokeRole_FullMethodName           = "/group.GroupService/RevokeRole"
	GroupService_GetMemberRole_FullMethodName        = "/group.GroupService/GetMemberRole"
)

// GroupServiceClient is the client API for GroupService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GroupService 群组、成员、申请/邀请、公告、管理员角色权限
type GroupServiceClient interface {
	// 群
	CreateGroup(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*CreateGroupResponse, error)
	GetGroup(ctx context.Context, in *GetGroupRequest, opts ...grpc.CallOption) (*GetGroupResponse, error)
	UpdateGroup(ctx context.Context, in *UpdateGroupRequest, opts ...grpc.CallOption) (*UpdateGroupResponse, error)
	DissolveGroup(ctx context.Context, in *DissolveGroupRequest, opts ...grpc.CallOption) (*DissolveGroupResponse, error)
	SearchGroups(ctx context.Context, in *SearchGroupsRequest, opts ...grpc.CallOption) (*SearchGroupsResponse, error)
	ListMyGroups(ctx context.Context, in *ListMyGroupsRequest, opts ...grpc.CallOption) (*ListMyGroupsResponse, error)
	// 成员
	JoinGroup(ctx context.Context, in *JoinGroupRequest, opts ...grpc.CallOption) (*JoinGroupResponse, error)
	LeaveGroup(ctx context.Context, in *LeaveGroupRequest, opts ...grpc.CallOption) (*LeaveGroupResponse, error)
	KickMember(ctx context.Context, in *KickMemberRequest, opts ...grpc.CallOption) (*KickMemberResponse, error)
	ListMembers(ctx context.Context, in *ListMembersRequest, opts ...grpc.CallOption) (*ListMembersResponse, error)
	UpdateMyNickname(ctx context.Context, in *UpdateMyNicknameRequest, opts ...grpc.CallOption) (*UpdateMyNicknameResponse, error)
	SetMemberMuted(ctx context.Context, in *SetMemberMutedRequest, opts ...grpc.CallOption) (*SetMemberMutedResponse, error)
	SetMemberRole(ctx context.Context, in *SetMemberRoleRequest, opts ...grpc.CallOption) (*SetMemberRoleResponse, error)
	// 申请/邀请
	ApplyJoin(ctx context.Context, in *ApplyJoinRequest, opts ...grpc.CallOption) (*ApplyJoinResponse, error)
	InviteJoin(ctx context.Context, in *InviteJoinRequest, opts ...grpc.CallOption) (*InviteJoinResponse, error)
	ListGroupRequests(ctx context.Context, in *ListGroupRequestsRequest, opts ...grpc.CallOption) (*ListGroupRequestsResponse, error)
	ListInvitations(ctx context.Context, in *ListInvitationsRequest, opts ...grpc.CallOption) (*ListInvitationsResponse, error)
	HandleGroupRequest(ctx context.Context, in *HandleGroupRequestRequest, opts ...grpc.CallOption) (*HandleGroupRequestResponse, error)
	HandleInvitation(ctx context.Context, in *HandleInvitationRequest, opts ...grpc.CallOption) (*HandleInvitationResponse, error)
	// 公告
	CreateAnnouncement(ctx context.Context, in *CreateAnnouncementRequest, opts ...grpc.CallOption) (*CreateAnnouncementResponse, error)
	ListAnnouncements(ctx context.Context, in *ListAnnouncementsRequest, opts ...grpc.CallOption) (*ListAnnouncementsResponse, error)
	MarkAnnouncementRead(ctx context.Context, in *MarkAnnouncementReadRequest, opts ...grpc.CallOption) (*MarkAnnouncementReadResponse, error)
	// 管理员角色权限
	ListAdminRoles(ctx context.Context, in *ListAdminRolesRequest, opts ...grpc.CallOption) (*ListAdminRolesResponse, error)
	GrantRole(ctx context.Context, in *GrantRoleRequest, opts ...grpc.CallOption) (*GrantRoleResponse, error)
	RevokeRole(ctx context.Context, in *RevokeRoleRequest, opts ...grpc.CallOption) (*RevokeRoleResponse, error)
	GetMemberRole(ctx context.Context, in *GetMemberRoleRequest, opts ...grpc.CallOption) (*GetMemberRoleResponse, error)
}

type groupServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGroupServiceClient(cc grpc.ClientConnInterface) GroupServiceClient {
	return &groupServiceClient{cc}
}

func (c *groupServiceClient) CreateGroup(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*CreateGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateGroupResponse)
	err := c.cc.Invoke(ctx, GroupService_CreateGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) GetGroup(ctx context.Context, in *GetGroupRequest, opts ...grpc.CallOption) (*GetGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGroupResponse)
	err := c.cc.Invoke(ctx, GroupService_GetGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) UpdateGroup(ctx context.Context, in *UpdateGroupRequest, opts ...grpc.CallOption) (*UpdateGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateGroupResponse)
	err := c.cc.Invoke(ctx, GroupService_UpdateGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) DissolveGroup(ctx context.Context, in *DissolveGroupRequest, opts ...grpc.CallOption) (*DissolveGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DissolveGroupResponse)
	err := c.cc.Invoke(ctx, GroupService_DissolveGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) SearchGroups(ctx context.Context, in *SearchGroupsRequest, opts ...grpc.CallOption) (*SearchGroupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchGroupsResponse)
	err := c.cc.Invoke(ctx, GroupService_SearchGroups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) ListMyGroups(ctx context.Context, in *ListMyGroupsRequest, opts ...grpc.CallOption) (*ListMyGroupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMyGroupsResponse)
	err := c.cc.Invoke(ctx, GroupService_ListMyGroups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) JoinGroup(ctx context.Context, in *JoinGroupRequest, opts ...grpc.CallOption) (*JoinGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinGroupResponse)
	err := c.cc.Invoke(ctx, GroupService_JoinGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) LeaveGroup(ctx context.Context, in *LeaveGroupRequest, opts ...grpc.CallOption) (*LeaveGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LeaveGroupResponse)
	err := c.cc.Invoke(ctx, GroupService_LeaveGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) KickMember(ctx context.Context, in *KickMemberRequest, opts ...grpc.CallOption) (*KickMemberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KickMemberResponse)
	err := c.cc.Invoke(ctx, GroupService_KickMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) ListMembers(ctx context.Context, in *ListMembersRequest, opts ...grpc.CallOption) (*ListMembersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMembersResponse)
	err := c.cc.Invoke(ctx, GroupService_ListMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) UpdateMyNickname(ctx context.Context, in *UpdateMyNicknameRequest, opts ...grpc.CallOption) (*UpdateMyNicknameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateMyNicknameResponse)
	err := c.cc.Invoke(ctx, GroupService_UpdateMyNickname_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) SetMemberMuted(ctx context.Context, in *SetMemberMutedRequest, opts ...grpc.CallOption) (*SetMemberMutedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetMemberMutedResponse)
	err := c.cc.Invoke(ctx, GroupService_SetMemberMuted_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) SetMemberRole(ctx context.Context, in *SetMemberRoleRequest, opts ...grpc.CallOption) (*SetMemberRoleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetMemberRoleResponse)
	err := c.cc.Invoke(ctx, GroupService_SetMemberRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) ApplyJoin(ctx context.Context, in *ApplyJoinRequest, opts ...grpc.CallOption) (*ApplyJoinResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyJoinResponse)
	err := c.cc.Invoke(ctx, GroupService_ApplyJoin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) InviteJoin(ctx context.Context, in *InviteJoinRequest, opts ...grpc.CallOption) (*InviteJoinResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InviteJoinResponse)
	err := c.cc.Invoke(ctx, GroupService_InviteJoin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) ListGroupRequests(ctx context.Context, in *ListGroupRequestsRequest, opts ...grpc.CallOption) (*ListGroupRequestsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListGroupRequestsResponse)
	err := c.cc.Invoke(ctx, GroupService_ListGroupRequests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) ListInvitations(ctx context.Context, in *ListInvitationsRequest, opts ...grpc.CallOption) (*ListInvitationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListInvitationsResponse)
	err := c.cc.Invoke(ctx, GroupService_ListInvitations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) HandleGroupRequest(ctx context.Context, in *HandleGroupRequestRequest, opts ...grpc.CallOption) (*HandleGroupRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandleGroupRequestResponse)
	err := c.cc.Invoke(ctx, GroupService_HandleGroupRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) HandleInvitation(ctx context.Context, in *HandleInvitationRequest, opts ...grpc.CallOption) (*HandleInvitationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandleInvitationResponse)
	err := c.cc.Invoke(ctx, GroupService_HandleInvitation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) CreateAnnouncement(ctx context.Context, in *CreateAnnouncementRequest, opts ...grpc.CallOption) (*CreateAnnouncementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAnnouncementResponse)
	err := c.cc.Invoke(ctx, GroupService_CreateAnnouncement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) ListAnnouncements(ctx context.Context, in *ListAnnouncementsRequest, opts ...grpc.CallOption) (*ListAnnouncementsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAnnouncementsResponse)
	err := c.cc.Invoke(ctx, GroupService_ListAnnouncements_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) MarkAnnouncementRead(ctx context.Context, in *MarkAnnouncementReadRequest, opts ...grpc.CallOption) (*MarkAnnouncementReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarkAnnouncementReadResponse)
	err := c.cc.Invoke(ctx, GroupService_MarkAnnouncementRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) ListAdminRoles(ctx context.Context, in *ListAdminRolesRequest, opts ...grpc.CallOption) (*ListAdminRolesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAdminRolesResponse)
	err := c.cc.Invoke(ctx, GroupService_ListAdminRoles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) GrantRole(ctx context.Context, in *GrantRoleRequest, opts ...grpc.CallOption) (*GrantRoleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GrantRoleResponse)
	err := c.cc.Invoke(ctx, GroupService_GrantRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) RevokeRole(ctx context.Context, in *RevokeRoleRequest, opts ...grpc.CallOption) (*RevokeRoleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeRoleResponse)
	err := c.cc.Invoke(ctx, GroupService_RevokeRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *groupServiceClient) GetMemberRole(ctx context.Context, in *GetMemberRoleRequest, opts ...grpc.CallOption) (*GetMemberRoleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMemberRoleResponse)
	err := c.cc.Invoke(ctx, GroupService_GetMemberRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GroupServiceServer is the server API for GroupService service.
// All implementations must embed UnimplementedGroupServiceServer
// for forward compatibility.
//
// GroupService 群组、成员、申请/邀请、公告、管理员角色权限
type GroupServiceServer interface {
	// 群
	CreateGroup(context.Context, *CreateGroupRequest) (*CreateGroupResponse, error)
	GetGroup(context.Context, *GetGroupRequest) (*GetGroupResponse, error)
	UpdateGroup(context.Context, *UpdateGroupRequest) (*UpdateGroupResponse, error)
	DissolveGroup(context.Context, *DissolveGroupRequest) (*DissolveGroupResponse, error)
	SearchGroups(context.Context, *SearchGroupsRequest) (*SearchGroupsResponse, error)
	ListMyGroups(context.Context, *ListMyGroupsRequest) (*ListMyGroupsResponse, error)
	// 成员
	JoinGroup(context.Context, *JoinGroupRequest) (*JoinGroupResponse, error)
	LeaveGroup(context.Context, *LeaveGroupRequest) (*LeaveGroupResponse, error)
	KickMember(context.Context, *KickMemberRequest) (*KickMemberResponse, error)
	ListMembers(context.Context, *ListMembersRequest) (*ListMembersResponse, error)
	UpdateMyNickname(context.Context, *UpdateMyNicknameRequest) (*UpdateMyNicknameResponse, error)
	SetMemberMuted(context.Context, *SetMemberMutedRequest) (*SetMemberMutedResponse, error)
	SetMemberRole(context.Context, *SetMemberRoleRequest) (*SetMemberRoleResponse, error)
	// 申请/邀请
	ApplyJoin(context.Context, *ApplyJoinRequest) (*ApplyJoinResponse, error)
	InviteJoin(context.Context, *InviteJoinRequest) (*InviteJoinResponse, error)
	ListGroupRequests(context.Context, *ListGroupRequestsRequest) (*ListGroupRequestsResponse, error)
	ListInvitations(context.Context, *ListInvitationsRequest) (*ListInvitationsResponse, error)
	HandleGroupRequest(context.Context, *HandleGroupRequestRequest) (*HandleGroupRequestResponse, error)
	HandleInvitation(context.Context, *HandleInvitationRequest) (*HandleInvitationResponse, error)
	// 公告
	CreateAnnouncement(context.Context, *CreateAnnouncementRequest) (*CreateAnnouncementResponse, error)
	ListAnnouncements(context.Context, *ListAnnouncementsRequest) (*ListAnnouncementsResponse, error)
	MarkAnnouncementRead(context.Context, *MarkAnnouncementReadRequest) (*MarkAnnouncementReadResponse, error)
	// 管理员角色权限
	ListAdminRoles(context.Context, *ListAdminRolesRequest) (*ListAdminRolesResponse, error)
	GrantRole(context.Context, *GrantRoleRequest) (*GrantRoleResponse, error)
	RevokeRole(context.Context, *RevokeRoleRequest) (*RevokeRoleResponse, error)
	GetMemberRole(context.Context, *GetMemberRoleRequest) (*GetMemberRoleResponse, error)
	mustEmbedUnimplementedGroupServiceServer()
}

// UnimplementedGroupServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGroupServiceServer struct{}

func (UnimplementedGroupServiceServer) CreateGroup(context.Context, *CreateGroupRequest) (*CreateGroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateGroup not implemented")
}
func (UnimplementedGroupServiceServer) GetGroup(context.Context, *GetGroupRequest) (*GetGroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGroup not implemented")
}
func (UnimplementedGroupServiceServer) UpdateGroup(context.Context, *UpdateGroupRequest) (*UpdateGroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateGroup not implemented")
}
func (UnimplementedGroupServiceServer) DissolveGroup(context.Context, *DissolveGroupRequest) (*DissolveGroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DissolveGroup not implemented")
}
func (UnimplementedGroupServiceServer) SearchGroups(context.Context, *SearchGroupsRequest) (*SearchGroupsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchGroups not implemented")
}
func (UnimplementedGroupServiceServer) ListMyGroups(context.Context, *ListMyGroupsRequest) (*ListMyGroupsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMyGroups not implemented")
}
func (UnimplementedGroupServiceServer) JoinGroup(context.Context, *JoinGroupRequest) (*JoinGroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method JoinGroup not implemented")
}
func (UnimplementedGroupServiceServer) LeaveGroup(context.Context, *LeaveGroupRequest) (*LeaveGroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LeaveGroup not implemented")
}
func (UnimplementedGroupServiceServer) KickMember(context.Context, *KickMemberRequest) (*KickMemberResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KickMember not implemented")
}
func (UnimplementedGroupServiceServer) ListMembers(context.Context, *ListMembersRequest) (*ListMembersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMembers not implemented")
}
func (UnimplementedGroupServiceServer) UpdateMyNickname(context.Context, *UpdateMyNicknameRequest) (*UpdateMyNicknameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateMyNickname not implemented")
}
func (UnimplementedGroupServiceServer) SetMemberMuted(context.Context, *SetMemberMutedRequest) (*SetMemberMutedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetMemberMuted not implemented")
}
func (UnimplementedGroupServiceServer) SetMemberRole(context.Context, *SetMemberRoleRequest) (*SetMemberRoleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetMemberRole not implemented")
}
func (UnimplementedGroupServiceServer) ApplyJoin(context.Context, *ApplyJoinRequest) (*ApplyJoinResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyJoin not implemented")
}
func (UnimplementedGroupServiceServer) InviteJoin(context.Context, *InviteJoinRequest) (*InviteJoinResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InviteJoin not implemented")
}
func (UnimplementedGroupServiceServer) ListGroupRequests(context.Context, *ListGroupRequestsRequest) (*ListGroupRequestsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListGroupRequests not implemented")
}
func (UnimplementedGroupServiceServer) ListInvitations(context.Context, *ListInvitationsRequest) (*ListInvitationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListInvitations not implemented")
}
func (UnimplementedGroupServiceServer) HandleGroupRequest(context.Context, *HandleGroupRequestRequest) (*HandleGroupRequestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleGroupRequest not implemented")
}
func (UnimplementedGroupServiceServer) HandleInvitation(context.Context, *HandleInvitationRequest) (*HandleInvitationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleInvitation not implemented")
}
func (UnimplementedGroupServiceServer) CreateAnnouncement(context.Context, *CreateAnnouncementRequest) (*CreateAnnouncementResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAnnouncement not implemented")
}
func (UnimplementedGroupServiceServer) ListAnnouncements(context.Context, *ListAnnouncementsRequest) (*ListAnnouncementsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAnnouncements not implemented")
}
func (UnimplementedGroupServiceServer) MarkAnnouncementRead(context.Context, *MarkAnnouncementReadRequest) (*MarkAnnouncementReadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkAnnouncementRead not implemented")
}
func (UnimplementedGroupServiceServer) ListAdminRoles(context.Context, *ListAdminRolesRequest) (*ListAdminRolesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAdminRoles not implemented")
}
func (UnimplementedGroupServiceServer) GrantRole(context.Context, *GrantRoleRequest) (*GrantRoleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GrantRole not implemented")
}
func (UnimplementedGroupServiceServer) RevokeRole(context.Context, *RevokeRoleRequest) (*RevokeRoleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeRole not implemented")
}
func (UnimplementedGroupServiceServer) GetMemberRole(context.Context, *GetMemberRoleRequest) (*GetMemberRoleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMemberRole not implemented")
}
func (UnimplementedGroupServiceServer) mustEmbedUnimplementedGroupServiceServer() {}
func (UnimplementedGroupServiceServer) testEmbeddedByValue()                      {}

// UnsafeGroupServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GroupServiceServer will
// result in compilation errors.
type UnsafeGroupServiceServer interface {
	mustEmbedUnimplementedGroupServiceServer()
}

func RegisterGroupServiceServer(s grpc.ServiceRegistrar, srv GroupServiceServer) {
	// If the following call panics, it indicates UnimplementedGroupServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GroupService_ServiceDesc, srv)
}

func _GroupService_CreateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).CreateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_CreateGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).CreateGroup(ctx, req.(*CreateGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_GetGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).GetGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_GetGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).GetGroup(ctx, req.(*GetGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_UpdateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).UpdateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_UpdateGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).UpdateGroup(ctx, req.(*UpdateGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_DissolveGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DissolveGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).DissolveGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_DissolveGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).DissolveGroup(ctx, req.(*DissolveGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_SearchGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).SearchGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_SearchGroups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).SearchGroups(ctx, req.(*SearchGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_ListMyGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMyGroupsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).ListMyGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_ListMyGroups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).ListMyGroups(ctx, req.(*ListMyGroupsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_JoinGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).JoinGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_JoinGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).JoinGroup(ctx, req.(*JoinGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_LeaveGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaveGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).LeaveGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_LeaveGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).LeaveGroup(ctx, req.(*LeaveGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_KickMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KickMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).KickMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_KickMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).KickMember(ctx, req.(*KickMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_ListMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).ListMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_ListMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).ListMembers(ctx, req.(*ListMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_UpdateMyNickname_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMyNicknameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).UpdateMyNickname(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_UpdateMyNickname_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).UpdateMyNickname(ctx, req.(*UpdateMyNicknameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_SetMemberMuted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetMemberMutedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).SetMemberMuted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_SetMemberMuted_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).SetMemberMuted(ctx, req.(*SetMemberMutedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_SetMemberRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetMemberRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).SetMemberRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_SetMemberRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).SetMemberRole(ctx, req.(*SetMemberRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_ApplyJoin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyJoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).ApplyJoin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_ApplyJoin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).ApplyJoin(ctx, req.(*ApplyJoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_InviteJoin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InviteJoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).InviteJoin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_InviteJoin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).InviteJoin(ctx, req.(*InviteJoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_ListGroupRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGroupRequestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).ListGroupRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_ListGroupRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).ListGroupRequests(ctx, req.(*ListGroupRequestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_ListInvitations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInvitationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).ListInvitations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_ListInvitations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).ListInvitations(ctx, req.(*ListInvitationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_HandleGroupRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleGroupRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).HandleGroupRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_HandleGroupRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).HandleGroupRequest(ctx, req.(*HandleGroupRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_HandleInvitation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleInvitationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).HandleInvitation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_HandleInvitation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).HandleInvitation(ctx, req.(*HandleInvitationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_CreateAnnouncement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAnnouncementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).CreateAnnouncement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_CreateAnnouncement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).CreateAnnouncement(ctx, req.(*CreateAnnouncementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_ListAnnouncements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAnnouncementsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).ListAnnouncements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_ListAnnouncements_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).ListAnnouncements(ctx, req.(*ListAnnouncementsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_MarkAnnouncementRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkAnnouncementReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).MarkAnnouncementRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_MarkAnnouncementRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).MarkAnnouncementRead(ctx, req.(*MarkAnnouncementReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_ListAdminRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAdminRolesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).ListAdminRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_ListAdminRoles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).ListAdminRoles(ctx, req.(*ListAdminRolesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_GrantRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrantRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).GrantRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_GrantRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).GrantRole(ctx, req.(*GrantRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_RevokeRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).RevokeRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_RevokeRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).RevokeRole(ctx, req.(*RevokeRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GroupService_GetMemberRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMemberRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupServiceServer).GetMemberRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupService_GetMemberRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupServiceServer).GetMemberRole(ctx, req.(*GetMemberRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GroupService_ServiceDesc is the grpc.ServiceDesc for GroupService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GroupService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "group.GroupService",
	HandlerType: (*GroupServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateGroup",
			Handler:    _GroupService_CreateGroup_Handler,
		},
		{
			MethodName: "GetGroup",
			Handler:    _GroupService_GetGroup_Handler,
		},
		{
			MethodName: "UpdateGroup",
			Handler:    _GroupService_UpdateGroup_Handler,
		},
		{
			MethodName: "DissolveGroup",
			Handler:    _GroupService_DissolveGroup_Handler,
		},
		{
			MethodName: "SearchGroups",
			Handler:    _GroupService_SearchGroups_Handler,
		},
		{
			MethodName: "ListMyGroups",
			Handler:    _GroupService_ListMyGroups_Handler,
		},
		{
			MethodName: "JoinGroup",
			Handler:    _GroupService_JoinGroup_Handler,
		},
		{
			MethodName: "LeaveGroup",
			Handler:    _GroupService_LeaveGroup_Handler,
		},
		{
			MethodName: "KickMember",
			Handler:    _GroupService_KickMember_Handler,
		},
		{
			MethodName: "ListMembers",
			Handler:    _GroupService_ListMembers_Handler,
		},
		{
			MethodName: "UpdateMyNickname",
			Handler:    _GroupService_UpdateMyNickname_Handler,
		},
		{
			MethodName: "SetMemberMuted",
			Handler:    _GroupService_SetMemberMuted_Handler,
		},
		{
			MethodName: "SetMemberRole",
			Handler:    _GroupService_SetMemberRole_Handler,
		},
		{
			MethodName: "ApplyJoin",
			Handler:    _GroupService_ApplyJoin_Handler,
		},
		{
			MethodName: "InviteJoin",
			Handler:    _GroupService_InviteJoin_Handler,
		},
		{
			MethodName: "ListGroupRequests",
			Handler:    _GroupService_ListGroupRequests_Handler,
		},
		{
			MethodName: "ListInvitations",
			Handler:    _GroupService_ListInvitations_Handler,
		},
		{
			MethodName: "HandleGroupRequest",
			Handler:    _GroupService_HandleGroupRequest_Handler,
		},
		{
			MethodName: "HandleInvitation",
			Handler:    _GroupService_HandleInvitation_Handler,
		},
		{
			MethodName: "CreateAnnouncement",
			Handler:    _GroupService_CreateAnnouncement_Handler,
		},
		{
			MethodName: "ListAnnouncements",
			Handler:    _GroupService_ListAnnouncements_Handler,
		},
		{
			MethodName: "MarkAnnouncementRead",
			Handler:    _GroupService_MarkAnnouncementRead_Handler,
		},
		{
			MethodName: "ListAdminRoles",
			Handler:    _GroupService_ListAdminRoles_Handler,
		},
		{
			MethodName: "GrantRole",
			Handler:    _GroupService_GrantRole_Handler,
		},
		{
			MethodName: "RevokeRole",
			Handler:    _GroupService_RevokeRole_Handler,
		},
		{
			MethodName: "GetMemberRole",
			Handler:    _GroupService_GetMemberRole_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "group.proto",
}
