// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.4
// source: beehive-m-friend.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FriendService_ListFriends_FullMethodName          = "/friend.FriendService/ListFriends"
	FriendService_DeleteFriend_FullMethodName         = "/friend.FriendService/DeleteFriend"
	FriendService_UpdateRemark_FullMethodName         = "/friend.FriendService/UpdateRemark"
	FriendService_SetFriendMuted_FullMethodName       = "/friend.FriendService/SetFriendMuted"
	FriendService_SetFriendSpecial_FullMethodName     = "/friend.FriendService/SetFriendSpecial"
	FriendService_SendFriendRequest_FullMethodName    = "/friend.FriendService/SendFriendRequest"
	FriendService_ListReceivedRequests_FullMethodName = "/friend.FriendService/ListReceivedRequests"
	FriendService_ListSentRequests_FullMethodName     = "/friend.FriendService/ListSentRequests"
	FriendService_HandleFriendRequest_FullMethodName  = "/friend.FriendService/HandleFriendRequest"
	FriendService_AddBlacklist_FullMethodName         = "/friend.FriendService/AddBlacklist"
	FriendService_RemoveBlacklist_FullMethodName      = "/friend.FriendService/RemoveBlacklist"
	FriendService_ListBlacklist_FullMethodName        = "/friend.FriendService/ListBlacklist"
	FriendService_CheckBlacklist_FullMethodName       = "/friend.FriendService/CheckBlacklist"
	FriendService_ListRecommendations_FullMethodName  = "/friend.FriendService/ListRecommendations"
	FriendService_IgnoreRecommendation_FullMethodName = "/friend.FriendService/IgnoreRecommendation"
)

// FriendServiceClient is the client API for FriendService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// FriendService 好友关系、好友申请、黑名单、好友推荐
type FriendServiceClient interface {
	// 好友
	ListFriends(ctx context.Context, in *ListFriendsRequest, opts ...grpc.CallOption) (*ListFriendsResponse, error)
	DeleteFriend(ctx context.Context, in *DeleteFriendRequest, opts ...grpc.CallOption) (*DeleteFriendResponse, error)
	UpdateRemark(ctx context.Context, in *UpdateRemarkRequest, opts ...grpc.CallOption) (*UpdateRemarkResponse, error)
	SetFriendMuted(ctx context.Context, in *SetFriendMutedRequest, opts ...grpc.CallOption) (*SetFriendMutedResponse, error)
	SetFriendSpecial(ctx context.Context, in *SetFriendSpecialRequest, opts ...grpc.CallOption) (*SetFriendSpecialResponse, error)
	// 申请
	SendFriendRequest(ctx context.Context, in *SendFriendRequestRequest, opts ...grpc.CallOption) (*SendFriendRequestResponse, error)
	ListReceivedRequests(ctx context.Context, in *ListReceivedRequestsRequest, opts ...grpc.CallOption) (*ListReceivedRequestsResponse, error)
	ListSentRequests(ctx context.Context, in *ListSentRequestsRequest, opts ...grpc.CallOption) (*ListSentRequestsResponse, error)
	HandleFriendRequest(ctx context.Context, in *HandleFriendRequestRequest, opts ...grpc.CallOption) (*HandleFriendRequestResponse, error)
	// 黑名单
	AddBlacklist(ctx context.Context, in *AddBlacklistRequest, opts ...grpc.CallOption) (*AddBlacklistResponse, error)
	RemoveBlacklist(ctx context.Context, in *RemoveBlacklistRequest, opts ...grpc.CallOption) (*RemoveBlacklistResponse, error)
	ListBlacklist(ctx context.Context, in *ListBlacklistRequest, opts ...grpc.CallOption) (*ListBlacklistResponse, error)
	CheckBlacklist(ctx context.Context, in *CheckBlacklistRequest, opts ...grpc.CallOption) (*CheckBlacklistResponse, error)
	// 推荐
	ListRecommendations(ctx context.Context, in *ListRecommendationsRequest, opts ...grpc.CallOption) (*ListRecommendationsResponse, error)
	IgnoreRecommendation(ctx context.Context, in *IgnoreRecommendationRequest, opts ...grpc.CallOption) (*IgnoreRecommendationResponse, error)
}

type friendServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFriendServiceClient(cc grpc.ClientConnInterface) FriendServiceClient {
	return &friendServiceClient{cc}
}

func (c *friendServiceClient) ListFriends(ctx context.Context, in *ListFriendsRequest, opts ...grpc.CallOption) (*ListFriendsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFriendsResponse)
	err := c.cc.Invoke(ctx, FriendService_ListFriends_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendServiceClient) DeleteFriend(ctx context.Context, in *DeleteFriendRequest, opts ...grpc.CallOption) (*DeleteFriendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteFriendResponse)
	err := c.cc.Invoke(ctx, FriendService_DeleteFriend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendServiceClient) UpdateRemark(ctx context.Context, in *UpdateRemarkRequest, opts ...grpc.CallOption) (*UpdateRemarkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateRemarkResponse)
	err := c.cc.Invoke(ctx, FriendService_UpdateRemark_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendServiceClient) SetFriendMuted(ctx context.Context, in *SetFriendMutedRequest, opts ...grpc.CallOption) (*SetFriendMutedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetFriendMutedResponse)
	err := c.cc.Invoke(ctx, FriendService_SetFriendMuted_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendServiceClient) SetFriendSpecial(ctx context.Context, in *SetFriendSpecialRequest, opts ...grpc.CallOption) (*SetFriendSpecialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetFriendSpecialResponse)
	err := c.cc.Invoke(ctx, FriendService_SetFriendSpecial_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendServiceClient) SendFriendRequest(ctx context.Context, in *SendFriendRequestRequest, opts ...grpc.CallOption) (*SendFriendRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendFriendRequestResponse)
	err := c.cc.Invoke(ctx, FriendService_SendFriendRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendServiceClient) ListReceivedRequests(ctx context.Context, in *ListReceivedRequestsRequest, opts ...grpc.CallOption) (*ListReceivedRequestsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListReceivedRequestsResponse)
	err := c.cc.Invoke(ctx, FriendService_ListReceivedRequests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendServiceClient) ListSentRequests(ctx context.Context, in *ListSentRequestsRequest, opts ...grpc.CallOption) (*ListSentRequestsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSentRequestsResponse)
	err := c.cc.Invoke(ctx, FriendService_ListSentRequests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendServiceClient) HandleFriendRequest(ctx context.Context, in *HandleFriendRequestRequest, opts ...grpc.CallOption) (*HandleFriendRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandleFriendRequestResponse)
	err := c.cc.Invoke(ctx, FriendService_HandleFriendRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendServiceClient) AddBlacklist(ctx context.Context, in *AddBlacklistRequest, opts ...grpc.CallOption) (*AddBlacklistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddBlacklistResponse)
	err := c.cc.Invoke(ctx, FriendService_AddBlacklist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendServiceClient) RemoveBlacklist(ctx context.Context, in *RemoveBlacklistRequest, opts ...grpc.CallOption) (*RemoveBlacklistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveBlacklistResponse)
	err := c.cc.Invoke(ctx, FriendService_RemoveBlacklist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendServiceClient) ListBlacklist(ctx context.Context, in *ListBlacklistRequest, opts ...grpc.CallOption) (*ListBlacklistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBlacklistResponse)
	err := c.cc.Invoke(ctx, FriendService_ListBlacklist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendServiceClient) CheckBlacklist(ctx context.Context, in *CheckBlacklistRequest, opts ...grpc.CallOption) (*CheckBlacklistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckBlacklistResponse)
	err := c.cc.Invoke(ctx, FriendService_CheckBlacklist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendServiceClient) ListRecommendations(ctx context.Context, in *ListRecommendationsRequest, opts ...grpc.CallOption) (*ListRecommendationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRecommendationsResponse)
	err := c.cc.Invoke(ctx, FriendService_ListRecommendations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *friendServiceClient) IgnoreRecommendation(ctx context.Context, in *IgnoreRecommendationRequest, opts ...grpc.CallOption) (*IgnoreRecommendationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IgnoreRecommendationResponse)
	err := c.cc.Invoke(ctx, FriendService_IgnoreRecommendation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FriendServiceServer is the server API for FriendService service.
// All implementations must embed UnimplementedFriendServiceServer
// for forward compatibility.
//
// FriendService 好友关系、好友申请、黑名单、好友推荐
type FriendServiceServer interface {
	// 好友
	ListFriends(context.Context, *ListFriendsRequest) (*ListFriendsResponse, error)
	DeleteFriend(context.Context, *DeleteFriendRequest) (*DeleteFriendResponse, error)
	UpdateRemark(context.Context, *UpdateRemarkRequest) (*UpdateRemarkResponse, error)
	SetFriendMuted(context.Context, *SetFriendMutedRequest) (*SetFriendMutedResponse, error)
	SetFriendSpecial(context.Context, *SetFriendSpecialRequest) (*SetFriendSpecialResponse, error)
	// 申请
	SendFriendRequest(context.Context, *SendFriendRequestRequest) (*SendFriendRequestResponse, error)
	ListReceivedRequests(context.Context, *ListReceivedRequestsRequest) (*ListReceivedRequestsResponse, error)
	ListSentRequests(context.Context, *ListSentRequestsRequest) (*ListSentRequestsResponse, error)
	HandleFriendRequest(context.Context, *HandleFriendRequestRequest) (*HandleFriendRequestResponse, error)
	// 黑名单
	AddBlacklist(context.Context, *AddBlacklistRequest) (*AddBlacklistResponse, error)
	RemoveBlacklist(context.Context, *RemoveBlacklistRequest) (*RemoveBlacklistResponse, error)
	ListBlacklist(context.Context, *ListBlacklistRequest) (*ListBlacklistResponse, error)
	CheckBlacklist(context.Context, *CheckBlacklistRequest) (*CheckBlacklistResponse, error)
	// 推荐
	ListRecommendations(context.Context, *ListRecommendationsRequest) (*ListRecommendationsResponse, error)
	IgnoreRecommendation(context.Context, *IgnoreRecommendationRequest) (*IgnoreRecommendationResponse, error)
	mustEmbedUnimplementedFriendServiceServer()
}

// UnimplementedFriendServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFriendServiceServer struct{}

func (UnimplementedFriendServiceServer) ListFriends(context.Context, *ListFriendsRequest) (*ListFriendsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFriends not implemented")
}
func (UnimplementedFriendServiceServer) DeleteFriend(context.Context, *DeleteFriendRequest) (*DeleteFriendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteFriend not implemented")
}
func (UnimplementedFriendServiceServer) UpdateRemark(context.Context, *UpdateRemarkRequest) (*UpdateRemarkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateRemark not implemented")
}
func (UnimplementedFriendServiceServer) SetFriendMuted(context.Context, *SetFriendMutedRequest) (*SetFriendMutedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetFriendMuted not implemented")
}
func (UnimplementedFriendServiceServer) SetFriendSpecial(context.Context, *SetFriendSpecialRequest) (*SetFriendSpecialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetFriendSpecial not implemented")
}
func (UnimplementedFriendServiceServer) SendFriendRequest(context.Context, *SendFriendRequestRequest) (*SendFriendRequestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendFriendRequest not implemented")
}
func (UnimplementedFriendServiceServer) ListReceivedRequests(context.Context, *ListReceivedRequestsRequest) (*ListReceivedRequestsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListReceivedRequests not implemented")
}
func (UnimplementedFriendServiceServer) ListSentRequests(context.Context, *ListSentRequestsRequest) (*ListSentRequestsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSentRequests not implemented")
}
func (UnimplementedFriendServiceServer) HandleFriendRequest(context.Context, *HandleFriendRequestRequest) (*HandleFriendRequestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleFriendRequest not implemented")
}
func (UnimplementedFriendServiceServer) AddBlacklist(context.Context, *AddBlacklistRequest) (*AddBlacklistResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddBlacklist not implemented")
}
func (UnimplementedFriendServiceServer) RemoveBlacklist(context.Context, *RemoveBlacklistRequest) (*RemoveBlacklistResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveBlacklist not implemented")
}
func (UnimplementedFriendServiceServer) ListBlacklist(context.Context, *ListBlacklistRequest) (*ListBlacklistResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBlacklist not implemented")
}
func (UnimplementedFriendServiceServer) CheckBlacklist(context.Context, *CheckBlacklistRequest) (*CheckBlacklistResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckBlacklist not implemented")
}
func (UnimplementedFriendServiceServer) ListRecommendations(context.Context, *ListRecommendationsRequest) (*ListRecommendationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRecommendations not implemented")
}
func (UnimplementedFriendServiceServer) IgnoreRecommendation(context.Context, *IgnoreRecommendationRequest) (*IgnoreRecommendationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IgnoreRecommendation not implemented")
}
func (UnimplementedFriendServiceServer) mustEmbedUnimplementedFriendServiceServer() {}
func (UnimplementedFriendServiceServer) testEmbeddedByValue()                       {}

// UnsafeFriendServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FriendServiceServer will
// result in compilation errors.
type UnsafeFriendServiceServer interface {
	mustEmbedUnimplementedFriendServiceServer()
}

func RegisterFriendServiceServer(s grpc.ServiceRegistrar, srv FriendServiceServer) {
	// If the following call panics, it indicates UnimplementedFriendServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FriendService_ServiceDesc, srv)
}

func _FriendService_ListFriends_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFriendsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServiceServer).ListFriends(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendService_ListFriends_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServiceServer).ListFriends(ctx, req.(*ListFriendsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendService_DeleteFriend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFriendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServiceServer).DeleteFriend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendService_DeleteFriend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServiceServer).DeleteFriend(ctx, req.(*DeleteFriendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendService_UpdateRemark_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRemarkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServiceServer).UpdateRemark(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendService_UpdateRemark_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServiceServer).UpdateRemark(ctx, req.(*UpdateRemarkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendService_SetFriendMuted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetFriendMutedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServiceServer).SetFriendMuted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendService_SetFriendMuted_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServiceServer).SetFriendMuted(ctx, req.(*SetFriendMutedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendService_SetFriendSpecial_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetFriendSpecialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServiceServer).SetFriendSpecial(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendService_SetFriendSpecial_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServiceServer).SetFriendSpecial(ctx, req.(*SetFriendSpecialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendService_SendFriendRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendFriendRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServiceServer).SendFriendRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendService_SendFriendRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServiceServer).SendFriendRequest(ctx, req.(*SendFriendRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendService_ListReceivedRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReceivedRequestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServiceServer).ListReceivedRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendService_ListReceivedRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServiceServer).ListReceivedRequests(ctx, req.(*ListReceivedRequestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendService_ListSentRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSentRequestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServiceServer).ListSentRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendService_ListSentRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServiceServer).ListSentRequests(ctx, req.(*ListSentRequestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendService_HandleFriendRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleFriendRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServiceServer).HandleFriendRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendService_HandleFriendRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServiceServer).HandleFriendRequest(ctx, req.(*HandleFriendRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendService_AddBlacklist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBlacklistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServiceServer).AddBlacklist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendService_AddBlacklist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServiceServer).AddBlacklist(ctx, req.(*AddBlacklistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendService_RemoveBlacklist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveBlacklistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServiceServer).RemoveBlacklist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendService_RemoveBlacklist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServiceServer).RemoveBlacklist(ctx, req.(*RemoveBlacklistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendService_ListBlacklist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBlacklistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServiceServer).ListBlacklist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendService_ListBlacklist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServiceServer).ListBlacklist(ctx, req.(*ListBlacklistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendService_CheckBlacklist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckBlacklistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServiceServer).CheckBlacklist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendService_CheckBlacklist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServiceServer).CheckBlacklist(ctx, req.(*CheckBlacklistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendService_ListRecommendations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRecommendationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServiceServer).ListRecommendations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendService_ListRecommendations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServiceServer).ListRecommendations(ctx, req.(*ListRecommendationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FriendService_IgnoreRecommendation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IgnoreRecommendationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FriendServiceServer).IgnoreRecommendation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FriendService_IgnoreRecommendation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FriendServiceServer).IgnoreRecommendation(ctx, req.(*IgnoreRecommendationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FriendService_ServiceDesc is the grpc.ServiceDesc for FriendService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FriendService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "friend.FriendService",
	HandlerType: (*FriendServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListFriends",
			Handler:    _FriendService_ListFriends_Handler,
		},
		{
			MethodName: "DeleteFriend",
			Handler:    _FriendService_DeleteFriend_Handler,
		},
		{
			MethodName: "UpdateRemark",
			Handler:    _FriendService_UpdateRemark_Handler,
		},
		{
			MethodName: "SetFriendMuted",
			Handler:    _FriendService_SetFriendMuted_Handler,
		},
		{
			MethodName: "SetFriendSpecial",
			Handler:    _FriendService_SetFriendSpecial_Handler,
		},
		{
			MethodName: "SendFriendRequest",
			Handler:    _FriendService_SendFriendRequest_Handler,
		},
		{
			MethodName: "ListReceivedRequests",
			Handler:    _FriendService_ListReceivedRequests_Handler,
		},
		{
			MethodName: "ListSentRequests",
			Handler:    _FriendService_ListSentRequests_Handler,
		},
		{
			MethodName: "HandleFriendRequest",
			Handler:    _FriendService_HandleFriendRequest_Handler,
		},
		{
			MethodName: "AddBlacklist",
			Handler:    _FriendService_AddBlacklist_Handler,
		},
		{
			MethodName: "RemoveBlacklist",
			Handler:    _FriendService_RemoveBlacklist_Handler,
		},
		{
			MethodName: "ListBlacklist",
			Handler:    _FriendService_ListBlacklist_Handler,
		},
		{
			MethodName: "CheckBlacklist",
			Handler:    _FriendService_CheckBlacklist_Handler,
		},
		{
			MethodName: "ListRecommendations",
			Handler:    _FriendService_ListRecommendations_Handler,
		},
		{
			MethodName: "IgnoreRecommendation",
			Handler:    _FriendService_IgnoreRecommendation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "beehive-m-friend.proto",
}
