// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: beehive-m-friend.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 好友项（与 friends 表对齐）
type FriendItem struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	FriendId         int64                  `protobuf:"varint,1,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`
	Remark           string                 `protobuf:"bytes,2,opt,name=remark,proto3" json:"remark,omitempty"`
	Source           string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`                         // 来源
	IsBlocked        int32                  `protobuf:"varint,4,opt,name=is_blocked,json=isBlocked,proto3" json:"is_blocked,omitempty"` // 0否 1是
	IsSpecial        int32                  `protobuf:"varint,5,opt,name=is_special,json=isSpecial,proto3" json:"is_special,omitempty"` // 0否 1是
	IsMuted          int32                  `protobuf:"varint,6,opt,name=is_muted,json=isMuted,proto3" json:"is_muted,omitempty"`       // 0否 1是
	AddTime          int64                  `protobuf:"varint,7,opt,name=add_time,json=addTime,proto3" json:"add_time,omitempty"`
	LastInteractTime int64                  `protobuf:"varint,8,opt,name=last_interact_time,json=lastInteractTime,proto3" json:"last_interact_time,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FriendItem) Reset() {
	*x = FriendItem{}
	mi := &file_beehive_m_friend_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendItem) ProtoMessage() {}

func (x *FriendItem) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_friend_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendItem.ProtoReflect.Descriptor instead.
func (*FriendItem) Descriptor() ([]byte, []int) {
	return file_beehive_m_friend_proto_rawDescGZIP(), []int{0}
}

func (x *FriendItem) GetFriendId() int64 {
	if x != nil {
		return x.FriendId
	}
	return 0
}

func (x *FriendItem) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *FriendItem) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *FriendItem) GetIsBlocked() int32 {
	if x != nil {
		return x.IsBlocked
	}
	return 0
}

func (x *FriendItem) GetIsSpecial() int32 {
	if x != nil {
		return x.IsSpecial
	}
	return 0
}

func (x *FriendItem) GetIsMuted() int32 {
	if x != nil {
		return x.IsMuted
	}
	return 0
}

func (x *FriendItem) GetAddTime() int64 {
	if x != nil {
		return x.AddTime
	}
	return 0
}

func (x *FriendItem) GetLastInteractTime() int64 {
	if x != nil {
		return x.LastInteractTime
	}
	return 0
}

// 好友申请项（与 friend_requests 表对齐）
type FriendRequestItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     int64                  `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ApplicantId   int64                  `protobuf:"varint,2,opt,name=applicant_id,json=applicantId,proto3" json:"applicant_id,omitempty"`
	TargetId      int64                  `protobuf:"varint,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	Status        int32                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"` // 0待处理 1同意 2拒绝 3忽略
	HandleTime    int64                  `protobuf:"varint,6,opt,name=handle_time,json=handleTime,proto3" json:"handle_time,omitempty"`
	CreateTime    int64                  `protobuf:"varint,7,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendRequestItem) Reset() {
	*x = FriendRequestItem{}
	mi := &file_beehive_m_friend_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendRequestItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendRequestItem) ProtoMessage() {}

func (x *FriendRequestItem) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_friend_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendRequestItem.ProtoReflect.Descriptor instead.
func (*FriendRequestItem) Descriptor() ([]byte, []int) {
	return file_beehive_m_friend_proto_rawDescGZIP(), []int{1}
}

func (x *FriendRequestItem) GetRequestId() int64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *FriendRequestItem) GetApplicantId() int64 {
	if x != nil {
		return x.ApplicantId
	}
	return 0
}

func (x *FriendRequestItem) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *FriendRequestItem) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *FriendRequestItem) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *FriendRequestItem) GetHandleTime() int64 {
	if x != nil {
		return x.HandleTime
	}
	return 0
}

func (x *FriendRequestItem) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

// 黑名单项（与 blacklists 表对齐）
type BlacklistItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BlockedUserId int64                  `protobuf:"varint,2,opt,name=blocked_user_id,json=blockedUserId,proto3" json:"blocked_user_id,omitempty"`
	BlockedType   int32                  `protobuf:"varint,3,opt,name=blocked_type,json=blockedType,proto3" json:"blocked_type,omitempty"` // 1私聊 2群聊 3全部
	Remark        string                 `protobuf:"bytes,4,opt,name=remark,proto3" json:"remark,omitempty"`
	BlockTime     int64                  `protobuf:"varint,5,opt,name=block_time,json=blockTime,proto3" json:"block_time,omitempty"`
	ExpireTime    int64                  `protobuf:"varint,6,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"` // 0 表示永久
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlacklistItem) Reset() {
	*x = BlacklistItem{}
	mi := &file_beehive_m_friend_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlacklistItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlacklistItem) ProtoMessage() {}

func (x *BlacklistItem) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_friend_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlacklistItem.ProtoReflect.Descriptor instead.
func (*BlacklistItem) Descriptor() ([]byte, []int) {
	return file_beehive_m_friend_proto_rawDescGZIP(), []int{2}
}

func (x *BlacklistItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BlacklistItem) GetBlockedUserId() int64 {
	if x != nil {
		return x.BlockedUserId
	}
	return 0
}

func (x *BlacklistItem) GetBlockedType() int32 {
	if x != nil {
		return x.BlockedType
	}
	return 0
}

func (x *BlacklistItem) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *BlacklistItem) GetBlockTime() int64 {
	if x != nil {
		return x.BlockTime
	}
	return 0
}

func (x *BlacklistItem) GetExpireTime() int64 {
	if x != nil {
		return x.ExpireTime
	}
	return 0
}

// 推荐项（与 friend_recommendations 表对齐）
type RecommendationItem struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RecommendedUserId int64                  `protobuf:"varint,2,opt,name=recommended_user_id,json=recommendedUserId,proto3" json:"recommended_user_id,omitempty"`
	Reason            string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Score             float64                `protobuf:"fixed64,4,opt,name=score,proto3" json:"score,omitempty"`
	Source            string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	Status            int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"` // 0未处理 1已添加 2忽略
	CreateTime        int64                  `protobuf:"varint,7,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RecommendationItem) Reset() {
	*x = RecommendationItem{}
	mi := &file_beehive_m_friend_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendationItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendationItem) ProtoMessage() {}

func (x *RecommendationItem) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_friend_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendationItem.ProtoReflect.Descriptor instead.
func (*RecommendationItem) Descriptor() ([]byte, []int) {
	return file_beehive_m_friend_proto_rawDescGZIP(), []int{3}
}

func (x *RecommendationItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RecommendationItem) GetRecommendedUserId() int64 {
	if x != nil {
		return x.RecommendedUserId
	}
	return 0
}

func (x *RecommendationItem) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RecommendationItem) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *RecommendationItem) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *RecommendationItem) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *RecommendationItem) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

type ListFriendsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"` // 从 1 开始，0 表示不分页
	Size          int32                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"` // 每页条数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFriendsRequest) Reset() {
	*x = ListFriendsRequest{}
	mi := &file_beehive_m_friend_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFriendsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFriendsRequest) ProtoMessage() {}

func (x *ListFriendsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_friend_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFriendsRequest.ProtoReflect.Descriptor instead.
func (*ListFriendsRequest) Descriptor() ([]byte, []int) {
	return file_beehive_m_friend_proto_rawDescGZIP(), []int{4}
}

func (x *ListFriendsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListFriendsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListFriendsRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListFriendsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Friends       []*FriendItem          `protobuf:"bytes,1,rep,name=friends,proto3" json:"friends,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFriendsResponse) Reset() {
	*x = ListFriendsResponse{}
	mi := &file_beehive_m_friend_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFriendsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFriendsResponse) ProtoMessage() {}

func (x *ListFriendsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_friend_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFriendsResponse.ProtoReflect.Descriptor instead.
func (*ListFriendsResponse) Descriptor() ([]byte, []int) {
	return file_beehive_m_friend_proto_rawDescGZIP(), []int{5}
}

func (x *ListFriendsResponse) GetFriends() []*FriendItem {
	if x != nil {
		return x.Friends
	}
	return nil
}

func (x *ListFriendsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type DeleteFriendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FriendId      int64                  `protobuf:"varint,2,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFriendRequest) Reset() {
	*x = DeleteFriendRequest{}
	mi := &file_beehive_m_friend_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFriendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFriendRequest) ProtoMessage() {}

func (x *DeleteFriendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_friend_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFriendRequest.ProtoReflect.Descriptor instead.
func (*DeleteFriendRequest) Descriptor() ([]byte, []int) {
	return file_beehive_m_friend_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteFriendRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeleteFriendRequest) GetFriendId() int64 {
	if x != nil {
		return x.FriendId
	}
	return 0
}

type DeleteFriendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFriendResponse) Reset() {
	*x = DeleteFriendResponse{}
	mi := &file_beehive_m_friend_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFriendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFriendResponse) ProtoMessage() {}

func (x *DeleteFriendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_friend_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFriendResponse.ProtoReflect.Descriptor instead.
func (*DeleteFriendResponse) Descriptor() ([]byte, []int) {
	return file_beehive_m_friend_proto_rawDescGZIP(), []int{7}
}

type UpdateRemarkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FriendId      int64                  `protobuf:"varint,2,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`
	Remark        string                 `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRemarkRequest) Reset() {
	*x = UpdateRemarkRequest{}
	mi := &file_beehive_m_friend_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRemarkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRemarkRequest) ProtoMessage() {}

func (x *UpdateRemarkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_friend_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRemarkRequest.ProtoReflect.Descriptor instead.
func (*UpdateRemarkRequest) Descriptor() ([]byte, []int) {
	return file_beehive_m_friend_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateRemarkRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateRemarkRequest) GetFriendId() int64 {
	if x != nil {
		return x.FriendId
	}
	return 0
}

func (x *UpdateRemarkRequest) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type UpdateRemarkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRemarkResponse) Reset() {
	*x = UpdateRemarkResponse{}
	mi := &file_beehive_m_friend_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRemarkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRemarkResponse) ProtoMessage() {}

func (x *UpdateRemarkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_friend_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRemarkResponse.ProtoReflect.Descriptor instead.
func (*UpdateRemarkResponse) Descriptor() ([]byte, []int) {
	return file_beehive_m_friend_proto_rawDescGZIP(), []int{9}
}

type SetFriendMutedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FriendId      int64                  `protobuf:"varint,2,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`
	IsMuted       int32                  `protobuf:"varint,3,opt,name=is_muted,json=isMuted,proto3" json:"is_muted,omitempty"` // 0否 1是
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetFriendMutedRequest) Reset() {
	*x = SetFriendMutedRequest{}
	mi := &file_beehive_m_friend_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetFriendMutedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetFriendMutedRequest) ProtoMessage() {}

func (x *SetFriendMutedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_friend_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetFriendMutedRequest.ProtoReflect.Descriptor instead.
func (*SetFriendMutedRequest) Descriptor() ([]byte, []int) {
	return file_beehive_m_friend_proto_rawDescGZIP(), []int{10}
}

func (x *SetFriendMutedRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SetFriendMutedRequest) GetFriendId() int64 {
	if x != nil {
		return x.FriendId
	}
	return 0
}

func (x *SetFriendMutedRequest) GetIsMuted() int32 {
	if x != nil {
		return x.IsMuted
	}
	return 0
}

type SetFriendMutedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetFriendMutedResponse) Reset() {
	*x = SetFriendMutedResponse{}
	mi := &file_beehive_m_friend_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetFriendMutedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetFriendMutedResponse) ProtoMessage() {}

func (x *SetFriendMutedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_friend_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetFriendMutedResponse.ProtoReflect.Descriptor instead.
func (*SetFriendMutedResponse) Descriptor() ([]byte, []int) {
	return file_beehive_m_friend_proto_rawDescGZIP(), []int{11}
}

type SetFriendSpecialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FriendId      int64                  `protobuf:"varint,2,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"`
	IsSpecial     int32                  `protobuf:"varint,3,opt,name=is_special,json=isSpecial,proto3" json:"is_special,omitempty"` // 0否 1是
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetFriendSpecialRequest) Reset() {
	*x = SetFriendSpecialRequest{}
	mi := &file_beehive_m_friend_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetFriendSpecialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetFriendSpecialRequest) ProtoMessage() {}

func (x *SetFriendSpecialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_friend_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetFriendSpecialRequest.ProtoReflect.Descriptor instead.
func (*SetFriendSpecialRequest) Descriptor() ([]byte, []int) {
	return file_beehive_m_friend_proto_rawDescGZIP(), []int{12}
}

func (x *SetFriendSpecialRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SetFriendSpecialRequest) GetFriendId() int64 {
	if x != nil {
		return x.FriendId
	}
	return 0
}

func (x *SetFriendSpecialRequest) GetIsSpecial() int32 {
	if x != nil {
		return x.IsSpecial
	}
	return 0
}

type SetFriendSpecialResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetFriendSpecialResponse) Reset() {
	*x = SetFriendSpecialResponse{}
	mi := &file_beehive_m_friend_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetFriendSpecialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetFriendSpecialResponse) ProtoMessage() {}

func (x *SetFriendSpecialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_friend_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetFriendSpecialResponse.ProtoReflect.Descriptor instead.
func (*SetFriendSpecialResponse) Descriptor() ([]byte, []int) {
	return file_beehive_m_friend_proto_rawDescGZIP(), []int{13}
}

type SendFriendRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplicantId   int64                  `protobuf:"varint,1,opt,name=applicant_id,json=applicantId,proto3" json:"applicant_id,omitempty"`
	TargetId      int64                  `protobuf:"varint,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendFriendRequestRequest) Reset() {
	*x = SendFriendRequestRequest{}
	mi := &file_beehive_m_friend_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendFriendRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFriendRequestRequest) ProtoMessage() {}

func (x *SendFriendRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_friend_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFriendRequestRequest.ProtoReflect.Descriptor instead.
func (*SendFriendRequestRequest) Descriptor() ([]byte, []int) {
	return file_beehive_m_friend_proto_rawDescGZIP(), []int{14}
}

func (x *SendFriendRequestRequest) GetApplicantId() int64 {
	if x != nil {
		return x.ApplicantId
	}
	return 0
}

func (x *SendFriendRequestRequest) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *SendFriendRequestRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type SendFriendRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     int64                  `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendFriendRequestResponse) Reset() {
	*x = SendFriendRequestResponse{}
	mi := &file_beehive_m_friend_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendFriendRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFriendRequestResponse) ProtoMessage() {}

func (x *SendFriendRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_friend_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFriendRequestResponse.ProtoReflect.Descriptor instead.
func (*SendFriendRequestResponse) Descriptor() ([]byte, []int) {
	return file_beehive_m_friend_proto_rawDescGZIP(), []int{15}
}

func (x *SendFriendRequestResponse) GetRequestId() int64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

type ListReceivedRequestsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      int64                  `protobuf:"varint,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"` // 当前用户
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReceivedRequestsRequest) Reset() {
	*x = ListReceivedRequestsRequest{}
	mi := &file_beehive_m_friend_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReceivedRequestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReceivedRequestsRequest) ProtoMessage() {}

func (x *ListReceivedRequestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_friend_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReceivedRequestsRequest.ProtoReflect.Descriptor instead.
func (*ListReceivedRequestsRequest) Descriptor() ([]byte, []int) {
	return file_beehive_m_friend_proto_rawDescGZIP(), []int{16}
}

func (x *ListReceivedRequestsRequest) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *ListReceivedRequestsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListReceivedRequestsRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListReceivedRequestsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*FriendRequestItem   `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReceivedRequestsResponse) Reset() {
	*x = ListReceivedRequestsResponse{}
	mi := &file_beehive_m_friend_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReceivedRequestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReceivedRequestsResponse) ProtoMessage() {}

func (x *ListReceivedRequestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_friend_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReceivedRequestsResponse.ProtoReflect.Descriptor instead.
func (*ListReceivedRequestsResponse) Descriptor() ([]byte, []int) {
	return file_beehive_m_friend_proto_rawDescGZIP(), []int{17}
}

func (x *ListReceivedRequestsResponse) GetRequests() []*FriendRequestItem {
	if x != nil {
		return x.Requests
	}
	return nil
}

func (x *ListReceivedRequestsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ListSentRequestsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplicantId   int64                  `protobuf:"varint,1,opt,name=applicant_id,json=applicantId,proto3" json:"applicant_id,omitempty"` // 当前用户
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSentRequestsRequest) Reset() {
	*x = ListSentRequestsRequest{}
	mi := &file_beehive_m_friend_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSentRequestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSentRequestsRequest) ProtoMessage() {}

func (x *ListSentRequestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_friend_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSentRequestsRequest.ProtoReflect.Descriptor instead.
func (*ListSentRequestsRequest) Descriptor() ([]byte, []int) {
	return file_beehive_m_friend_proto_rawDescGZIP(), []int{18}
}

func (x *ListSentRequestsRequest) GetApplicantId() int64 {
	if x != nil {
		return x.ApplicantId
	}
	return 0
}

func (x *ListSentRequestsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListSentRequestsRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListSentRequestsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*FriendRequestItem   `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSentRequestsResponse) Reset() {
	*x = ListSentRequestsResponse{}
	mi := &file_beehive_m_friend_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSentRequestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSentRequestsResponse) ProtoMessage() {}

func (x *ListSentRequestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_friend_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSentRequestsResponse.ProtoReflect.Descriptor instead.
func (*ListSentRequestsResponse) Descriptor() ([]byte, []int) {
	return file_beehive_m_friend_proto_rawDescGZIP(), []int{19}
}

func (x *ListSentRequestsResponse) GetRequests() []*FriendRequestItem {
	if x != nil {
		return x.Requests
	}
	return nil
}

func (x *ListSentRequestsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type HandleFriendRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     int64                  `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"` // 1同意 2拒绝 3忽略
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleFriendRequestRequest) Reset() {
	*x = HandleFriendRequestRequest{}
	mi := &file_beehive_m_friend_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleFriendRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleFriendRequestRequest) ProtoMessage() {}

func (x *HandleFriendRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_friend_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleFriendRequestRequest.ProtoReflect.Descriptor instead.
func (*HandleFriendRequestRequest) Descriptor() ([]byte, []int) {
	return file_beehive_m_friend_proto_rawDescGZIP(), []int{20}
}

func (x *HandleFriendRequestRequest) GetRequestId() int64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *HandleFriendRequestRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type HandleFriendRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleFriendRequestResponse) Reset() {
	*x = HandleFriendRequestResponse{}
	mi := &file_beehive_m_friend_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleFriendRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleFriendRequestResponse) ProtoMessage() {}

func (x *HandleFriendRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_friend_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleFriendRequestResponse.ProtoReflect.Descriptor instead.
func (*HandleFriendRequestResponse) Descriptor() ([]byte, []int) {
	return file_beehive_m_friend_proto_rawDescGZIP(), []int{21}
}

type AddBlacklistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BlockedUserId int64                  `protobuf:"varint,2,opt,name=blocked_user_id,json=blockedUserId,proto3" json:"blocked_user_id,omitempty"`
	BlockedType   int32                  `protobuf:"varint,3,opt,name=blocked_type,json=blockedType,proto3" json:"blocked_type,omitempty"` // 1私聊 2群聊 3全部
	Remark        string                 `protobuf:"bytes,4,opt,name=remark,proto3" json:"remark,omitempty"`
	ExpireTime    int64                  `protobuf:"varint,5,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"` // 0 或未传表示永久
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddBlacklistRequest) Reset() {
	*x = AddBlacklistRequest{}
	mi := &file_beehive_m_friend_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBlacklistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBlacklistRequest) ProtoMessage() {}

func (x *AddBlacklistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_friend_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBlacklistRequest.ProtoReflect.Descriptor instead.
func (*AddBlacklistRequest) Descriptor() ([]byte, []int) {
	return file_beehive_m_friend_proto_rawDescGZIP(), []int{22}
}

func (x *AddBlacklistRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddBlacklistRequest) GetBlockedUserId() int64 {
	if x != nil {
		return x.BlockedUserId
	}
	return 0
}

func (x *AddBlacklistRequest) GetBlockedType() int32 {
	if x != nil {
		return x.BlockedType
	}
	return 0
}

func (x *AddBlacklistRequest) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *AddBlacklistRequest) GetExpireTime() int64 {
	if x != nil {
		return x.ExpireTime
	}
	return 0
}

type AddBlacklistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddBlacklistResponse) Reset() {
	*x = AddBlacklistResponse{}
	mi := &file_beehive_m_friend_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBlacklistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBlacklistResponse) ProtoMessage() {}

func (x *AddBlacklistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_friend_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBlacklistResponse.ProtoReflect.Descriptor instead.
func (*AddBlacklistResponse) Descriptor() ([]byte, []int) {
	return file_beehive_m_friend_proto_rawDescGZIP(), []int{23}
}

type RemoveBlacklistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BlockedUserId int64                  `protobuf:"varint,2,opt,name=blocked_user_id,json=blockedUserId,proto3" json:"blocked_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveBlacklistRequest) Reset() {
	*x = RemoveBlacklistRequest{}
	mi := &file_beehive_m_friend_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveBlacklistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveBlacklistRequest) ProtoMessage() {}

func (x *RemoveBlacklistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_friend_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveBlacklistRequest.ProtoReflect.Descriptor instead.
func (*RemoveBlacklistRequest) Descriptor() ([]byte, []int) {
	return file_beehive_m_friend_proto_rawDescGZIP(), []int{24}
}

func (x *RemoveBlacklistRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RemoveBlacklistRequest) GetBlockedUserId() int64 {
	if x != nil {
		return x.BlockedUserId
	}
	return 0
}

type RemoveBlacklistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveBlacklistResponse) Reset() {
	*x = RemoveBlacklistResponse{}
	mi := &file_beehive_m_friend_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveBlacklistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveBlacklistResponse) ProtoMessage() {}

func (x *RemoveBlacklistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_friend_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveBlacklistResponse.ProtoReflect.Descriptor instead.
func (*RemoveBlacklistResponse) Descriptor() ([]byte, []int) {
	return file_beehive_m_friend_proto_rawDescGZIP(), []int{25}
}

type ListBlacklistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBlacklistRequest) Reset() {
	*x = ListBlacklistRequest{}
	mi := &file_beehive_m_friend_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBlacklistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBlacklistRequest) ProtoMessage() {}

func (x *ListBlacklistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_friend_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBlacklistRequest.ProtoReflect.Descriptor instead.
func (*ListBlacklistRequest) Descriptor() ([]byte, []int) {
	return file_beehive_m_friend_proto_rawDescGZIP(), []int{26}
}

func (x *ListBlacklistRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListBlacklistRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListBlacklistRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListBlacklistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*BlacklistItem       `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBlacklistResponse) Reset() {
	*x = ListBlacklistResponse{}
	mi := &file_beehive_m_friend_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBlacklistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBlacklistResponse) ProtoMessage() {}

func (x *ListBlacklistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_friend_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBlacklistResponse.ProtoReflect.Descriptor instead.
func (*ListBlacklistResponse) Descriptor() ([]byte, []int) {
	return file_beehive_m_friend_proto_rawDescGZIP(), []int{27}
}

func (x *ListBlacklistResponse) GetItems() []*BlacklistItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListBlacklistResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CheckBlacklistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BlockedUserId int64                  `protobuf:"varint,2,opt,name=blocked_user_id,json=blockedUserId,proto3" json:"blocked_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckBlacklistRequest) Reset() {
	*x = CheckBlacklistRequest{}
	mi := &file_beehive_m_friend_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckBlacklistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckBlacklistRequest) ProtoMessage() {}

func (x *CheckBlacklistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_friend_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckBlacklistRequest.ProtoReflect.Descriptor instead.
func (*CheckBlacklistRequest) Descriptor() ([]byte, []int) {
	return file_beehive_m_friend_proto_rawDescGZIP(), []int{28}
}

func (x *CheckBlacklistRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CheckBlacklistRequest) GetBlockedUserId() int64 {
	if x != nil {
		return x.BlockedUserId
	}
	return 0
}

type CheckBlacklistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsBlocked     bool                   `protobuf:"varint,1,opt,name=is_blocked,json=isBlocked,proto3" json:"is_blocked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckBlacklistResponse) Reset() {
	*x = CheckBlacklistResponse{}
	mi := &file_beehive_m_friend_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckBlacklistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckBlacklistResponse) ProtoMessage() {}

func (x *CheckBlacklistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_friend_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckBlacklistResponse.ProtoReflect.Descriptor instead.
func (*CheckBlacklistResponse) Descriptor() ([]byte, []int) {
	return file_beehive_m_friend_proto_rawDescGZIP(), []int{29}
}

func (x *CheckBlacklistResponse) GetIsBlocked() bool {
	if x != nil {
		return x.IsBlocked
	}
	return false
}

type ListRecommendationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRecommendationsRequest) Reset() {
	*x = ListRecommendationsRequest{}
	mi := &file_beehive_m_friend_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecommendationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecommendationsRequest) ProtoMessage() {}

func (x *ListRecommendationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_friend_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecommendationsRequest.ProtoReflect.Descriptor instead.
func (*ListRecommendationsRequest) Descriptor() ([]byte, []int) {
	return file_beehive_m_friend_proto_rawDescGZIP(), []int{30}
}

func (x *ListRecommendationsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListRecommendationsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListRecommendationsRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListRecommendationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*RecommendationItem  `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRecommendationsResponse) Reset() {
	*x = ListRecommendationsResponse{}
	mi := &file_beehive_m_friend_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecommendationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecommendationsResponse) ProtoMessage() {}

func (x *ListRecommendationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_friend_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecommendationsResponse.ProtoReflect.Descriptor instead.
func (*ListRecommendationsResponse) Descriptor() ([]byte, []int) {
	return file_beehive_m_friend_proto_rawDescGZIP(), []int{31}
}

func (x *ListRecommendationsResponse) GetItems() []*RecommendationItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListRecommendationsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type IgnoreRecommendationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Id            int64                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"` // recommendation id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IgnoreRecommendationRequest) Reset() {
	*x = IgnoreRecommendationRequest{}
	mi := &file_beehive_m_friend_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IgnoreRecommendationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IgnoreRecommendationRequest) ProtoMessage() {}

func (x *IgnoreRecommendationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_friend_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IgnoreRecommendationRequest.ProtoReflect.Descriptor instead.
func (*IgnoreRecommendationRequest) Descriptor() ([]byte, []int) {
	return file_beehive_m_friend_proto_rawDescGZIP(), []int{32}
}

func (x *IgnoreRecommendationRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *IgnoreRecommendationRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type IgnoreRecommendationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IgnoreRecommendationResponse) Reset() {
	*x = IgnoreRecommendationResponse{}
	mi := &file_beehive_m_friend_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IgnoreRecommendationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IgnoreRecommendationResponse) ProtoMessage() {}

func (x *IgnoreRecommendationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_friend_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IgnoreRecommendationResponse.ProtoReflect.Descriptor instead.
func (*IgnoreRecommendationResponse) Descriptor() ([]byte, []int) {
	return file_beehive_m_friend_proto_rawDescGZIP(), []int{33}
}

var File_beehive_m_friend_proto protoreflect.FileDescriptor

const file_beehive_m_friend_proto_rawDesc = "" +
	"\n" +
	"\x16beehive-m-friend.proto\x12\x06friend\"\xfb\x01\n" +
	"\n" +
	"FriendItem\x12\x1b\n" +
	"\tfriend_id\x18\x01 \x01(\x03R\bfriendId\x12\x16\n" +
	"\x06remark\x18\x02 \x01(\tR\x06remark\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x1d\n" +
	"\n" +
	"is_blocked\x18\x04 \x01(\x05R\tisBlocked\x12\x1d\n" +
	"\n" +
	"is_special\x18\x05 \x01(\x05R\tisSpecial\x12\x19\n" +
	"\bis_muted\x18\x06 \x01(\x05R\aisMuted\x12\x19\n" +
	"\badd_time\x18\a \x01(\x03R\aaddTime\x12,\n" +
	"\x12last_interact_time\x18\b \x01(\x03R\x10lastInteractTime\"\xe4\x01\n" +
	"\x11FriendRequestItem\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x03R\trequestId\x12!\n" +
	"\fapplicant_id\x18\x02 \x01(\x03R\vapplicantId\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\x03R\btargetId\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x05R\x06status\x12\x1f\n" +
	"\vhandle_time\x18\x06 \x01(\x03R\n" +
	"handleTime\x12\x1f\n" +
	"\vcreate_time\x18\a \x01(\x03R\n" +
	"createTime\"\xc2\x01\n" +
	"\rBlacklistItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12&\n" +
	"\x0fblocked_user_id\x18\x02 \x01(\x03R\rblockedUserId\x12!\n" +
	"\fblocked_type\x18\x03 \x01(\x05R\vblockedType\x12\x16\n" +
	"\x06remark\x18\x04 \x01(\tR\x06remark\x12\x1d\n" +
	"\n" +
	"block_time\x18\x05 \x01(\x03R\tblockTime\x12\x1f\n" +
	"\vexpire_time\x18\x06 \x01(\x03R\n" +
	"expireTime\"\xd3\x01\n" +
	"\x12RecommendationItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12.\n" +
	"\x13recommended_user_id\x18\x02 \x01(\x03R\x11recommendedUserId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x01R\x05score\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x12\x1f\n" +
	"\vcreate_time\x18\a \x01(\x03R\n" +
	"createTime\"U\n" +
	"\x12ListFriendsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x05R\x04size\"Y\n" +
	"\x13ListFriendsResponse\x12,\n" +
	"\afriends\x18\x01 \x03(\v2\x12.friend.FriendItemR\afriends\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"K\n" +
	"\x13DeleteFriendRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tfriend_id\x18\x02 \x01(\x03R\bfriendId\"\x16\n" +
	"\x14DeleteFriendResponse\"c\n" +
	"\x13UpdateRemarkRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tfriend_id\x18\x02 \x01(\x03R\bfriendId\x12\x16\n" +
	"\x06remark\x18\x03 \x01(\tR\x06remark\"\x16\n" +
	"\x14UpdateRemarkResponse\"h\n" +
	"\x15SetFriendMutedRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tfriend_id\x18\x02 \x01(\x03R\bfriendId\x12\x19\n" +
	"\bis_muted\x18\x03 \x01(\x05R\aisMuted\"\x18\n" +
	"\x16SetFriendMutedResponse\"n\n" +
	"\x17SetFriendSpecialRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tfriend_id\x18\x02 \x01(\x03R\bfriendId\x12\x1d\n" +
	"\n" +
	"is_special\x18\x03 \x01(\x05R\tisSpecial\"\x1a\n" +
	"\x18SetFriendSpecialResponse\"r\n" +
	"\x18SendFriendRequestRequest\x12!\n" +
	"\fapplicant_id\x18\x01 \x01(\x03R\vapplicantId\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\x03R\btargetId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\":\n" +
	"\x19SendFriendRequestResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x03R\trequestId\"b\n" +
	"\x1bListReceivedRequestsRequest\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\x03R\btargetId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x05R\x04size\"k\n" +
	"\x1cListReceivedRequestsResponse\x125\n" +
	"\brequests\x18\x01 \x03(\v2\x19.friend.FriendRequestItemR\brequests\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"d\n" +
	"\x17ListSentRequestsRequest\x12!\n" +
	"\fapplicant_id\x18\x01 \x01(\x03R\vapplicantId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x05R\x04size\"g\n" +
	"\x18ListSentRequestsResponse\x125\n" +
	"\brequests\x18\x01 \x03(\v2\x19.friend.FriendRequestItemR\brequests\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"S\n" +
	"\x1aHandleFriendRequestRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x03R\trequestId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\"\x1d\n" +
	"\x1bHandleFriendRequestResponse\"\xb2\x01\n" +
	"\x13AddBlacklistRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12&\n" +
	"\x0fblocked_user_id\x18\x02 \x01(\x03R\rblockedUserId\x12!\n" +
	"\fblocked_type\x18\x03 \x01(\x05R\vblockedType\x12\x16\n" +
	"\x06remark\x18\x04 \x01(\tR\x06remark\x12\x1f\n" +
	"\vexpire_time\x18\x05 \x01(\x03R\n" +
	"expireTime\"\x16\n" +
	"\x14AddBlacklistResponse\"Y\n" +
	"\x16RemoveBlacklistRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12&\n" +
	"\x0fblocked_user_id\x18\x02 \x01(\x03R\rblockedUserId\"\x19\n" +
	"\x17RemoveBlacklistResponse\"W\n" +
	"\x14ListBlacklistRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x05R\x04size\"Z\n" +
	"\x15ListBlacklistResponse\x12+\n" +
	"\x05items\x18\x01 \x03(\v2\x15.friend.BlacklistItemR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"X\n" +
	"\x15CheckBlacklistRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12&\n" +
	"\x0fblocked_user_id\x18\x02 \x01(\x03R\rblockedUserId\"7\n" +
	"\x16CheckBlacklistResponse\x12\x1d\n" +
	"\n" +
	"is_blocked\x18\x01 \x01(\bR\tisBlocked\"]\n" +
	"\x1aListRecommendationsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x05R\x04size\"e\n" +
	"\x1bListRecommendationsResponse\x120\n" +
	"\x05items\x18\x01 \x03(\v2\x1a.friend.RecommendationItemR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"F\n" +
	"\x1bIgnoreRecommendationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x03R\x02id\"\x1e\n" +
	"\x1cIgnoreRecommendationResponse2\x8a\n" +
	"\n" +
	"\rFriendService\x12F\n" +
	"\vListFriends\x12\x1a.friend.ListFriendsRequest\x1a\x1b.friend.ListFriendsResponse\x12I\n" +
	"\fDeleteFriend\x12\x1b.friend.DeleteFriendRequest\x1a\x1c.friend.DeleteFriendResponse\x12I\n" +
	"\fUpdateRemark\x12\x1b.friend.UpdateRemarkRequest\x1a\x1c.friend.UpdateRemarkResponse\x12O\n" +
	"\x0eSetFriendMuted\x12\x1d.friend.SetFriendMutedRequest\x1a\x1e.friend.SetFriendMutedResponse\x12U\n" +
	"\x10SetFriendSpecial\x12\x1f.friend.SetFriendSpecialRequest\x1a .friend.SetFriendSpecialResponse\x12X\n" +
	"\x11SendFriendRequest\x12 .friend.SendFriendRequestRequest\x1a!.friend.SendFriendRequestResponse\x12a\n" +
	"\x14ListReceivedRequests\x12#.friend.ListReceivedRequestsRequest\x1a$.friend.ListReceivedRequestsResponse\x12U\n" +
	"\x10ListSentRequests\x12\x1f.friend.ListSentRequestsRequest\x1a .friend.ListSentRequestsResponse\x12^\n" +
	"\x13HandleFriendRequest\x12\".friend.HandleFriendRequestRequest\x1a#.friend.HandleFriendRequestResponse\x12I\n" +
	"\fAddBlacklist\x12\x1b.friend.AddBlacklistRequest\x1a\x1c.friend.AddBlacklistResponse\x12R\n" +
	"\x0fRemoveBlacklist\x12\x1e.friend.RemoveBlacklistRequest\x1a\x1f.friend.RemoveBlacklistResponse\x12L\n" +
	"\rListBlacklist\x12\x1c.friend.ListBlacklistRequest\x1a\x1d.friend.ListBlacklistResponse\x12O\n" +
	"\x0eCheckBlacklist\x12\x1d.friend.CheckBlacklistRequest\x1a\x1e.friend.CheckBlacklistResponse\x12^\n" +
	"\x13ListRecommendations\x12\".friend.ListRecommendationsRequest\x1a#.friend.ListRecommendationsResponse\x12a\n" +
	"\x14IgnoreRecommendation\x12#.friend.IgnoreRecommendationRequest\x1a$.friend.IgnoreRecommendationResponseB\x14Z\x12services/friend/pbb\x06proto3"

var (
	file_beehive_m_friend_proto_rawDescOnce sync.Once
	file_beehive_m_friend_proto_rawDescData []byte
)

func file_beehive_m_friend_proto_rawDescGZIP() []byte {
	file_beehive_m_friend_proto_rawDescOnce.Do(func() {
		file_beehive_m_friend_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_beehive_m_friend_proto_rawDesc), len(file_beehive_m_friend_proto_rawDesc)))
	})
	return file_beehive_m_friend_proto_rawDescData
}

var file_beehive_m_friend_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_beehive_m_friend_proto_goTypes = []any{
	(*FriendItem)(nil),                   // 0: friend.FriendItem
	(*FriendRequestItem)(nil),            // 1: friend.FriendRequestItem
	(*BlacklistItem)(nil),                // 2: friend.BlacklistItem
	(*RecommendationItem)(nil),           // 3: friend.RecommendationItem
	(*ListFriendsRequest)(nil),           // 4: friend.ListFriendsRequest
	(*ListFriendsResponse)(nil),          // 5: friend.ListFriendsResponse
	(*DeleteFriendRequest)(nil),          // 6: friend.DeleteFriendRequest
	(*DeleteFriendResponse)(nil),         // 7: friend.DeleteFriendResponse
	(*UpdateRemarkRequest)(nil),          // 8: friend.UpdateRemarkRequest
	(*UpdateRemarkResponse)(nil),         // 9: friend.UpdateRemarkResponse
	(*SetFriendMutedRequest)(nil),        // 10: friend.SetFriendMutedRequest
	(*SetFriendMutedResponse)(nil),       // 11: friend.SetFriendMutedResponse
	(*SetFriendSpecialRequest)(nil),      // 12: friend.SetFriendSpecialRequest
	(*SetFriendSpecialResponse)(nil),     // 13: friend.SetFriendSpecialResponse
	(*SendFriendRequestRequest)(nil),     // 14: friend.SendFriendRequestRequest
	(*SendFriendRequestResponse)(nil),    // 15: friend.SendFriendRequestResponse
	(*ListReceivedRequestsRequest)(nil),  // 16: friend.ListReceivedRequestsRequest
	(*ListReceivedRequestsResponse)(nil), // 17: friend.ListReceivedRequestsResponse
	(*ListSentRequestsRequest)(nil),      // 18: friend.ListSentRequestsRequest
	(*ListSentRequestsResponse)(nil),     // 19: friend.ListSentRequestsResponse
	(*HandleFriendRequestRequest)(nil),   // 20: friend.HandleFriendRequestRequest
	(*HandleFriendRequestResponse)(nil),  // 21: friend.HandleFriendRequestResponse
	(*AddBlacklistRequest)(nil),          // 22: friend.AddBlacklistRequest
	(*AddBlacklistResponse)(nil),         // 23: friend.AddBlacklistResponse
	(*RemoveBlacklistRequest)(nil),       // 24: friend.RemoveBlacklistRequest
	(*RemoveBlacklistResponse)(nil),      // 25: friend.RemoveBlacklistResponse
	(*ListBlacklistRequest)(nil),         // 26: friend.ListBlacklistRequest
	(*ListBlacklistResponse)(nil),        // 27: friend.ListBlacklistResponse
	(*CheckBlacklistRequest)(nil),        // 28: friend.CheckBlacklistRequest
	(*CheckBlacklistResponse)(nil),       // 29: friend.CheckBlacklistResponse
	(*ListRecommendationsRequest)(nil),   // 30: friend.ListRecommendationsRequest
	(*ListRecommendationsResponse)(nil),  // 31: friend.ListRecommendationsResponse
	(*IgnoreRecommendationRequest)(nil),  // 32: friend.IgnoreRecommendationRequest
	(*IgnoreRecommendationResponse)(nil), // 33: friend.IgnoreRecommendationResponse
}
var file_beehive_m_friend_proto_depIdxs = []int32{
	0,  // 0: friend.ListFriendsResponse.friends:type_name -> friend.FriendItem
	1,  // 1: friend.ListReceivedRequestsResponse.requests:type_name -> friend.FriendRequestItem
	1,  // 2: friend.ListSentRequestsResponse.requests:type_name -> friend.FriendRequestItem
	2,  // 3: friend.ListBlacklistResponse.items:type_name -> friend.BlacklistItem
	3,  // 4: friend.ListRecommendationsResponse.items:type_name -> friend.RecommendationItem
	4,  // 5: friend.FriendService.ListFriends:input_type -> friend.ListFriendsRequest
	6,  // 6: friend.FriendService.DeleteFriend:input_type -> friend.DeleteFriendRequest
	8,  // 7: friend.FriendService.UpdateRemark:input_type -> friend.UpdateRemarkRequest
	10, // 8: friend.FriendService.SetFriendMuted:input_type -> friend.SetFriendMutedRequest
	12, // 9: friend.FriendService.SetFriendSpecial:input_type -> friend.SetFriendSpecialRequest
	14, // 10: friend.FriendService.SendFriendRequest:input_type -> friend.SendFriendRequestRequest
	16, // 11: friend.FriendService.ListReceivedRequests:input_type -> friend.ListReceivedRequestsRequest
	18, // 12: friend.FriendService.ListSentRequests:input_type -> friend.ListSentRequestsRequest
	20, // 13: friend.FriendService.HandleFriendRequest:input_type -> friend.HandleFriendRequestRequest
	22, // 14: friend.FriendService.AddBlacklist:input_type -> friend.AddBlacklistRequest
	24, // 15: friend.FriendService.RemoveBlacklist:input_type -> friend.RemoveBlacklistRequest
	26, // 16: friend.FriendService.ListBlacklist:input_type -> friend.ListBlacklistRequest
	28, // 17: friend.FriendService.CheckBlacklist:input_type -> friend.CheckBlacklistRequest
	30, // 18: friend.FriendService.ListRecommendations:input_type -> friend.ListRecommendationsRequest
	32, // 19: friend.FriendService.IgnoreRecommendation:input_type -> friend.IgnoreRecommendationRequest
	5,  // 20: friend.FriendService.ListFriends:output_type -> friend.ListFriendsResponse
	7,  // 21: friend.FriendService.DeleteFriend:output_type -> friend.DeleteFriendResponse
	9,  // 22: friend.FriendService.UpdateRemark:output_type -> friend.UpdateRemarkResponse
	11, // 23: friend.FriendService.SetFriendMuted:output_type -> friend.SetFriendMutedResponse
	13, // 24: friend.FriendService.SetFriendSpecial:output_type -> friend.SetFriendSpecialResponse
	15, // 25: friend.FriendService.SendFriendRequest:output_type -> friend.SendFriendRequestResponse
	17, // 26: friend.FriendService.ListReceivedRequests:output_type -> friend.ListReceivedRequestsResponse
	19, // 27: friend.FriendService.ListSentRequests:output_type -> friend.ListSentRequestsResponse
	21, // 28: friend.FriendService.HandleFriendRequest:output_type -> friend.HandleFriendRequestResponse
	23, // 29: friend.FriendService.AddBlacklist:output_type -> friend.AddBlacklistResponse
	25, // 30: friend.FriendService.RemoveBlacklist:output_type -> friend.RemoveBlacklistResponse
	27, // 31: friend.FriendService.ListBlacklist:output_type -> friend.ListBlacklistResponse
	29, // 32: friend.FriendService.CheckBlacklist:output_type -> friend.CheckBlacklistResponse
	31, // 33: friend.FriendService.ListRecommendations:output_type -> friend.ListRecommendationsResponse
	33, // 34: friend.FriendService.IgnoreRecommendation:output_type -> friend.IgnoreRecommendationResponse
	20, // [20:35] is the sub-list for method output_type
	5,  // [5:20] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_beehive_m_friend_proto_init() }
func file_beehive_m_friend_proto_init() {
	if File_beehive_m_friend_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_beehive_m_friend_proto_rawDesc), len(file_beehive_m_friend_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_beehive_m_friend_proto_goTypes,
		DependencyIndexes: file_beehive_m_friend_proto_depIdxs,
		MessageInfos:      file_beehive_m_friend_proto_msgTypes,
	}.Build()
	File_beehive_m_friend_proto = out.File
	file_beehive_m_friend_proto_goTypes = nil
	file_beehive_m_friend_proto_depIdxs = nil
}
