// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: message.proto

package messageservice

import (
	"context"

	"github.com/HappyLadySauce/Beehive-M/services/message/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Conversation                    = pb.Conversation
	GetGroupUnreadCountRequest      = pb.GetGroupUnreadCountRequest
	GetGroupUnreadCountResponse     = pb.GetGroupUnreadCountResponse
	GetMessageRequest               = pb.GetMessageRequest
	GetMessageResponse              = pb.GetMessageResponse
	GetOrCreateConversationRequest  = pb.GetOrCreateConversationRequest
	GetOrCreateConversationResponse = pb.GetOrCreateConversationResponse
	GetPrivateUnreadCountRequest    = pb.GetPrivateUnreadCountRequest
	GetPrivateUnreadCountResponse   = pb.GetPrivateUnreadCountResponse
	GetSyncCursorRequest            = pb.GetSyncCursorRequest
	GetSyncCursorResponse           = pb.GetSyncCursorResponse
	ListConversationsRequest        = pb.ListConversationsRequest
	ListConversationsResponse       = pb.ListConversationsResponse
	ListGroupMessagesRequest        = pb.ListGroupMessagesRequest
	ListGroupMessagesResponse       = pb.ListGroupMessagesResponse
	ListMessageReferencesRequest    = pb.ListMessageReferencesRequest
	ListMessageReferencesResponse   = pb.ListMessageReferencesResponse
	ListPrivateMessagesRequest      = pb.ListPrivateMessagesRequest
	ListPrivateMessagesResponse     = pb.ListPrivateMessagesResponse
	MarkGroupReadRequest            = pb.MarkGroupReadRequest
	MarkGroupReadResponse           = pb.MarkGroupReadResponse
	MarkPrivateReadRequest          = pb.MarkPrivateReadRequest
	MarkPrivateReadResponse         = pb.MarkPrivateReadResponse
	Message                         = pb.Message
	MessageReference                = pb.MessageReference
	PullMessagesRequest             = pb.PullMessagesRequest
	PullMessagesResponse            = pb.PullMessagesResponse
	RecallMessageRequest            = pb.RecallMessageRequest
	RecallMessageResponse           = pb.RecallMessageResponse
	SendGroupMessageRequest         = pb.SendGroupMessageRequest
	SendGroupMessageResponse        = pb.SendGroupMessageResponse
	SendPrivateMessageRequest       = pb.SendPrivateMessageRequest
	SendPrivateMessageResponse      = pb.SendPrivateMessageResponse
	SetConversationMuteRequest      = pb.SetConversationMuteRequest
	SetConversationMuteResponse     = pb.SetConversationMuteResponse
	SetConversationPinRequest       = pb.SetConversationPinRequest
	SetConversationPinResponse      = pb.SetConversationPinResponse

	MessageService interface {
		// 私聊
		SendPrivateMessage(ctx context.Context, in *SendPrivateMessageRequest, opts ...grpc.CallOption) (*SendPrivateMessageResponse, error)
		ListPrivateMessages(ctx context.Context, in *ListPrivateMessagesRequest, opts ...grpc.CallOption) (*ListPrivateMessagesResponse, error)
		MarkPrivateRead(ctx context.Context, in *MarkPrivateReadRequest, opts ...grpc.CallOption) (*MarkPrivateReadResponse, error)
		GetPrivateUnreadCount(ctx context.Context, in *GetPrivateUnreadCountRequest, opts ...grpc.CallOption) (*GetPrivateUnreadCountResponse, error)
		// 群聊
		SendGroupMessage(ctx context.Context, in *SendGroupMessageRequest, opts ...grpc.CallOption) (*SendGroupMessageResponse, error)
		ListGroupMessages(ctx context.Context, in *ListGroupMessagesRequest, opts ...grpc.CallOption) (*ListGroupMessagesResponse, error)
		MarkGroupRead(ctx context.Context, in *MarkGroupReadRequest, opts ...grpc.CallOption) (*MarkGroupReadResponse, error)
		GetGroupUnreadCount(ctx context.Context, in *GetGroupUnreadCountRequest, opts ...grpc.CallOption) (*GetGroupUnreadCountResponse, error)
		// 通用
		RecallMessage(ctx context.Context, in *RecallMessageRequest, opts ...grpc.CallOption) (*RecallMessageResponse, error)
		GetMessage(ctx context.Context, in *GetMessageRequest, opts ...grpc.CallOption) (*GetMessageResponse, error)
		ListMessageReferences(ctx context.Context, in *ListMessageReferencesRequest, opts ...grpc.CallOption) (*ListMessageReferencesResponse, error)
		// 会话
		ListConversations(ctx context.Context, in *ListConversationsRequest, opts ...grpc.CallOption) (*ListConversationsResponse, error)
		SetConversationPin(ctx context.Context, in *SetConversationPinRequest, opts ...grpc.CallOption) (*SetConversationPinResponse, error)
		SetConversationMute(ctx context.Context, in *SetConversationMuteRequest, opts ...grpc.CallOption) (*SetConversationMuteResponse, error)
		GetOrCreateConversation(ctx context.Context, in *GetOrCreateConversationRequest, opts ...grpc.CallOption) (*GetOrCreateConversationResponse, error)
		// 同步
		GetSyncCursor(ctx context.Context, in *GetSyncCursorRequest, opts ...grpc.CallOption) (*GetSyncCursorResponse, error)
		PullMessages(ctx context.Context, in *PullMessagesRequest, opts ...grpc.CallOption) (*PullMessagesResponse, error)
	}

	defaultMessageService struct {
		cli zrpc.Client
	}
)

func NewMessageService(cli zrpc.Client) MessageService {
	return &defaultMessageService{
		cli: cli,
	}
}

// 私聊
func (m *defaultMessageService) SendPrivateMessage(ctx context.Context, in *SendPrivateMessageRequest, opts ...grpc.CallOption) (*SendPrivateMessageResponse, error) {
	client := pb.NewMessageServiceClient(m.cli.Conn())
	return client.SendPrivateMessage(ctx, in, opts...)
}

func (m *defaultMessageService) ListPrivateMessages(ctx context.Context, in *ListPrivateMessagesRequest, opts ...grpc.CallOption) (*ListPrivateMessagesResponse, error) {
	client := pb.NewMessageServiceClient(m.cli.Conn())
	return client.ListPrivateMessages(ctx, in, opts...)
}

func (m *defaultMessageService) MarkPrivateRead(ctx context.Context, in *MarkPrivateReadRequest, opts ...grpc.CallOption) (*MarkPrivateReadResponse, error) {
	client := pb.NewMessageServiceClient(m.cli.Conn())
	return client.MarkPrivateRead(ctx, in, opts...)
}

func (m *defaultMessageService) GetPrivateUnreadCount(ctx context.Context, in *GetPrivateUnreadCountRequest, opts ...grpc.CallOption) (*GetPrivateUnreadCountResponse, error) {
	client := pb.NewMessageServiceClient(m.cli.Conn())
	return client.GetPrivateUnreadCount(ctx, in, opts...)
}

// 群聊
func (m *defaultMessageService) SendGroupMessage(ctx context.Context, in *SendGroupMessageRequest, opts ...grpc.CallOption) (*SendGroupMessageResponse, error) {
	client := pb.NewMessageServiceClient(m.cli.Conn())
	return client.SendGroupMessage(ctx, in, opts...)
}

func (m *defaultMessageService) ListGroupMessages(ctx context.Context, in *ListGroupMessagesRequest, opts ...grpc.CallOption) (*ListGroupMessagesResponse, error) {
	client := pb.NewMessageServiceClient(m.cli.Conn())
	return client.ListGroupMessages(ctx, in, opts...)
}

func (m *defaultMessageService) MarkGroupRead(ctx context.Context, in *MarkGroupReadRequest, opts ...grpc.CallOption) (*MarkGroupReadResponse, error) {
	client := pb.NewMessageServiceClient(m.cli.Conn())
	return client.MarkGroupRead(ctx, in, opts...)
}

func (m *defaultMessageService) GetGroupUnreadCount(ctx context.Context, in *GetGroupUnreadCountRequest, opts ...grpc.CallOption) (*GetGroupUnreadCountResponse, error) {
	client := pb.NewMessageServiceClient(m.cli.Conn())
	return client.GetGroupUnreadCount(ctx, in, opts...)
}

// 通用
func (m *defaultMessageService) RecallMessage(ctx context.Context, in *RecallMessageRequest, opts ...grpc.CallOption) (*RecallMessageResponse, error) {
	client := pb.NewMessageServiceClient(m.cli.Conn())
	return client.RecallMessage(ctx, in, opts...)
}

func (m *defaultMessageService) GetMessage(ctx context.Context, in *GetMessageRequest, opts ...grpc.CallOption) (*GetMessageResponse, error) {
	client := pb.NewMessageServiceClient(m.cli.Conn())
	return client.GetMessage(ctx, in, opts...)
}

func (m *defaultMessageService) ListMessageReferences(ctx context.Context, in *ListMessageReferencesRequest, opts ...grpc.CallOption) (*ListMessageReferencesResponse, error) {
	client := pb.NewMessageServiceClient(m.cli.Conn())
	return client.ListMessageReferences(ctx, in, opts...)
}

// 会话
func (m *defaultMessageService) ListConversations(ctx context.Context, in *ListConversationsRequest, opts ...grpc.CallOption) (*ListConversationsResponse, error) {
	client := pb.NewMessageServiceClient(m.cli.Conn())
	return client.ListConversations(ctx, in, opts...)
}

func (m *defaultMessageService) SetConversationPin(ctx context.Context, in *SetConversationPinRequest, opts ...grpc.CallOption) (*SetConversationPinResponse, error) {
	client := pb.NewMessageServiceClient(m.cli.Conn())
	return client.SetConversationPin(ctx, in, opts...)
}

func (m *defaultMessageService) SetConversationMute(ctx context.Context, in *SetConversationMuteRequest, opts ...grpc.CallOption) (*SetConversationMuteResponse, error) {
	client := pb.NewMessageServiceClient(m.cli.Conn())
	return client.SetConversationMute(ctx, in, opts...)
}

func (m *defaultMessageService) GetOrCreateConversation(ctx context.Context, in *GetOrCreateConversationRequest, opts ...grpc.CallOption) (*GetOrCreateConversationResponse, error) {
	client := pb.NewMessageServiceClient(m.cli.Conn())
	return client.GetOrCreateConversation(ctx, in, opts...)
}

// 同步
func (m *defaultMessageService) GetSyncCursor(ctx context.Context, in *GetSyncCursorRequest, opts ...grpc.CallOption) (*GetSyncCursorResponse, error) {
	client := pb.NewMessageServiceClient(m.cli.Conn())
	return client.GetSyncCursor(ctx, in, opts...)
}

func (m *defaultMessageService) PullMessages(ctx context.Context, in *PullMessagesRequest, opts ...grpc.CallOption) (*PullMessagesResponse, error) {
	client := pb.NewMessageServiceClient(m.cli.Conn())
	return client.PullMessages(ctx, in, opts...)
}
