// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: beehive-m-user.proto

package server

import (
	"context"

	"github.com/HappyLadySauce/Beehive-M/services/user/internal/logic/userservice"
	"github.com/HappyLadySauce/Beehive-M/services/user/internal/svc"
	"github.com/HappyLadySauce/Beehive-M/services/user/pb"
)

type UserServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedUserServiceServer
}

func NewUserServiceServer(svcCtx *svc.ServiceContext) *UserServiceServer {
	return &UserServiceServer{
		svcCtx: svcCtx,
	}
}

// 按 user_id 查单个用户（会话头、资料页等）
func (s *UserServiceServer) GetUser(ctx context.Context, in *pb.GetUserRequest) (*pb.GetUserResponse, error) {
	l := userservicelogic.NewGetUserLogic(ctx, s.svcCtx)
	return l.GetUser(in)
}

// 批量按 user_id 查（会话列表、群成员列表等）
func (s *UserServiceServer) GetUserBatch(ctx context.Context, in *pb.GetUserBatchRequest) (*pb.GetUserBatchResponse, error) {
	l := userservicelogic.NewGetUserBatchLogic(ctx, s.svcCtx)
	return l.GetUserBatch(in)
}

// 按账号查（登录、搜索用）
func (s *UserServiceServer) GetUserByAccount(ctx context.Context, in *pb.GetUserByAccountRequest) (*pb.GetUserByAccountResponse, error) {
	l := userservicelogic.NewGetUserByAccountLogic(ctx, s.svcCtx)
	return l.GetUserByAccount(in)
}

// 关键词搜索用户（全文检索），分页
func (s *UserServiceServer) SearchUsers(ctx context.Context, in *pb.SearchUsersRequest) (*pb.SearchUsersResponse, error) {
	l := userservicelogic.NewSearchUsersLogic(ctx, s.svcCtx)
	return l.SearchUsers(in)
}

// 更新当前用户资料（昵称、头像、签名等）
func (s *UserServiceServer) UpdateProfile(ctx context.Context, in *pb.UpdateProfileRequest) (*pb.UpdateProfileResponse, error) {
	l := userservicelogic.NewUpdateProfileLogic(ctx, s.svcCtx)
	return l.UpdateProfile(in)
}

// 仅内部使用：按 user_id 查用户（含 password_hash），供 auth 登录校验
func (s *UserServiceServer) GetUserForAuth(ctx context.Context, in *pb.GetUserForAuthRequest) (*pb.UserForAuth, error) {
	l := userservicelogic.NewGetUserForAuthLogic(ctx, s.svcCtx)
	return l.GetUserForAuth(in)
}
