// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: beehive-m-resource.proto

package server

import (
	"context"

	"github.com/HappyLadySauce/Beehive-M/services/resource/internal/logic/resourceservice"
	"github.com/HappyLadySauce/Beehive-M/services/resource/internal/svc"
	"github.com/HappyLadySauce/Beehive-M/services/resource/pb"
)

type ResourceServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedResourceServiceServer
}

func NewResourceServiceServer(svcCtx *svc.ServiceContext) *ResourceServiceServer {
	return &ResourceServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *ResourceServiceServer) Upload(ctx context.Context, in *pb.UploadRequest) (*pb.UploadResponse, error) {
	l := resourceservicelogic.NewUploadLogic(ctx, s.svcCtx)
	return l.Upload(in)
}

func (s *ResourceServiceServer) GetResource(ctx context.Context, in *pb.GetResourceRequest) (*pb.GetResourceResponse, error) {
	l := resourceservicelogic.NewGetResourceLogic(ctx, s.svcCtx)
	return l.GetResource(in)
}

func (s *ResourceServiceServer) DeleteResource(ctx context.Context, in *pb.DeleteResourceRequest) (*pb.DeleteResourceResponse, error) {
	l := resourceservicelogic.NewDeleteResourceLogic(ctx, s.svcCtx)
	return l.DeleteResource(in)
}

func (s *ResourceServiceServer) GetByHash(ctx context.Context, in *pb.GetByHashRequest) (*pb.GetByHashResponse, error) {
	l := resourceservicelogic.NewGetByHashLogic(ctx, s.svcCtx)
	return l.GetByHash(in)
}

func (s *ResourceServiceServer) CleanExpiredTemp(ctx context.Context, in *pb.CleanExpiredTempRequest) (*pb.CleanExpiredTempResponse, error) {
	l := resourceservicelogic.NewCleanExpiredTempLogic(ctx, s.svcCtx)
	return l.CleanExpiredTemp(in)
}
