// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: beehive-m-presence.proto

package presenceservice

import (
	"context"

	"github.com/HappyLadySauce/Beehive-M/services/presence/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BatchGetOnlineStatusRequest  = pb.BatchGetOnlineStatusRequest
	BatchGetOnlineStatusResponse = pb.BatchGetOnlineStatusResponse
	GetOnlineStatusRequest       = pb.GetOnlineStatusRequest
	GetOnlineStatusResponse      = pb.GetOnlineStatusResponse
	KickDeviceRequest            = pb.KickDeviceRequest
	KickDeviceResponse           = pb.KickDeviceResponse
	OnlineStatus                 = pb.OnlineStatus
	ReportHeartbeatRequest       = pb.ReportHeartbeatRequest
	ReportHeartbeatResponse      = pb.ReportHeartbeatResponse

	PresenceService interface {
		ReportHeartbeat(ctx context.Context, in *ReportHeartbeatRequest, opts ...grpc.CallOption) (*ReportHeartbeatResponse, error)
		GetOnlineStatus(ctx context.Context, in *GetOnlineStatusRequest, opts ...grpc.CallOption) (*GetOnlineStatusResponse, error)
		BatchGetOnlineStatus(ctx context.Context, in *BatchGetOnlineStatusRequest, opts ...grpc.CallOption) (*BatchGetOnlineStatusResponse, error)
		KickDevice(ctx context.Context, in *KickDeviceRequest, opts ...grpc.CallOption) (*KickDeviceResponse, error)
	}

	defaultPresenceService struct {
		cli zrpc.Client
	}
)

func NewPresenceService(cli zrpc.Client) PresenceService {
	return &defaultPresenceService{
		cli: cli,
	}
}

func (m *defaultPresenceService) ReportHeartbeat(ctx context.Context, in *ReportHeartbeatRequest, opts ...grpc.CallOption) (*ReportHeartbeatResponse, error) {
	client := pb.NewPresenceServiceClient(m.cli.Conn())
	return client.ReportHeartbeat(ctx, in, opts...)
}

func (m *defaultPresenceService) GetOnlineStatus(ctx context.Context, in *GetOnlineStatusRequest, opts ...grpc.CallOption) (*GetOnlineStatusResponse, error) {
	client := pb.NewPresenceServiceClient(m.cli.Conn())
	return client.GetOnlineStatus(ctx, in, opts...)
}

func (m *defaultPresenceService) BatchGetOnlineStatus(ctx context.Context, in *BatchGetOnlineStatusRequest, opts ...grpc.CallOption) (*BatchGetOnlineStatusResponse, error) {
	client := pb.NewPresenceServiceClient(m.cli.Conn())
	return client.BatchGetOnlineStatus(ctx, in, opts...)
}

func (m *defaultPresenceService) KickDevice(ctx context.Context, in *KickDeviceRequest, opts ...grpc.CallOption) (*KickDeviceResponse, error) {
	client := pb.NewPresenceServiceClient(m.cli.Conn())
	return client.KickDevice(ctx, in, opts...)
}
