// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: beehive-m-notify.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Notification struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId int64                  `protobuf:"varint,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	UserId         int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type           int32                  `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"` // 1好友申请 2群申请 3入群邀请 4系统公告
	Title          string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Content        string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	RelatedId      int64                  `protobuf:"varint,6,opt,name=related_id,json=relatedId,proto3" json:"related_id,omitempty"` // 申请ID/群ID等
	IsRead         int32                  `protobuf:"varint,7,opt,name=is_read,json=isRead,proto3" json:"is_read,omitempty"`          // 0未读 1已读
	ExtraData      string                 `protobuf:"bytes,8,opt,name=extra_data,json=extraData,proto3" json:"extra_data,omitempty"`  // JSON
	CreateTime     int64                  `protobuf:"varint,9,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	ReadTime       int64                  `protobuf:"varint,10,opt,name=read_time,json=readTime,proto3" json:"read_time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_beehive_m_notify_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_notify_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_beehive_m_notify_proto_rawDescGZIP(), []int{0}
}

func (x *Notification) GetNotificationId() int64 {
	if x != nil {
		return x.NotificationId
	}
	return 0
}

func (x *Notification) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Notification) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Notification) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Notification) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Notification) GetRelatedId() int64 {
	if x != nil {
		return x.RelatedId
	}
	return 0
}

func (x *Notification) GetIsRead() int32 {
	if x != nil {
		return x.IsRead
	}
	return 0
}

func (x *Notification) GetExtraData() string {
	if x != nil {
		return x.ExtraData
	}
	return ""
}

func (x *Notification) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *Notification) GetReadTime() int64 {
	if x != nil {
		return x.ReadTime
	}
	return 0
}

type ListNotificationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type          int32                  `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`                   // 可选，0 表示全部
	IsRead        int32                  `protobuf:"varint,3,opt,name=is_read,json=isRead,proto3" json:"is_read,omitempty"` // 可选，-1 表示全部 0未读 1已读
	Page          int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotificationsRequest) Reset() {
	*x = ListNotificationsRequest{}
	mi := &file_beehive_m_notify_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotificationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotificationsRequest) ProtoMessage() {}

func (x *ListNotificationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_notify_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotificationsRequest.ProtoReflect.Descriptor instead.
func (*ListNotificationsRequest) Descriptor() ([]byte, []int) {
	return file_beehive_m_notify_proto_rawDescGZIP(), []int{1}
}

func (x *ListNotificationsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListNotificationsRequest) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ListNotificationsRequest) GetIsRead() int32 {
	if x != nil {
		return x.IsRead
	}
	return 0
}

func (x *ListNotificationsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListNotificationsRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListNotificationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notifications []*Notification        `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotificationsResponse) Reset() {
	*x = ListNotificationsResponse{}
	mi := &file_beehive_m_notify_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotificationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotificationsResponse) ProtoMessage() {}

func (x *ListNotificationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_notify_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotificationsResponse.ProtoReflect.Descriptor instead.
func (*ListNotificationsResponse) Descriptor() ([]byte, []int) {
	return file_beehive_m_notify_proto_rawDescGZIP(), []int{2}
}

func (x *ListNotificationsResponse) GetNotifications() []*Notification {
	if x != nil {
		return x.Notifications
	}
	return nil
}

func (x *ListNotificationsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type MarkReadRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId int64                  `protobuf:"varint,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MarkReadRequest) Reset() {
	*x = MarkReadRequest{}
	mi := &file_beehive_m_notify_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkReadRequest) ProtoMessage() {}

func (x *MarkReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_notify_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkReadRequest.ProtoReflect.Descriptor instead.
func (*MarkReadRequest) Descriptor() ([]byte, []int) {
	return file_beehive_m_notify_proto_rawDescGZIP(), []int{3}
}

func (x *MarkReadRequest) GetNotificationId() int64 {
	if x != nil {
		return x.NotificationId
	}
	return 0
}

type MarkReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkReadResponse) Reset() {
	*x = MarkReadResponse{}
	mi := &file_beehive_m_notify_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkReadResponse) ProtoMessage() {}

func (x *MarkReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_notify_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkReadResponse.ProtoReflect.Descriptor instead.
func (*MarkReadResponse) Descriptor() ([]byte, []int) {
	return file_beehive_m_notify_proto_rawDescGZIP(), []int{4}
}

type MarkAllReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type          int32                  `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"` // 可选，0 表示全部类型
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkAllReadRequest) Reset() {
	*x = MarkAllReadRequest{}
	mi := &file_beehive_m_notify_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAllReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAllReadRequest) ProtoMessage() {}

func (x *MarkAllReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_notify_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAllReadRequest.ProtoReflect.Descriptor instead.
func (*MarkAllReadRequest) Descriptor() ([]byte, []int) {
	return file_beehive_m_notify_proto_rawDescGZIP(), []int{5}
}

func (x *MarkAllReadRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MarkAllReadRequest) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

type MarkAllReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkAllReadResponse) Reset() {
	*x = MarkAllReadResponse{}
	mi := &file_beehive_m_notify_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAllReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAllReadResponse) ProtoMessage() {}

func (x *MarkAllReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_notify_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAllReadResponse.ProtoReflect.Descriptor instead.
func (*MarkAllReadResponse) Descriptor() ([]byte, []int) {
	return file_beehive_m_notify_proto_rawDescGZIP(), []int{6}
}

type GetUnreadCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type          int32                  `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"` // 可选，0 表示全部
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUnreadCountRequest) Reset() {
	*x = GetUnreadCountRequest{}
	mi := &file_beehive_m_notify_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnreadCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnreadCountRequest) ProtoMessage() {}

func (x *GetUnreadCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_notify_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnreadCountRequest.ProtoReflect.Descriptor instead.
func (*GetUnreadCountRequest) Descriptor() ([]byte, []int) {
	return file_beehive_m_notify_proto_rawDescGZIP(), []int{7}
}

func (x *GetUnreadCountRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetUnreadCountRequest) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

type GetUnreadCountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUnreadCountResponse) Reset() {
	*x = GetUnreadCountResponse{}
	mi := &file_beehive_m_notify_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnreadCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnreadCountResponse) ProtoMessage() {}

func (x *GetUnreadCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_notify_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnreadCountResponse.ProtoReflect.Descriptor instead.
func (*GetUnreadCountResponse) Descriptor() ([]byte, []int) {
	return file_beehive_m_notify_proto_rawDescGZIP(), []int{8}
}

func (x *GetUnreadCountResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type NotifyFriendRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      int64                  `protobuf:"varint,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"` // 接收人
	ApplicantId   int64                  `protobuf:"varint,2,opt,name=applicant_id,json=applicantId,proto3" json:"applicant_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	RequestId     int64                  `protobuf:"varint,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyFriendRequestRequest) Reset() {
	*x = NotifyFriendRequestRequest{}
	mi := &file_beehive_m_notify_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyFriendRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyFriendRequestRequest) ProtoMessage() {}

func (x *NotifyFriendRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_notify_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyFriendRequestRequest.ProtoReflect.Descriptor instead.
func (*NotifyFriendRequestRequest) Descriptor() ([]byte, []int) {
	return file_beehive_m_notify_proto_rawDescGZIP(), []int{9}
}

func (x *NotifyFriendRequestRequest) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *NotifyFriendRequestRequest) GetApplicantId() int64 {
	if x != nil {
		return x.ApplicantId
	}
	return 0
}

func (x *NotifyFriendRequestRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *NotifyFriendRequestRequest) GetRequestId() int64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

type NotifyFriendRequestResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId int64                  `protobuf:"varint,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NotifyFriendRequestResponse) Reset() {
	*x = NotifyFriendRequestResponse{}
	mi := &file_beehive_m_notify_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyFriendRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyFriendRequestResponse) ProtoMessage() {}

func (x *NotifyFriendRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_notify_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyFriendRequestResponse.ProtoReflect.Descriptor instead.
func (*NotifyFriendRequestResponse) Descriptor() ([]byte, []int) {
	return file_beehive_m_notify_proto_rawDescGZIP(), []int{10}
}

func (x *NotifyFriendRequestResponse) GetNotificationId() int64 {
	if x != nil {
		return x.NotificationId
	}
	return 0
}

type NotifyGroupRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 接收人（群主/管理员）
	ApplicantId   int64                  `protobuf:"varint,2,opt,name=applicant_id,json=applicantId,proto3" json:"applicant_id,omitempty"`
	GroupId       int64                  `protobuf:"varint,3,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	RequestId     int64                  `protobuf:"varint,5,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyGroupRequestRequest) Reset() {
	*x = NotifyGroupRequestRequest{}
	mi := &file_beehive_m_notify_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyGroupRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyGroupRequestRequest) ProtoMessage() {}

func (x *NotifyGroupRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_notify_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyGroupRequestRequest.ProtoReflect.Descriptor instead.
func (*NotifyGroupRequestRequest) Descriptor() ([]byte, []int) {
	return file_beehive_m_notify_proto_rawDescGZIP(), []int{11}
}

func (x *NotifyGroupRequestRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *NotifyGroupRequestRequest) GetApplicantId() int64 {
	if x != nil {
		return x.ApplicantId
	}
	return 0
}

func (x *NotifyGroupRequestRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *NotifyGroupRequestRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *NotifyGroupRequestRequest) GetRequestId() int64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

type NotifyGroupRequestResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId int64                  `protobuf:"varint,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NotifyGroupRequestResponse) Reset() {
	*x = NotifyGroupRequestResponse{}
	mi := &file_beehive_m_notify_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyGroupRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyGroupRequestResponse) ProtoMessage() {}

func (x *NotifyGroupRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_notify_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyGroupRequestResponse.ProtoReflect.Descriptor instead.
func (*NotifyGroupRequestResponse) Descriptor() ([]byte, []int) {
	return file_beehive_m_notify_proto_rawDescGZIP(), []int{12}
}

func (x *NotifyGroupRequestResponse) GetNotificationId() int64 {
	if x != nil {
		return x.NotificationId
	}
	return 0
}

type NotifyInviteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InviteeId     int64                  `protobuf:"varint,1,opt,name=invitee_id,json=inviteeId,proto3" json:"invitee_id,omitempty"`
	InviterId     int64                  `protobuf:"varint,2,opt,name=inviter_id,json=inviterId,proto3" json:"inviter_id,omitempty"`
	GroupId       int64                  `protobuf:"varint,3,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	InvitationId  int64                  `protobuf:"varint,4,opt,name=invitation_id,json=invitationId,proto3" json:"invitation_id,omitempty"`
	Title         string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyInviteRequest) Reset() {
	*x = NotifyInviteRequest{}
	mi := &file_beehive_m_notify_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyInviteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyInviteRequest) ProtoMessage() {}

func (x *NotifyInviteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_notify_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyInviteRequest.ProtoReflect.Descriptor instead.
func (*NotifyInviteRequest) Descriptor() ([]byte, []int) {
	return file_beehive_m_notify_proto_rawDescGZIP(), []int{13}
}

func (x *NotifyInviteRequest) GetInviteeId() int64 {
	if x != nil {
		return x.InviteeId
	}
	return 0
}

func (x *NotifyInviteRequest) GetInviterId() int64 {
	if x != nil {
		return x.InviterId
	}
	return 0
}

func (x *NotifyInviteRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *NotifyInviteRequest) GetInvitationId() int64 {
	if x != nil {
		return x.InvitationId
	}
	return 0
}

func (x *NotifyInviteRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NotifyInviteRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type NotifyInviteResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId int64                  `protobuf:"varint,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NotifyInviteResponse) Reset() {
	*x = NotifyInviteResponse{}
	mi := &file_beehive_m_notify_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyInviteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyInviteResponse) ProtoMessage() {}

func (x *NotifyInviteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_notify_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyInviteResponse.ProtoReflect.Descriptor instead.
func (*NotifyInviteResponse) Descriptor() ([]byte, []int) {
	return file_beehive_m_notify_proto_rawDescGZIP(), []int{14}
}

func (x *NotifyInviteResponse) GetNotificationId() int64 {
	if x != nil {
		return x.NotificationId
	}
	return 0
}

type NotifySystemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	RelatedId     int64                  `protobuf:"varint,4,opt,name=related_id,json=relatedId,proto3" json:"related_id,omitempty"`
	ExtraData     string                 `protobuf:"bytes,5,opt,name=extra_data,json=extraData,proto3" json:"extra_data,omitempty"` // JSON
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifySystemRequest) Reset() {
	*x = NotifySystemRequest{}
	mi := &file_beehive_m_notify_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifySystemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifySystemRequest) ProtoMessage() {}

func (x *NotifySystemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_notify_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifySystemRequest.ProtoReflect.Descriptor instead.
func (*NotifySystemRequest) Descriptor() ([]byte, []int) {
	return file_beehive_m_notify_proto_rawDescGZIP(), []int{15}
}

func (x *NotifySystemRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *NotifySystemRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NotifySystemRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *NotifySystemRequest) GetRelatedId() int64 {
	if x != nil {
		return x.RelatedId
	}
	return 0
}

func (x *NotifySystemRequest) GetExtraData() string {
	if x != nil {
		return x.ExtraData
	}
	return ""
}

type NotifySystemResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId int64                  `protobuf:"varint,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NotifySystemResponse) Reset() {
	*x = NotifySystemResponse{}
	mi := &file_beehive_m_notify_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifySystemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifySystemResponse) ProtoMessage() {}

func (x *NotifySystemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_notify_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifySystemResponse.ProtoReflect.Descriptor instead.
func (*NotifySystemResponse) Descriptor() ([]byte, []int) {
	return file_beehive_m_notify_proto_rawDescGZIP(), []int{16}
}

func (x *NotifySystemResponse) GetNotificationId() int64 {
	if x != nil {
		return x.NotificationId
	}
	return 0
}

var File_beehive_m_notify_proto protoreflect.FileDescriptor

const file_beehive_m_notify_proto_rawDesc = "" +
	"\n" +
	"\x16beehive-m-notify.proto\x12\x06notify\"\xa9\x02\n" +
	"\fNotification\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\x03R\x0enotificationId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\x05R\x04type\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"related_id\x18\x06 \x01(\x03R\trelatedId\x12\x17\n" +
	"\ais_read\x18\a \x01(\x05R\x06isRead\x12\x1d\n" +
	"\n" +
	"extra_data\x18\b \x01(\tR\textraData\x12\x1f\n" +
	"\vcreate_time\x18\t \x01(\x03R\n" +
	"createTime\x12\x1b\n" +
	"\tread_time\x18\n" +
	" \x01(\x03R\breadTime\"\x88\x01\n" +
	"\x18ListNotificationsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\x05R\x04type\x12\x17\n" +
	"\ais_read\x18\x03 \x01(\x05R\x06isRead\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x05 \x01(\x05R\x04size\"m\n" +
	"\x19ListNotificationsResponse\x12:\n" +
	"\rnotifications\x18\x01 \x03(\v2\x14.notify.NotificationR\rnotifications\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\":\n" +
	"\x0fMarkReadRequest\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\x03R\x0enotificationId\"\x12\n" +
	"\x10MarkReadResponse\"A\n" +
	"\x12MarkAllReadRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\x05R\x04type\"\x15\n" +
	"\x13MarkAllReadResponse\"D\n" +
	"\x15GetUnreadCountRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\x05R\x04type\".\n" +
	"\x16GetUnreadCountResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\"\x93\x01\n" +
	"\x1aNotifyFriendRequestRequest\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\x03R\btargetId\x12!\n" +
	"\fapplicant_id\x18\x02 \x01(\x03R\vapplicantId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\x03R\trequestId\"F\n" +
	"\x1bNotifyFriendRequestResponse\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\x03R\x0enotificationId\"\xa9\x01\n" +
	"\x19NotifyGroupRequestRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12!\n" +
	"\fapplicant_id\x18\x02 \x01(\x03R\vapplicantId\x12\x19\n" +
	"\bgroup_id\x18\x03 \x01(\x03R\agroupId\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12\x1d\n" +
	"\n" +
	"request_id\x18\x05 \x01(\x03R\trequestId\"E\n" +
	"\x1aNotifyGroupRequestResponse\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\x03R\x0enotificationId\"\xc3\x01\n" +
	"\x13NotifyInviteRequest\x12\x1d\n" +
	"\n" +
	"invitee_id\x18\x01 \x01(\x03R\tinviteeId\x12\x1d\n" +
	"\n" +
	"inviter_id\x18\x02 \x01(\x03R\tinviterId\x12\x19\n" +
	"\bgroup_id\x18\x03 \x01(\x03R\agroupId\x12#\n" +
	"\rinvitation_id\x18\x04 \x01(\x03R\finvitationId\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\"?\n" +
	"\x14NotifyInviteResponse\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\x03R\x0enotificationId\"\x9c\x01\n" +
	"\x13NotifySystemRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"related_id\x18\x04 \x01(\x03R\trelatedId\x12\x1d\n" +
	"\n" +
	"extra_data\x18\x05 \x01(\tR\textraData\"?\n" +
	"\x14NotifySystemResponse\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\x03R\x0enotificationId2\x94\x05\n" +
	"\rNotifyService\x12X\n" +
	"\x11ListNotifications\x12 .notify.ListNotificationsRequest\x1a!.notify.ListNotificationsResponse\x12=\n" +
	"\bMarkRead\x12\x17.notify.MarkReadRequest\x1a\x18.notify.MarkReadResponse\x12F\n" +
	"\vMarkAllRead\x12\x1a.notify.MarkAllReadRequest\x1a\x1b.notify.MarkAllReadResponse\x12O\n" +
	"\x0eGetUnreadCount\x12\x1d.notify.GetUnreadCountRequest\x1a\x1e.notify.GetUnreadCountResponse\x12^\n" +
	"\x13NotifyFriendRequest\x12\".notify.NotifyFriendRequestRequest\x1a#.notify.NotifyFriendRequestResponse\x12[\n" +
	"\x12NotifyGroupRequest\x12!.notify.NotifyGroupRequestRequest\x1a\".notify.NotifyGroupRequestResponse\x12I\n" +
	"\fNotifyInvite\x12\x1b.notify.NotifyInviteRequest\x1a\x1c.notify.NotifyInviteResponse\x12I\n" +
	"\fNotifySystem\x12\x1b.notify.NotifySystemRequest\x1a\x1c.notify.NotifySystemResponseB\x14Z\x12services/notify/pbb\x06proto3"

var (
	file_beehive_m_notify_proto_rawDescOnce sync.Once
	file_beehive_m_notify_proto_rawDescData []byte
)

func file_beehive_m_notify_proto_rawDescGZIP() []byte {
	file_beehive_m_notify_proto_rawDescOnce.Do(func() {
		file_beehive_m_notify_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_beehive_m_notify_proto_rawDesc), len(file_beehive_m_notify_proto_rawDesc)))
	})
	return file_beehive_m_notify_proto_rawDescData
}

var file_beehive_m_notify_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_beehive_m_notify_proto_goTypes = []any{
	(*Notification)(nil),                // 0: notify.Notification
	(*ListNotificationsRequest)(nil),    // 1: notify.ListNotificationsRequest
	(*ListNotificationsResponse)(nil),   // 2: notify.ListNotificationsResponse
	(*MarkReadRequest)(nil),             // 3: notify.MarkReadRequest
	(*MarkReadResponse)(nil),            // 4: notify.MarkReadResponse
	(*MarkAllReadRequest)(nil),          // 5: notify.MarkAllReadRequest
	(*MarkAllReadResponse)(nil),         // 6: notify.MarkAllReadResponse
	(*GetUnreadCountRequest)(nil),       // 7: notify.GetUnreadCountRequest
	(*GetUnreadCountResponse)(nil),      // 8: notify.GetUnreadCountResponse
	(*NotifyFriendRequestRequest)(nil),  // 9: notify.NotifyFriendRequestRequest
	(*NotifyFriendRequestResponse)(nil), // 10: notify.NotifyFriendRequestResponse
	(*NotifyGroupRequestRequest)(nil),   // 11: notify.NotifyGroupRequestRequest
	(*NotifyGroupRequestResponse)(nil),  // 12: notify.NotifyGroupRequestResponse
	(*NotifyInviteRequest)(nil),         // 13: notify.NotifyInviteRequest
	(*NotifyInviteResponse)(nil),        // 14: notify.NotifyInviteResponse
	(*NotifySystemRequest)(nil),         // 15: notify.NotifySystemRequest
	(*NotifySystemResponse)(nil),        // 16: notify.NotifySystemResponse
}
var file_beehive_m_notify_proto_depIdxs = []int32{
	0,  // 0: notify.ListNotificationsResponse.notifications:type_name -> notify.Notification
	1,  // 1: notify.NotifyService.ListNotifications:input_type -> notify.ListNotificationsRequest
	3,  // 2: notify.NotifyService.MarkRead:input_type -> notify.MarkReadRequest
	5,  // 3: notify.NotifyService.MarkAllRead:input_type -> notify.MarkAllReadRequest
	7,  // 4: notify.NotifyService.GetUnreadCount:input_type -> notify.GetUnreadCountRequest
	9,  // 5: notify.NotifyService.NotifyFriendRequest:input_type -> notify.NotifyFriendRequestRequest
	11, // 6: notify.NotifyService.NotifyGroupRequest:input_type -> notify.NotifyGroupRequestRequest
	13, // 7: notify.NotifyService.NotifyInvite:input_type -> notify.NotifyInviteRequest
	15, // 8: notify.NotifyService.NotifySystem:input_type -> notify.NotifySystemRequest
	2,  // 9: notify.NotifyService.ListNotifications:output_type -> notify.ListNotificationsResponse
	4,  // 10: notify.NotifyService.MarkRead:output_type -> notify.MarkReadResponse
	6,  // 11: notify.NotifyService.MarkAllRead:output_type -> notify.MarkAllReadResponse
	8,  // 12: notify.NotifyService.GetUnreadCount:output_type -> notify.GetUnreadCountResponse
	10, // 13: notify.NotifyService.NotifyFriendRequest:output_type -> notify.NotifyFriendRequestResponse
	12, // 14: notify.NotifyService.NotifyGroupRequest:output_type -> notify.NotifyGroupRequestResponse
	14, // 15: notify.NotifyService.NotifyInvite:output_type -> notify.NotifyInviteResponse
	16, // 16: notify.NotifyService.NotifySystem:output_type -> notify.NotifySystemResponse
	9,  // [9:17] is the sub-list for method output_type
	1,  // [1:9] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_beehive_m_notify_proto_init() }
func file_beehive_m_notify_proto_init() {
	if File_beehive_m_notify_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_beehive_m_notify_proto_rawDesc), len(file_beehive_m_notify_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_beehive_m_notify_proto_goTypes,
		DependencyIndexes: file_beehive_m_notify_proto_depIdxs,
		MessageInfos:      file_beehive_m_notify_proto_msgTypes,
	}.Build()
	File_beehive_m_notify_proto = out.File
	file_beehive_m_notify_proto_goTypes = nil
	file_beehive_m_notify_proto_depIdxs = nil
}
