// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.4
// source: notify.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NotifyService_ListNotifications_FullMethodName   = "/notify.NotifyService/ListNotifications"
	NotifyService_MarkRead_FullMethodName            = "/notify.NotifyService/MarkRead"
	NotifyService_MarkAllRead_FullMethodName         = "/notify.NotifyService/MarkAllRead"
	NotifyService_GetUnreadCount_FullMethodName      = "/notify.NotifyService/GetUnreadCount"
	NotifyService_NotifyFriendRequest_FullMethodName = "/notify.NotifyService/NotifyFriendRequest"
	NotifyService_NotifyGroupRequest_FullMethodName  = "/notify.NotifyService/NotifyGroupRequest"
	NotifyService_NotifyInvite_FullMethodName        = "/notify.NotifyService/NotifyInvite"
	NotifyService_NotifySystem_FullMethodName        = "/notify.NotifyService/NotifySystem"
)

// NotifyServiceClient is the client API for NotifyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// NotifyService 系统通知的列表、已读、未读数；内部创建通知（供 Friend/Group 等调）
type NotifyServiceClient interface {
	// 对客户端
	ListNotifications(ctx context.Context, in *ListNotificationsRequest, opts ...grpc.CallOption) (*ListNotificationsResponse, error)
	MarkRead(ctx context.Context, in *MarkReadRequest, opts ...grpc.CallOption) (*MarkReadResponse, error)
	MarkAllRead(ctx context.Context, in *MarkAllReadRequest, opts ...grpc.CallOption) (*MarkAllReadResponse, error)
	GetUnreadCount(ctx context.Context, in *GetUnreadCountRequest, opts ...grpc.CallOption) (*GetUnreadCountResponse, error)
	// 内部创建（供 Friend/Group 等调）
	NotifyFriendRequest(ctx context.Context, in *NotifyFriendRequestRequest, opts ...grpc.CallOption) (*NotifyFriendRequestResponse, error)
	NotifyGroupRequest(ctx context.Context, in *NotifyGroupRequestRequest, opts ...grpc.CallOption) (*NotifyGroupRequestResponse, error)
	NotifyInvite(ctx context.Context, in *NotifyInviteRequest, opts ...grpc.CallOption) (*NotifyInviteResponse, error)
	NotifySystem(ctx context.Context, in *NotifySystemRequest, opts ...grpc.CallOption) (*NotifySystemResponse, error)
}

type notifyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNotifyServiceClient(cc grpc.ClientConnInterface) NotifyServiceClient {
	return &notifyServiceClient{cc}
}

func (c *notifyServiceClient) ListNotifications(ctx context.Context, in *ListNotificationsRequest, opts ...grpc.CallOption) (*ListNotificationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNotificationsResponse)
	err := c.cc.Invoke(ctx, NotifyService_ListNotifications_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) MarkRead(ctx context.Context, in *MarkReadRequest, opts ...grpc.CallOption) (*MarkReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarkReadResponse)
	err := c.cc.Invoke(ctx, NotifyService_MarkRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) MarkAllRead(ctx context.Context, in *MarkAllReadRequest, opts ...grpc.CallOption) (*MarkAllReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarkAllReadResponse)
	err := c.cc.Invoke(ctx, NotifyService_MarkAllRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) GetUnreadCount(ctx context.Context, in *GetUnreadCountRequest, opts ...grpc.CallOption) (*GetUnreadCountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUnreadCountResponse)
	err := c.cc.Invoke(ctx, NotifyService_GetUnreadCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) NotifyFriendRequest(ctx context.Context, in *NotifyFriendRequestRequest, opts ...grpc.CallOption) (*NotifyFriendRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotifyFriendRequestResponse)
	err := c.cc.Invoke(ctx, NotifyService_NotifyFriendRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) NotifyGroupRequest(ctx context.Context, in *NotifyGroupRequestRequest, opts ...grpc.CallOption) (*NotifyGroupRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotifyGroupRequestResponse)
	err := c.cc.Invoke(ctx, NotifyService_NotifyGroupRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) NotifyInvite(ctx context.Context, in *NotifyInviteRequest, opts ...grpc.CallOption) (*NotifyInviteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotifyInviteResponse)
	err := c.cc.Invoke(ctx, NotifyService_NotifyInvite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifyServiceClient) NotifySystem(ctx context.Context, in *NotifySystemRequest, opts ...grpc.CallOption) (*NotifySystemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotifySystemResponse)
	err := c.cc.Invoke(ctx, NotifyService_NotifySystem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotifyServiceServer is the server API for NotifyService service.
// All implementations must embed UnimplementedNotifyServiceServer
// for forward compatibility.
//
// NotifyService 系统通知的列表、已读、未读数；内部创建通知（供 Friend/Group 等调）
type NotifyServiceServer interface {
	// 对客户端
	ListNotifications(context.Context, *ListNotificationsRequest) (*ListNotificationsResponse, error)
	MarkRead(context.Context, *MarkReadRequest) (*MarkReadResponse, error)
	MarkAllRead(context.Context, *MarkAllReadRequest) (*MarkAllReadResponse, error)
	GetUnreadCount(context.Context, *GetUnreadCountRequest) (*GetUnreadCountResponse, error)
	// 内部创建（供 Friend/Group 等调）
	NotifyFriendRequest(context.Context, *NotifyFriendRequestRequest) (*NotifyFriendRequestResponse, error)
	NotifyGroupRequest(context.Context, *NotifyGroupRequestRequest) (*NotifyGroupRequestResponse, error)
	NotifyInvite(context.Context, *NotifyInviteRequest) (*NotifyInviteResponse, error)
	NotifySystem(context.Context, *NotifySystemRequest) (*NotifySystemResponse, error)
	mustEmbedUnimplementedNotifyServiceServer()
}

// UnimplementedNotifyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNotifyServiceServer struct{}

func (UnimplementedNotifyServiceServer) ListNotifications(context.Context, *ListNotificationsRequest) (*ListNotificationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNotifications not implemented")
}
func (UnimplementedNotifyServiceServer) MarkRead(context.Context, *MarkReadRequest) (*MarkReadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkRead not implemented")
}
func (UnimplementedNotifyServiceServer) MarkAllRead(context.Context, *MarkAllReadRequest) (*MarkAllReadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkAllRead not implemented")
}
func (UnimplementedNotifyServiceServer) GetUnreadCount(context.Context, *GetUnreadCountRequest) (*GetUnreadCountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUnreadCount not implemented")
}
func (UnimplementedNotifyServiceServer) NotifyFriendRequest(context.Context, *NotifyFriendRequestRequest) (*NotifyFriendRequestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NotifyFriendRequest not implemented")
}
func (UnimplementedNotifyServiceServer) NotifyGroupRequest(context.Context, *NotifyGroupRequestRequest) (*NotifyGroupRequestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NotifyGroupRequest not implemented")
}
func (UnimplementedNotifyServiceServer) NotifyInvite(context.Context, *NotifyInviteRequest) (*NotifyInviteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NotifyInvite not implemented")
}
func (UnimplementedNotifyServiceServer) NotifySystem(context.Context, *NotifySystemRequest) (*NotifySystemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NotifySystem not implemented")
}
func (UnimplementedNotifyServiceServer) mustEmbedUnimplementedNotifyServiceServer() {}
func (UnimplementedNotifyServiceServer) testEmbeddedByValue()                       {}

// UnsafeNotifyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotifyServiceServer will
// result in compilation errors.
type UnsafeNotifyServiceServer interface {
	mustEmbedUnimplementedNotifyServiceServer()
}

func RegisterNotifyServiceServer(s grpc.ServiceRegistrar, srv NotifyServiceServer) {
	// If the following call panics, it indicates UnimplementedNotifyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NotifyService_ServiceDesc, srv)
}

func _NotifyService_ListNotifications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNotificationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).ListNotifications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_ListNotifications_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).ListNotifications(ctx, req.(*ListNotificationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_MarkRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).MarkRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_MarkRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).MarkRead(ctx, req.(*MarkReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_MarkAllRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkAllReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).MarkAllRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_MarkAllRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).MarkAllRead(ctx, req.(*MarkAllReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_GetUnreadCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUnreadCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).GetUnreadCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_GetUnreadCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).GetUnreadCount(ctx, req.(*GetUnreadCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_NotifyFriendRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyFriendRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).NotifyFriendRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_NotifyFriendRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).NotifyFriendRequest(ctx, req.(*NotifyFriendRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_NotifyGroupRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyGroupRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).NotifyGroupRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_NotifyGroupRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).NotifyGroupRequest(ctx, req.(*NotifyGroupRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_NotifyInvite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyInviteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).NotifyInvite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_NotifyInvite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).NotifyInvite(ctx, req.(*NotifyInviteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifyService_NotifySystem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifySystemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifyServiceServer).NotifySystem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifyService_NotifySystem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifyServiceServer).NotifySystem(ctx, req.(*NotifySystemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NotifyService_ServiceDesc is the grpc.ServiceDesc for NotifyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NotifyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "notify.NotifyService",
	HandlerType: (*NotifyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListNotifications",
			Handler:    _NotifyService_ListNotifications_Handler,
		},
		{
			MethodName: "MarkRead",
			Handler:    _NotifyService_MarkRead_Handler,
		},
		{
			MethodName: "MarkAllRead",
			Handler:    _NotifyService_MarkAllRead_Handler,
		},
		{
			MethodName: "GetUnreadCount",
			Handler:    _NotifyService_GetUnreadCount_Handler,
		},
		{
			MethodName: "NotifyFriendRequest",
			Handler:    _NotifyService_NotifyFriendRequest_Handler,
		},
		{
			MethodName: "NotifyGroupRequest",
			Handler:    _NotifyService_NotifyGroupRequest_Handler,
		},
		{
			MethodName: "NotifyInvite",
			Handler:    _NotifyService_NotifyInvite_Handler,
		},
		{
			MethodName: "NotifySystem",
			Handler:    _NotifyService_NotifySystem_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "notify.proto",
}
