// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: beehive-m-user.proto

package userservice

import (
	"context"

	"github.com/HappyLadySauce/Beehive-M/services/user/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetUserBatchRequest     = pb.GetUserBatchRequest
	GetUserBatchResponse    = pb.GetUserBatchResponse
	GetUserByAccountRequest = pb.GetUserByAccountRequest
	GetUserForAuthRequest   = pb.GetUserForAuthRequest
	GetUserRequest          = pb.GetUserRequest
	SearchUsersRequest      = pb.SearchUsersRequest
	SearchUsersResponse     = pb.SearchUsersResponse
	UpdateProfileRequest    = pb.UpdateProfileRequest
	User                    = pb.User
	UserForAuth             = pb.UserForAuth

	UserService interface {
		// 按 user_id 查单个用户（会话头、资料页等）
		GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*User, error)
		// 批量按 user_id 查（会话列表、群成员列表等）
		GetUserBatch(ctx context.Context, in *GetUserBatchRequest, opts ...grpc.CallOption) (*GetUserBatchResponse, error)
		// 按账号查（登录、搜索用）
		GetUserByAccount(ctx context.Context, in *GetUserByAccountRequest, opts ...grpc.CallOption) (*User, error)
		// 关键词搜索用户（全文检索），分页
		SearchUsers(ctx context.Context, in *SearchUsersRequest, opts ...grpc.CallOption) (*SearchUsersResponse, error)
		// 更新当前用户资料（昵称、头像、签名等）
		UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*User, error)
		// 仅内部使用：按 user_id 查用户（含 password_hash），供 auth 登录校验
		GetUserForAuth(ctx context.Context, in *GetUserForAuthRequest, opts ...grpc.CallOption) (*UserForAuth, error)
	}

	defaultUserService struct {
		cli zrpc.Client
	}
)

func NewUserService(cli zrpc.Client) UserService {
	return &defaultUserService{
		cli: cli,
	}
}

// 按 user_id 查单个用户（会话头、资料页等）
func (m *defaultUserService) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*User, error) {
	client := pb.NewUserServiceClient(m.cli.Conn())
	return client.GetUser(ctx, in, opts...)
}

// 批量按 user_id 查（会话列表、群成员列表等）
func (m *defaultUserService) GetUserBatch(ctx context.Context, in *GetUserBatchRequest, opts ...grpc.CallOption) (*GetUserBatchResponse, error) {
	client := pb.NewUserServiceClient(m.cli.Conn())
	return client.GetUserBatch(ctx, in, opts...)
}

// 按账号查（登录、搜索用）
func (m *defaultUserService) GetUserByAccount(ctx context.Context, in *GetUserByAccountRequest, opts ...grpc.CallOption) (*User, error) {
	client := pb.NewUserServiceClient(m.cli.Conn())
	return client.GetUserByAccount(ctx, in, opts...)
}

// 关键词搜索用户（全文检索），分页
func (m *defaultUserService) SearchUsers(ctx context.Context, in *SearchUsersRequest, opts ...grpc.CallOption) (*SearchUsersResponse, error) {
	client := pb.NewUserServiceClient(m.cli.Conn())
	return client.SearchUsers(ctx, in, opts...)
}

// 更新当前用户资料（昵称、头像、签名等）
func (m *defaultUserService) UpdateProfile(ctx context.Context, in *UpdateProfileRequest, opts ...grpc.CallOption) (*User, error) {
	client := pb.NewUserServiceClient(m.cli.Conn())
	return client.UpdateProfile(ctx, in, opts...)
}

// 仅内部使用：按 user_id 查用户（含 password_hash），供 auth 登录校验
func (m *defaultUserService) GetUserForAuth(ctx context.Context, in *GetUserForAuthRequest, opts ...grpc.CallOption) (*UserForAuth, error) {
	client := pb.NewUserServiceClient(m.cli.Conn())
	return client.GetUserForAuth(ctx, in, opts...)
}
