// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: beehive-m-notify.proto

package notifyservice

import (
	"context"

	"github.com/HappyLadySauce/Beehive-M/services/notify/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetUnreadCountRequest       = pb.GetUnreadCountRequest
	GetUnreadCountResponse      = pb.GetUnreadCountResponse
	ListNotificationsRequest    = pb.ListNotificationsRequest
	ListNotificationsResponse   = pb.ListNotificationsResponse
	MarkAllReadRequest          = pb.MarkAllReadRequest
	MarkAllReadResponse         = pb.MarkAllReadResponse
	MarkReadRequest             = pb.MarkReadRequest
	MarkReadResponse            = pb.MarkReadResponse
	Notification                = pb.Notification
	NotifyFriendRequestRequest  = pb.NotifyFriendRequestRequest
	NotifyFriendRequestResponse = pb.NotifyFriendRequestResponse
	NotifyGroupRequestRequest   = pb.NotifyGroupRequestRequest
	NotifyGroupRequestResponse  = pb.NotifyGroupRequestResponse
	NotifyInviteRequest         = pb.NotifyInviteRequest
	NotifyInviteResponse        = pb.NotifyInviteResponse
	NotifySystemRequest         = pb.NotifySystemRequest
	NotifySystemResponse        = pb.NotifySystemResponse

	NotifyService interface {
		// 对客户端
		ListNotifications(ctx context.Context, in *ListNotificationsRequest, opts ...grpc.CallOption) (*ListNotificationsResponse, error)
		MarkRead(ctx context.Context, in *MarkReadRequest, opts ...grpc.CallOption) (*MarkReadResponse, error)
		MarkAllRead(ctx context.Context, in *MarkAllReadRequest, opts ...grpc.CallOption) (*MarkAllReadResponse, error)
		GetUnreadCount(ctx context.Context, in *GetUnreadCountRequest, opts ...grpc.CallOption) (*GetUnreadCountResponse, error)
		// 内部创建（供 Friend/Group 等调）
		NotifyFriendRequest(ctx context.Context, in *NotifyFriendRequestRequest, opts ...grpc.CallOption) (*NotifyFriendRequestResponse, error)
		NotifyGroupRequest(ctx context.Context, in *NotifyGroupRequestRequest, opts ...grpc.CallOption) (*NotifyGroupRequestResponse, error)
		NotifyInvite(ctx context.Context, in *NotifyInviteRequest, opts ...grpc.CallOption) (*NotifyInviteResponse, error)
		NotifySystem(ctx context.Context, in *NotifySystemRequest, opts ...grpc.CallOption) (*NotifySystemResponse, error)
	}

	defaultNotifyService struct {
		cli zrpc.Client
	}
)

func NewNotifyService(cli zrpc.Client) NotifyService {
	return &defaultNotifyService{
		cli: cli,
	}
}

// 对客户端
func (m *defaultNotifyService) ListNotifications(ctx context.Context, in *ListNotificationsRequest, opts ...grpc.CallOption) (*ListNotificationsResponse, error) {
	client := pb.NewNotifyServiceClient(m.cli.Conn())
	return client.ListNotifications(ctx, in, opts...)
}

func (m *defaultNotifyService) MarkRead(ctx context.Context, in *MarkReadRequest, opts ...grpc.CallOption) (*MarkReadResponse, error) {
	client := pb.NewNotifyServiceClient(m.cli.Conn())
	return client.MarkRead(ctx, in, opts...)
}

func (m *defaultNotifyService) MarkAllRead(ctx context.Context, in *MarkAllReadRequest, opts ...grpc.CallOption) (*MarkAllReadResponse, error) {
	client := pb.NewNotifyServiceClient(m.cli.Conn())
	return client.MarkAllRead(ctx, in, opts...)
}

func (m *defaultNotifyService) GetUnreadCount(ctx context.Context, in *GetUnreadCountRequest, opts ...grpc.CallOption) (*GetUnreadCountResponse, error) {
	client := pb.NewNotifyServiceClient(m.cli.Conn())
	return client.GetUnreadCount(ctx, in, opts...)
}

// 内部创建（供 Friend/Group 等调）
func (m *defaultNotifyService) NotifyFriendRequest(ctx context.Context, in *NotifyFriendRequestRequest, opts ...grpc.CallOption) (*NotifyFriendRequestResponse, error) {
	client := pb.NewNotifyServiceClient(m.cli.Conn())
	return client.NotifyFriendRequest(ctx, in, opts...)
}

func (m *defaultNotifyService) NotifyGroupRequest(ctx context.Context, in *NotifyGroupRequestRequest, opts ...grpc.CallOption) (*NotifyGroupRequestResponse, error) {
	client := pb.NewNotifyServiceClient(m.cli.Conn())
	return client.NotifyGroupRequest(ctx, in, opts...)
}

func (m *defaultNotifyService) NotifyInvite(ctx context.Context, in *NotifyInviteRequest, opts ...grpc.CallOption) (*NotifyInviteResponse, error) {
	client := pb.NewNotifyServiceClient(m.cli.Conn())
	return client.NotifyInvite(ctx, in, opts...)
}

func (m *defaultNotifyService) NotifySystem(ctx context.Context, in *NotifySystemRequest, opts ...grpc.CallOption) (*NotifySystemResponse, error) {
	client := pb.NewNotifyServiceClient(m.cli.Conn())
	return client.NotifySystem(ctx, in, opts...)
}
