// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: notify.proto

package server

import (
	"context"

	"github.com/HappyLadySauce/Beehive-M/services/notify/internal/logic/notifyservice"
	"github.com/HappyLadySauce/Beehive-M/services/notify/internal/svc"
	"github.com/HappyLadySauce/Beehive-M/services/notify/pb"
)

type NotifyServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedNotifyServiceServer
}

func NewNotifyServiceServer(svcCtx *svc.ServiceContext) *NotifyServiceServer {
	return &NotifyServiceServer{
		svcCtx: svcCtx,
	}
}

// 对客户端
func (s *NotifyServiceServer) ListNotifications(ctx context.Context, in *pb.ListNotificationsRequest) (*pb.ListNotificationsResponse, error) {
	l := notifyservicelogic.NewListNotificationsLogic(ctx, s.svcCtx)
	return l.ListNotifications(in)
}

func (s *NotifyServiceServer) MarkRead(ctx context.Context, in *pb.MarkReadRequest) (*pb.MarkReadResponse, error) {
	l := notifyservicelogic.NewMarkReadLogic(ctx, s.svcCtx)
	return l.MarkRead(in)
}

func (s *NotifyServiceServer) MarkAllRead(ctx context.Context, in *pb.MarkAllReadRequest) (*pb.MarkAllReadResponse, error) {
	l := notifyservicelogic.NewMarkAllReadLogic(ctx, s.svcCtx)
	return l.MarkAllRead(in)
}

func (s *NotifyServiceServer) GetUnreadCount(ctx context.Context, in *pb.GetUnreadCountRequest) (*pb.GetUnreadCountResponse, error) {
	l := notifyservicelogic.NewGetUnreadCountLogic(ctx, s.svcCtx)
	return l.GetUnreadCount(in)
}

// 内部创建（供 Friend/Group 等调）
func (s *NotifyServiceServer) NotifyFriendRequest(ctx context.Context, in *pb.NotifyFriendRequestRequest) (*pb.NotifyFriendRequestResponse, error) {
	l := notifyservicelogic.NewNotifyFriendRequestLogic(ctx, s.svcCtx)
	return l.NotifyFriendRequest(in)
}

func (s *NotifyServiceServer) NotifyGroupRequest(ctx context.Context, in *pb.NotifyGroupRequestRequest) (*pb.NotifyGroupRequestResponse, error) {
	l := notifyservicelogic.NewNotifyGroupRequestLogic(ctx, s.svcCtx)
	return l.NotifyGroupRequest(in)
}

func (s *NotifyServiceServer) NotifyInvite(ctx context.Context, in *pb.NotifyInviteRequest) (*pb.NotifyInviteResponse, error) {
	l := notifyservicelogic.NewNotifyInviteLogic(ctx, s.svcCtx)
	return l.NotifyInvite(in)
}

func (s *NotifyServiceServer) NotifySystem(ctx context.Context, in *pb.NotifySystemRequest) (*pb.NotifySystemResponse, error) {
	l := notifyservicelogic.NewNotifySystemLogic(ctx, s.svcCtx)
	return l.NotifySystem(in)
}
