// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: beehive-m-resource.proto

package resourceservice

import (
	"context"

	"github.com/HappyLadySauce/Beehive-M/services/resource/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CleanExpiredTempRequest  = pb.CleanExpiredTempRequest
	CleanExpiredTempResponse = pb.CleanExpiredTempResponse
	DeleteResourceRequest    = pb.DeleteResourceRequest
	DeleteResourceResponse   = pb.DeleteResourceResponse
	GetByHashRequest         = pb.GetByHashRequest
	GetByHashResponse        = pb.GetByHashResponse
	GetResourceRequest       = pb.GetResourceRequest
	GetResourceResponse      = pb.GetResourceResponse
	Resource                 = pb.Resource
	UploadRequest            = pb.UploadRequest
	UploadResponse           = pb.UploadResponse

	ResourceService interface {
		Upload(ctx context.Context, in *UploadRequest, opts ...grpc.CallOption) (*UploadResponse, error)
		GetResource(ctx context.Context, in *GetResourceRequest, opts ...grpc.CallOption) (*GetResourceResponse, error)
		DeleteResource(ctx context.Context, in *DeleteResourceRequest, opts ...grpc.CallOption) (*DeleteResourceResponse, error)
		GetByHash(ctx context.Context, in *GetByHashRequest, opts ...grpc.CallOption) (*GetByHashResponse, error)
		CleanExpiredTemp(ctx context.Context, in *CleanExpiredTempRequest, opts ...grpc.CallOption) (*CleanExpiredTempResponse, error)
	}

	defaultResourceService struct {
		cli zrpc.Client
	}
)

func NewResourceService(cli zrpc.Client) ResourceService {
	return &defaultResourceService{
		cli: cli,
	}
}

func (m *defaultResourceService) Upload(ctx context.Context, in *UploadRequest, opts ...grpc.CallOption) (*UploadResponse, error) {
	client := pb.NewResourceServiceClient(m.cli.Conn())
	return client.Upload(ctx, in, opts...)
}

func (m *defaultResourceService) GetResource(ctx context.Context, in *GetResourceRequest, opts ...grpc.CallOption) (*GetResourceResponse, error) {
	client := pb.NewResourceServiceClient(m.cli.Conn())
	return client.GetResource(ctx, in, opts...)
}

func (m *defaultResourceService) DeleteResource(ctx context.Context, in *DeleteResourceRequest, opts ...grpc.CallOption) (*DeleteResourceResponse, error) {
	client := pb.NewResourceServiceClient(m.cli.Conn())
	return client.DeleteResource(ctx, in, opts...)
}

func (m *defaultResourceService) GetByHash(ctx context.Context, in *GetByHashRequest, opts ...grpc.CallOption) (*GetByHashResponse, error) {
	client := pb.NewResourceServiceClient(m.cli.Conn())
	return client.GetByHash(ctx, in, opts...)
}

func (m *defaultResourceService) CleanExpiredTemp(ctx context.Context, in *CleanExpiredTempRequest, opts ...grpc.CallOption) (*CleanExpiredTempResponse, error) {
	client := pb.NewResourceServiceClient(m.cli.Conn())
	return client.CleanExpiredTemp(ctx, in, opts...)
}
