// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: beehive-m-resource.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 资源（与 resources 表对齐）
type Resource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	UploaderId    int64                  `protobuf:"varint,2,opt,name=uploader_id,json=uploaderId,proto3" json:"uploader_id,omitempty"`
	FileName      string                 `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileType      string                 `protobuf:"bytes,4,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"` // image/jpeg 等
	FileSize      int64                  `protobuf:"varint,5,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	FileHash      string                 `protobuf:"bytes,6,opt,name=file_hash,json=fileHash,proto3" json:"file_hash,omitempty"`
	StoragePath   string                 `protobuf:"bytes,7,opt,name=storage_path,json=storagePath,proto3" json:"storage_path,omitempty"`
	Url           string                 `protobuf:"bytes,8,opt,name=url,proto3" json:"url,omitempty"` // 访问 URL
	Width         int32                  `protobuf:"varint,9,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,10,opt,name=height,proto3" json:"height,omitempty"`
	UploadTime    int64                  `protobuf:"varint,11,opt,name=upload_time,json=uploadTime,proto3" json:"upload_time,omitempty"`
	Status        int32                  `protobuf:"varint,12,opt,name=status,proto3" json:"status,omitempty"`               // 1正常 2已删除
	IsTemp        int32                  `protobuf:"varint,13,opt,name=is_temp,json=isTemp,proto3" json:"is_temp,omitempty"` // 0否 1是
	ExpireTime    int64                  `protobuf:"varint,14,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_beehive_m_resource_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_resource_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_beehive_m_resource_proto_rawDescGZIP(), []int{0}
}

func (x *Resource) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *Resource) GetUploaderId() int64 {
	if x != nil {
		return x.UploaderId
	}
	return 0
}

func (x *Resource) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *Resource) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

func (x *Resource) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *Resource) GetFileHash() string {
	if x != nil {
		return x.FileHash
	}
	return ""
}

func (x *Resource) GetStoragePath() string {
	if x != nil {
		return x.StoragePath
	}
	return ""
}

func (x *Resource) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Resource) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Resource) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Resource) GetUploadTime() int64 {
	if x != nil {
		return x.UploadTime
	}
	return 0
}

func (x *Resource) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Resource) GetIsTemp() int32 {
	if x != nil {
		return x.IsTemp
	}
	return 0
}

func (x *Resource) GetExpireTime() int64 {
	if x != nil {
		return x.ExpireTime
	}
	return 0
}

type UploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UploaderId    int64                  `protobuf:"varint,1,opt,name=uploader_id,json=uploaderId,proto3" json:"uploader_id,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	FileType      string                 `protobuf:"bytes,3,opt,name=file_type,json=fileType,proto3" json:"file_type,omitempty"`
	FileSize      int64                  `protobuf:"varint,4,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	FileHash      string                 `protobuf:"bytes,5,opt,name=file_hash,json=fileHash,proto3" json:"file_hash,omitempty"`        // 可选，用于秒传
	Content       string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`                          // 小文件 base64；或由实现改为 stream/url
	IsTemp        int32                  `protobuf:"varint,7,opt,name=is_temp,json=isTemp,proto3" json:"is_temp,omitempty"`             // 0否 1是
	ExpireTime    int64                  `protobuf:"varint,8,opt,name=expire_time,json=expireTime,proto3" json:"expire_time,omitempty"` // 临时文件过期时间戳
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadRequest) Reset() {
	*x = UploadRequest{}
	mi := &file_beehive_m_resource_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadRequest) ProtoMessage() {}

func (x *UploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_resource_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadRequest.ProtoReflect.Descriptor instead.
func (*UploadRequest) Descriptor() ([]byte, []int) {
	return file_beehive_m_resource_proto_rawDescGZIP(), []int{1}
}

func (x *UploadRequest) GetUploaderId() int64 {
	if x != nil {
		return x.UploaderId
	}
	return 0
}

func (x *UploadRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *UploadRequest) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

func (x *UploadRequest) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *UploadRequest) GetFileHash() string {
	if x != nil {
		return x.FileHash
	}
	return ""
}

func (x *UploadRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *UploadRequest) GetIsTemp() int32 {
	if x != nil {
		return x.IsTemp
	}
	return 0
}

func (x *UploadRequest) GetExpireTime() int64 {
	if x != nil {
		return x.ExpireTime
	}
	return 0
}

type UploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	StoragePath   string                 `protobuf:"bytes,2,opt,name=storage_path,json=storagePath,proto3" json:"storage_path,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Width         int32                  `protobuf:"varint,4,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,5,opt,name=height,proto3" json:"height,omitempty"`
	FromHash      bool                   `protobuf:"varint,6,opt,name=from_hash,json=fromHash,proto3" json:"from_hash,omitempty"` // 是否秒传命中
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadResponse) Reset() {
	*x = UploadResponse{}
	mi := &file_beehive_m_resource_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResponse) ProtoMessage() {}

func (x *UploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_resource_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadResponse.ProtoReflect.Descriptor instead.
func (*UploadResponse) Descriptor() ([]byte, []int) {
	return file_beehive_m_resource_proto_rawDescGZIP(), []int{2}
}

func (x *UploadResponse) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *UploadResponse) GetStoragePath() string {
	if x != nil {
		return x.StoragePath
	}
	return ""
}

func (x *UploadResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *UploadResponse) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *UploadResponse) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *UploadResponse) GetFromHash() bool {
	if x != nil {
		return x.FromHash
	}
	return false
}

type GetResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResourceRequest) Reset() {
	*x = GetResourceRequest{}
	mi := &file_beehive_m_resource_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResourceRequest) ProtoMessage() {}

func (x *GetResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_resource_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResourceRequest.ProtoReflect.Descriptor instead.
func (*GetResourceRequest) Descriptor() ([]byte, []int) {
	return file_beehive_m_resource_proto_rawDescGZIP(), []int{3}
}

func (x *GetResourceRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

type GetResourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      *Resource              `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResourceResponse) Reset() {
	*x = GetResourceResponse{}
	mi := &file_beehive_m_resource_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResourceResponse) ProtoMessage() {}

func (x *GetResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_resource_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResourceResponse.ProtoReflect.Descriptor instead.
func (*GetResourceResponse) Descriptor() ([]byte, []int) {
	return file_beehive_m_resource_proto_rawDescGZIP(), []int{4}
}

func (x *GetResourceResponse) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

type DeleteResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceId    string                 `protobuf:"bytes,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	UploaderId    int64                  `protobuf:"varint,2,opt,name=uploader_id,json=uploaderId,proto3" json:"uploader_id,omitempty"` // 可选，校验归属
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResourceRequest) Reset() {
	*x = DeleteResourceRequest{}
	mi := &file_beehive_m_resource_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResourceRequest) ProtoMessage() {}

func (x *DeleteResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_resource_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResourceRequest.ProtoReflect.Descriptor instead.
func (*DeleteResourceRequest) Descriptor() ([]byte, []int) {
	return file_beehive_m_resource_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteResourceRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *DeleteResourceRequest) GetUploaderId() int64 {
	if x != nil {
		return x.UploaderId
	}
	return 0
}

type DeleteResourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResourceResponse) Reset() {
	*x = DeleteResourceResponse{}
	mi := &file_beehive_m_resource_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResourceResponse) ProtoMessage() {}

func (x *DeleteResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_resource_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResourceResponse.ProtoReflect.Descriptor instead.
func (*DeleteResourceResponse) Descriptor() ([]byte, []int) {
	return file_beehive_m_resource_proto_rawDescGZIP(), []int{6}
}

type GetByHashRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileHash      string                 `protobuf:"bytes,1,opt,name=file_hash,json=fileHash,proto3" json:"file_hash,omitempty"`
	UploaderId    int64                  `protobuf:"varint,2,opt,name=uploader_id,json=uploaderId,proto3" json:"uploader_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByHashRequest) Reset() {
	*x = GetByHashRequest{}
	mi := &file_beehive_m_resource_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByHashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByHashRequest) ProtoMessage() {}

func (x *GetByHashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_resource_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByHashRequest.ProtoReflect.Descriptor instead.
func (*GetByHashRequest) Descriptor() ([]byte, []int) {
	return file_beehive_m_resource_proto_rawDescGZIP(), []int{7}
}

func (x *GetByHashRequest) GetFileHash() string {
	if x != nil {
		return x.FileHash
	}
	return ""
}

func (x *GetByHashRequest) GetUploaderId() int64 {
	if x != nil {
		return x.UploaderId
	}
	return 0
}

type GetByHashResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	ResourceId    string                 `protobuf:"bytes,2,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetByHashResponse) Reset() {
	*x = GetByHashResponse{}
	mi := &file_beehive_m_resource_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetByHashResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByHashResponse) ProtoMessage() {}

func (x *GetByHashResponse) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_resource_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByHashResponse.ProtoReflect.Descriptor instead.
func (*GetByHashResponse) Descriptor() ([]byte, []int) {
	return file_beehive_m_resource_proto_rawDescGZIP(), []int{8}
}

func (x *GetByHashResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

func (x *GetByHashResponse) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *GetByHashResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type CleanExpiredTempRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleanExpiredTempRequest) Reset() {
	*x = CleanExpiredTempRequest{}
	mi := &file_beehive_m_resource_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanExpiredTempRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanExpiredTempRequest) ProtoMessage() {}

func (x *CleanExpiredTempRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_resource_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanExpiredTempRequest.ProtoReflect.Descriptor instead.
func (*CleanExpiredTempRequest) Descriptor() ([]byte, []int) {
	return file_beehive_m_resource_proto_rawDescGZIP(), []int{9}
}

type CleanExpiredTempResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeletedCount  int32                  `protobuf:"varint,1,opt,name=deleted_count,json=deletedCount,proto3" json:"deleted_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleanExpiredTempResponse) Reset() {
	*x = CleanExpiredTempResponse{}
	mi := &file_beehive_m_resource_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanExpiredTempResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanExpiredTempResponse) ProtoMessage() {}

func (x *CleanExpiredTempResponse) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_resource_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanExpiredTempResponse.ProtoReflect.Descriptor instead.
func (*CleanExpiredTempResponse) Descriptor() ([]byte, []int) {
	return file_beehive_m_resource_proto_rawDescGZIP(), []int{10}
}

func (x *CleanExpiredTempResponse) GetDeletedCount() int32 {
	if x != nil {
		return x.DeletedCount
	}
	return 0
}

var File_beehive_m_resource_proto protoreflect.FileDescriptor

const file_beehive_m_resource_proto_rawDesc = "" +
	"\n" +
	"\x18beehive-m-resource.proto\x12\bresource\"\x96\x03\n" +
	"\bResource\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\x12\x1f\n" +
	"\vuploader_id\x18\x02 \x01(\x03R\n" +
	"uploaderId\x12\x1b\n" +
	"\tfile_name\x18\x03 \x01(\tR\bfileName\x12\x1b\n" +
	"\tfile_type\x18\x04 \x01(\tR\bfileType\x12\x1b\n" +
	"\tfile_size\x18\x05 \x01(\x03R\bfileSize\x12\x1b\n" +
	"\tfile_hash\x18\x06 \x01(\tR\bfileHash\x12!\n" +
	"\fstorage_path\x18\a \x01(\tR\vstoragePath\x12\x10\n" +
	"\x03url\x18\b \x01(\tR\x03url\x12\x14\n" +
	"\x05width\x18\t \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\n" +
	" \x01(\x05R\x06height\x12\x1f\n" +
	"\vupload_time\x18\v \x01(\x03R\n" +
	"uploadTime\x12\x16\n" +
	"\x06status\x18\f \x01(\x05R\x06status\x12\x17\n" +
	"\ais_temp\x18\r \x01(\x05R\x06isTemp\x12\x1f\n" +
	"\vexpire_time\x18\x0e \x01(\x03R\n" +
	"expireTime\"\xf8\x01\n" +
	"\rUploadRequest\x12\x1f\n" +
	"\vuploader_id\x18\x01 \x01(\x03R\n" +
	"uploaderId\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x1b\n" +
	"\tfile_type\x18\x03 \x01(\tR\bfileType\x12\x1b\n" +
	"\tfile_size\x18\x04 \x01(\x03R\bfileSize\x12\x1b\n" +
	"\tfile_hash\x18\x05 \x01(\tR\bfileHash\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12\x17\n" +
	"\ais_temp\x18\a \x01(\x05R\x06isTemp\x12\x1f\n" +
	"\vexpire_time\x18\b \x01(\x03R\n" +
	"expireTime\"\xb1\x01\n" +
	"\x0eUploadResponse\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\x12!\n" +
	"\fstorage_path\x18\x02 \x01(\tR\vstoragePath\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x14\n" +
	"\x05width\x18\x04 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x05 \x01(\x05R\x06height\x12\x1b\n" +
	"\tfrom_hash\x18\x06 \x01(\bR\bfromHash\"5\n" +
	"\x12GetResourceRequest\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\"E\n" +
	"\x13GetResourceResponse\x12.\n" +
	"\bresource\x18\x01 \x01(\v2\x12.resource.ResourceR\bresource\"Y\n" +
	"\x15DeleteResourceRequest\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\tR\n" +
	"resourceId\x12\x1f\n" +
	"\vuploader_id\x18\x02 \x01(\x03R\n" +
	"uploaderId\"\x18\n" +
	"\x16DeleteResourceResponse\"P\n" +
	"\x10GetByHashRequest\x12\x1b\n" +
	"\tfile_hash\x18\x01 \x01(\tR\bfileHash\x12\x1f\n" +
	"\vuploader_id\x18\x02 \x01(\x03R\n" +
	"uploaderId\"^\n" +
	"\x11GetByHashResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\x12\x1f\n" +
	"\vresource_id\x18\x02 \x01(\tR\n" +
	"resourceId\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\"\x19\n" +
	"\x17CleanExpiredTempRequest\"?\n" +
	"\x18CleanExpiredTempResponse\x12#\n" +
	"\rdeleted_count\x18\x01 \x01(\x05R\fdeletedCount2\x90\x03\n" +
	"\x0fResourceService\x12;\n" +
	"\x06Upload\x12\x17.resource.UploadRequest\x1a\x18.resource.UploadResponse\x12J\n" +
	"\vGetResource\x12\x1c.resource.GetResourceRequest\x1a\x1d.resource.GetResourceResponse\x12S\n" +
	"\x0eDeleteResource\x12\x1f.resource.DeleteResourceRequest\x1a .resource.DeleteResourceResponse\x12D\n" +
	"\tGetByHash\x12\x1a.resource.GetByHashRequest\x1a\x1b.resource.GetByHashResponse\x12Y\n" +
	"\x10CleanExpiredTemp\x12!.resource.CleanExpiredTempRequest\x1a\".resource.CleanExpiredTempResponseB\x16Z\x14services/resource/pbb\x06proto3"

var (
	file_beehive_m_resource_proto_rawDescOnce sync.Once
	file_beehive_m_resource_proto_rawDescData []byte
)

func file_beehive_m_resource_proto_rawDescGZIP() []byte {
	file_beehive_m_resource_proto_rawDescOnce.Do(func() {
		file_beehive_m_resource_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_beehive_m_resource_proto_rawDesc), len(file_beehive_m_resource_proto_rawDesc)))
	})
	return file_beehive_m_resource_proto_rawDescData
}

var file_beehive_m_resource_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_beehive_m_resource_proto_goTypes = []any{
	(*Resource)(nil),                 // 0: resource.Resource
	(*UploadRequest)(nil),            // 1: resource.UploadRequest
	(*UploadResponse)(nil),           // 2: resource.UploadResponse
	(*GetResourceRequest)(nil),       // 3: resource.GetResourceRequest
	(*GetResourceResponse)(nil),      // 4: resource.GetResourceResponse
	(*DeleteResourceRequest)(nil),    // 5: resource.DeleteResourceRequest
	(*DeleteResourceResponse)(nil),   // 6: resource.DeleteResourceResponse
	(*GetByHashRequest)(nil),         // 7: resource.GetByHashRequest
	(*GetByHashResponse)(nil),        // 8: resource.GetByHashResponse
	(*CleanExpiredTempRequest)(nil),  // 9: resource.CleanExpiredTempRequest
	(*CleanExpiredTempResponse)(nil), // 10: resource.CleanExpiredTempResponse
}
var file_beehive_m_resource_proto_depIdxs = []int32{
	0,  // 0: resource.GetResourceResponse.resource:type_name -> resource.Resource
	1,  // 1: resource.ResourceService.Upload:input_type -> resource.UploadRequest
	3,  // 2: resource.ResourceService.GetResource:input_type -> resource.GetResourceRequest
	5,  // 3: resource.ResourceService.DeleteResource:input_type -> resource.DeleteResourceRequest
	7,  // 4: resource.ResourceService.GetByHash:input_type -> resource.GetByHashRequest
	9,  // 5: resource.ResourceService.CleanExpiredTemp:input_type -> resource.CleanExpiredTempRequest
	2,  // 6: resource.ResourceService.Upload:output_type -> resource.UploadResponse
	4,  // 7: resource.ResourceService.GetResource:output_type -> resource.GetResourceResponse
	6,  // 8: resource.ResourceService.DeleteResource:output_type -> resource.DeleteResourceResponse
	8,  // 9: resource.ResourceService.GetByHash:output_type -> resource.GetByHashResponse
	10, // 10: resource.ResourceService.CleanExpiredTemp:output_type -> resource.CleanExpiredTempResponse
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_beehive_m_resource_proto_init() }
func file_beehive_m_resource_proto_init() {
	if File_beehive_m_resource_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_beehive_m_resource_proto_rawDesc), len(file_beehive_m_resource_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_beehive_m_resource_proto_goTypes,
		DependencyIndexes: file_beehive_m_resource_proto_depIdxs,
		MessageInfos:      file_beehive_m_resource_proto_msgTypes,
	}.Build()
	File_beehive_m_resource_proto = out.File
	file_beehive_m_resource_proto_goTypes = nil
	file_beehive_m_resource_proto_depIdxs = nil
}
