// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: message.proto

package server

import (
	"context"

	"github.com/HappyLadySauce/Beehive-M/services/message/internal/logic/messageservice"
	"github.com/HappyLadySauce/Beehive-M/services/message/internal/svc"
	"github.com/HappyLadySauce/Beehive-M/services/message/pb"
)

type MessageServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedMessageServiceServer
}

func NewMessageServiceServer(svcCtx *svc.ServiceContext) *MessageServiceServer {
	return &MessageServiceServer{
		svcCtx: svcCtx,
	}
}

// 私聊
func (s *MessageServiceServer) SendPrivateMessage(ctx context.Context, in *pb.SendPrivateMessageRequest) (*pb.SendPrivateMessageResponse, error) {
	l := messageservicelogic.NewSendPrivateMessageLogic(ctx, s.svcCtx)
	return l.SendPrivateMessage(in)
}

func (s *MessageServiceServer) ListPrivateMessages(ctx context.Context, in *pb.ListPrivateMessagesRequest) (*pb.ListPrivateMessagesResponse, error) {
	l := messageservicelogic.NewListPrivateMessagesLogic(ctx, s.svcCtx)
	return l.ListPrivateMessages(in)
}

func (s *MessageServiceServer) MarkPrivateRead(ctx context.Context, in *pb.MarkPrivateReadRequest) (*pb.MarkPrivateReadResponse, error) {
	l := messageservicelogic.NewMarkPrivateReadLogic(ctx, s.svcCtx)
	return l.MarkPrivateRead(in)
}

func (s *MessageServiceServer) GetPrivateUnreadCount(ctx context.Context, in *pb.GetPrivateUnreadCountRequest) (*pb.GetPrivateUnreadCountResponse, error) {
	l := messageservicelogic.NewGetPrivateUnreadCountLogic(ctx, s.svcCtx)
	return l.GetPrivateUnreadCount(in)
}

// 群聊
func (s *MessageServiceServer) SendGroupMessage(ctx context.Context, in *pb.SendGroupMessageRequest) (*pb.SendGroupMessageResponse, error) {
	l := messageservicelogic.NewSendGroupMessageLogic(ctx, s.svcCtx)
	return l.SendGroupMessage(in)
}

func (s *MessageServiceServer) ListGroupMessages(ctx context.Context, in *pb.ListGroupMessagesRequest) (*pb.ListGroupMessagesResponse, error) {
	l := messageservicelogic.NewListGroupMessagesLogic(ctx, s.svcCtx)
	return l.ListGroupMessages(in)
}

func (s *MessageServiceServer) MarkGroupRead(ctx context.Context, in *pb.MarkGroupReadRequest) (*pb.MarkGroupReadResponse, error) {
	l := messageservicelogic.NewMarkGroupReadLogic(ctx, s.svcCtx)
	return l.MarkGroupRead(in)
}

func (s *MessageServiceServer) GetGroupUnreadCount(ctx context.Context, in *pb.GetGroupUnreadCountRequest) (*pb.GetGroupUnreadCountResponse, error) {
	l := messageservicelogic.NewGetGroupUnreadCountLogic(ctx, s.svcCtx)
	return l.GetGroupUnreadCount(in)
}

// 通用
func (s *MessageServiceServer) RecallMessage(ctx context.Context, in *pb.RecallMessageRequest) (*pb.RecallMessageResponse, error) {
	l := messageservicelogic.NewRecallMessageLogic(ctx, s.svcCtx)
	return l.RecallMessage(in)
}

func (s *MessageServiceServer) GetMessage(ctx context.Context, in *pb.GetMessageRequest) (*pb.GetMessageResponse, error) {
	l := messageservicelogic.NewGetMessageLogic(ctx, s.svcCtx)
	return l.GetMessage(in)
}

func (s *MessageServiceServer) ListMessageReferences(ctx context.Context, in *pb.ListMessageReferencesRequest) (*pb.ListMessageReferencesResponse, error) {
	l := messageservicelogic.NewListMessageReferencesLogic(ctx, s.svcCtx)
	return l.ListMessageReferences(in)
}

// 会话
func (s *MessageServiceServer) ListConversations(ctx context.Context, in *pb.ListConversationsRequest) (*pb.ListConversationsResponse, error) {
	l := messageservicelogic.NewListConversationsLogic(ctx, s.svcCtx)
	return l.ListConversations(in)
}

func (s *MessageServiceServer) SetConversationPin(ctx context.Context, in *pb.SetConversationPinRequest) (*pb.SetConversationPinResponse, error) {
	l := messageservicelogic.NewSetConversationPinLogic(ctx, s.svcCtx)
	return l.SetConversationPin(in)
}

func (s *MessageServiceServer) SetConversationMute(ctx context.Context, in *pb.SetConversationMuteRequest) (*pb.SetConversationMuteResponse, error) {
	l := messageservicelogic.NewSetConversationMuteLogic(ctx, s.svcCtx)
	return l.SetConversationMute(in)
}

func (s *MessageServiceServer) GetOrCreateConversation(ctx context.Context, in *pb.GetOrCreateConversationRequest) (*pb.GetOrCreateConversationResponse, error) {
	l := messageservicelogic.NewGetOrCreateConversationLogic(ctx, s.svcCtx)
	return l.GetOrCreateConversation(in)
}

// 同步
func (s *MessageServiceServer) GetSyncCursor(ctx context.Context, in *pb.GetSyncCursorRequest) (*pb.GetSyncCursorResponse, error) {
	l := messageservicelogic.NewGetSyncCursorLogic(ctx, s.svcCtx)
	return l.GetSyncCursor(in)
}

func (s *MessageServiceServer) PullMessages(ctx context.Context, in *pb.PullMessagesRequest) (*pb.PullMessagesResponse, error) {
	l := messageservicelogic.NewPullMessagesLogic(ctx, s.svcCtx)
	return l.PullMessages(in)
}
