// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: friend.proto

package friendservice

import (
	"context"

	"github.com/HappyLadySauce/Beehive-M/services/friend/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddBlacklistRequest          = pb.AddBlacklistRequest
	AddBlacklistResponse         = pb.AddBlacklistResponse
	BlacklistItem                = pb.BlacklistItem
	CheckBlacklistRequest        = pb.CheckBlacklistRequest
	CheckBlacklistResponse       = pb.CheckBlacklistResponse
	DeleteFriendRequest          = pb.DeleteFriendRequest
	DeleteFriendResponse         = pb.DeleteFriendResponse
	FriendItem                   = pb.FriendItem
	FriendRequestItem            = pb.FriendRequestItem
	HandleFriendRequestRequest   = pb.HandleFriendRequestRequest
	HandleFriendRequestResponse  = pb.HandleFriendRequestResponse
	IgnoreRecommendationRequest  = pb.IgnoreRecommendationRequest
	IgnoreRecommendationResponse = pb.IgnoreRecommendationResponse
	ListBlacklistRequest         = pb.ListBlacklistRequest
	ListBlacklistResponse        = pb.ListBlacklistResponse
	ListFriendsRequest           = pb.ListFriendsRequest
	ListFriendsResponse          = pb.ListFriendsResponse
	ListReceivedRequestsRequest  = pb.ListReceivedRequestsRequest
	ListReceivedRequestsResponse = pb.ListReceivedRequestsResponse
	ListRecommendationsRequest   = pb.ListRecommendationsRequest
	ListRecommendationsResponse  = pb.ListRecommendationsResponse
	ListSentRequestsRequest      = pb.ListSentRequestsRequest
	ListSentRequestsResponse     = pb.ListSentRequestsResponse
	RecommendationItem           = pb.RecommendationItem
	RemoveBlacklistRequest       = pb.RemoveBlacklistRequest
	RemoveBlacklistResponse      = pb.RemoveBlacklistResponse
	SendFriendRequestRequest     = pb.SendFriendRequestRequest
	SendFriendRequestResponse    = pb.SendFriendRequestResponse
	SetFriendMutedRequest        = pb.SetFriendMutedRequest
	SetFriendMutedResponse       = pb.SetFriendMutedResponse
	SetFriendSpecialRequest      = pb.SetFriendSpecialRequest
	SetFriendSpecialResponse     = pb.SetFriendSpecialResponse
	UpdateRemarkRequest          = pb.UpdateRemarkRequest
	UpdateRemarkResponse         = pb.UpdateRemarkResponse

	FriendService interface {
		// 好友
		ListFriends(ctx context.Context, in *ListFriendsRequest, opts ...grpc.CallOption) (*ListFriendsResponse, error)
		DeleteFriend(ctx context.Context, in *DeleteFriendRequest, opts ...grpc.CallOption) (*DeleteFriendResponse, error)
		UpdateRemark(ctx context.Context, in *UpdateRemarkRequest, opts ...grpc.CallOption) (*UpdateRemarkResponse, error)
		SetFriendMuted(ctx context.Context, in *SetFriendMutedRequest, opts ...grpc.CallOption) (*SetFriendMutedResponse, error)
		SetFriendSpecial(ctx context.Context, in *SetFriendSpecialRequest, opts ...grpc.CallOption) (*SetFriendSpecialResponse, error)
		// 申请
		SendFriendRequest(ctx context.Context, in *SendFriendRequestRequest, opts ...grpc.CallOption) (*SendFriendRequestResponse, error)
		ListReceivedRequests(ctx context.Context, in *ListReceivedRequestsRequest, opts ...grpc.CallOption) (*ListReceivedRequestsResponse, error)
		ListSentRequests(ctx context.Context, in *ListSentRequestsRequest, opts ...grpc.CallOption) (*ListSentRequestsResponse, error)
		HandleFriendRequest(ctx context.Context, in *HandleFriendRequestRequest, opts ...grpc.CallOption) (*HandleFriendRequestResponse, error)
		// 黑名单
		AddBlacklist(ctx context.Context, in *AddBlacklistRequest, opts ...grpc.CallOption) (*AddBlacklistResponse, error)
		RemoveBlacklist(ctx context.Context, in *RemoveBlacklistRequest, opts ...grpc.CallOption) (*RemoveBlacklistResponse, error)
		ListBlacklist(ctx context.Context, in *ListBlacklistRequest, opts ...grpc.CallOption) (*ListBlacklistResponse, error)
		CheckBlacklist(ctx context.Context, in *CheckBlacklistRequest, opts ...grpc.CallOption) (*CheckBlacklistResponse, error)
		// 推荐
		ListRecommendations(ctx context.Context, in *ListRecommendationsRequest, opts ...grpc.CallOption) (*ListRecommendationsResponse, error)
		IgnoreRecommendation(ctx context.Context, in *IgnoreRecommendationRequest, opts ...grpc.CallOption) (*IgnoreRecommendationResponse, error)
	}

	defaultFriendService struct {
		cli zrpc.Client
	}
)

func NewFriendService(cli zrpc.Client) FriendService {
	return &defaultFriendService{
		cli: cli,
	}
}

// 好友
func (m *defaultFriendService) ListFriends(ctx context.Context, in *ListFriendsRequest, opts ...grpc.CallOption) (*ListFriendsResponse, error) {
	client := pb.NewFriendServiceClient(m.cli.Conn())
	return client.ListFriends(ctx, in, opts...)
}

func (m *defaultFriendService) DeleteFriend(ctx context.Context, in *DeleteFriendRequest, opts ...grpc.CallOption) (*DeleteFriendResponse, error) {
	client := pb.NewFriendServiceClient(m.cli.Conn())
	return client.DeleteFriend(ctx, in, opts...)
}

func (m *defaultFriendService) UpdateRemark(ctx context.Context, in *UpdateRemarkRequest, opts ...grpc.CallOption) (*UpdateRemarkResponse, error) {
	client := pb.NewFriendServiceClient(m.cli.Conn())
	return client.UpdateRemark(ctx, in, opts...)
}

func (m *defaultFriendService) SetFriendMuted(ctx context.Context, in *SetFriendMutedRequest, opts ...grpc.CallOption) (*SetFriendMutedResponse, error) {
	client := pb.NewFriendServiceClient(m.cli.Conn())
	return client.SetFriendMuted(ctx, in, opts...)
}

func (m *defaultFriendService) SetFriendSpecial(ctx context.Context, in *SetFriendSpecialRequest, opts ...grpc.CallOption) (*SetFriendSpecialResponse, error) {
	client := pb.NewFriendServiceClient(m.cli.Conn())
	return client.SetFriendSpecial(ctx, in, opts...)
}

// 申请
func (m *defaultFriendService) SendFriendRequest(ctx context.Context, in *SendFriendRequestRequest, opts ...grpc.CallOption) (*SendFriendRequestResponse, error) {
	client := pb.NewFriendServiceClient(m.cli.Conn())
	return client.SendFriendRequest(ctx, in, opts...)
}

func (m *defaultFriendService) ListReceivedRequests(ctx context.Context, in *ListReceivedRequestsRequest, opts ...grpc.CallOption) (*ListReceivedRequestsResponse, error) {
	client := pb.NewFriendServiceClient(m.cli.Conn())
	return client.ListReceivedRequests(ctx, in, opts...)
}

func (m *defaultFriendService) ListSentRequests(ctx context.Context, in *ListSentRequestsRequest, opts ...grpc.CallOption) (*ListSentRequestsResponse, error) {
	client := pb.NewFriendServiceClient(m.cli.Conn())
	return client.ListSentRequests(ctx, in, opts...)
}

func (m *defaultFriendService) HandleFriendRequest(ctx context.Context, in *HandleFriendRequestRequest, opts ...grpc.CallOption) (*HandleFriendRequestResponse, error) {
	client := pb.NewFriendServiceClient(m.cli.Conn())
	return client.HandleFriendRequest(ctx, in, opts...)
}

// 黑名单
func (m *defaultFriendService) AddBlacklist(ctx context.Context, in *AddBlacklistRequest, opts ...grpc.CallOption) (*AddBlacklistResponse, error) {
	client := pb.NewFriendServiceClient(m.cli.Conn())
	return client.AddBlacklist(ctx, in, opts...)
}

func (m *defaultFriendService) RemoveBlacklist(ctx context.Context, in *RemoveBlacklistRequest, opts ...grpc.CallOption) (*RemoveBlacklistResponse, error) {
	client := pb.NewFriendServiceClient(m.cli.Conn())
	return client.RemoveBlacklist(ctx, in, opts...)
}

func (m *defaultFriendService) ListBlacklist(ctx context.Context, in *ListBlacklistRequest, opts ...grpc.CallOption) (*ListBlacklistResponse, error) {
	client := pb.NewFriendServiceClient(m.cli.Conn())
	return client.ListBlacklist(ctx, in, opts...)
}

func (m *defaultFriendService) CheckBlacklist(ctx context.Context, in *CheckBlacklistRequest, opts ...grpc.CallOption) (*CheckBlacklistResponse, error) {
	client := pb.NewFriendServiceClient(m.cli.Conn())
	return client.CheckBlacklist(ctx, in, opts...)
}

// 推荐
func (m *defaultFriendService) ListRecommendations(ctx context.Context, in *ListRecommendationsRequest, opts ...grpc.CallOption) (*ListRecommendationsResponse, error) {
	client := pb.NewFriendServiceClient(m.cli.Conn())
	return client.ListRecommendations(ctx, in, opts...)
}

func (m *defaultFriendService) IgnoreRecommendation(ctx context.Context, in *IgnoreRecommendationRequest, opts ...grpc.CallOption) (*IgnoreRecommendationResponse, error) {
	client := pb.NewFriendServiceClient(m.cli.Conn())
	return client.IgnoreRecommendation(ctx, in, opts...)
}
