// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	gateway "github.com/HappyLadySauce/Beehive-M/services/gateway/internal/handler/gateway"
	"github.com/HappyLadySauce/Beehive-M/services/gateway/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/healthz",
				Handler: gateway.HealthHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/ws",
				Handler: gateway.WsEntryHandler(serverCtx),
			},
		},
	)
}
