// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: presence.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OnlineStatus struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId        string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Status          int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`                          // 0离线 1在线 2忙碌 3离开
	DeviceType      string                 `protobuf:"bytes,4,opt,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"` // web/android/ios
	ClientIp        string                 `protobuf:"bytes,5,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	LastHeartbeatAt int64                  `protobuf:"varint,6,opt,name=last_heartbeat_at,json=lastHeartbeatAt,proto3" json:"last_heartbeat_at,omitempty"`
	UpdateTime      int64                  `protobuf:"varint,7,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OnlineStatus) Reset() {
	*x = OnlineStatus{}
	mi := &file_presence_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnlineStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineStatus) ProtoMessage() {}

func (x *OnlineStatus) ProtoReflect() protoreflect.Message {
	mi := &file_presence_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineStatus.ProtoReflect.Descriptor instead.
func (*OnlineStatus) Descriptor() ([]byte, []int) {
	return file_presence_proto_rawDescGZIP(), []int{0}
}

func (x *OnlineStatus) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OnlineStatus) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *OnlineStatus) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *OnlineStatus) GetDeviceType() string {
	if x != nil {
		return x.DeviceType
	}
	return ""
}

func (x *OnlineStatus) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *OnlineStatus) GetLastHeartbeatAt() int64 {
	if x != nil {
		return x.LastHeartbeatAt
	}
	return 0
}

func (x *OnlineStatus) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

type ReportHeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`       // 可选，多端时区分
	DeviceType    string                 `protobuf:"bytes,3,opt,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"` // web/android/ios
	ClientIp      string                 `protobuf:"bytes,4,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`       // 可选
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportHeartbeatRequest) Reset() {
	*x = ReportHeartbeatRequest{}
	mi := &file_presence_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportHeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportHeartbeatRequest) ProtoMessage() {}

func (x *ReportHeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_presence_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportHeartbeatRequest.ProtoReflect.Descriptor instead.
func (*ReportHeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_presence_proto_rawDescGZIP(), []int{1}
}

func (x *ReportHeartbeatRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ReportHeartbeatRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *ReportHeartbeatRequest) GetDeviceType() string {
	if x != nil {
		return x.DeviceType
	}
	return ""
}

func (x *ReportHeartbeatRequest) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

type ReportHeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportHeartbeatResponse) Reset() {
	*x = ReportHeartbeatResponse{}
	mi := &file_presence_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportHeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportHeartbeatResponse) ProtoMessage() {}

func (x *ReportHeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_presence_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportHeartbeatResponse.ProtoReflect.Descriptor instead.
func (*ReportHeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_presence_proto_rawDescGZIP(), []int{2}
}

type GetOnlineStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"` // 空表示获取该用户全部设备状态
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOnlineStatusRequest) Reset() {
	*x = GetOnlineStatusRequest{}
	mi := &file_presence_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOnlineStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOnlineStatusRequest) ProtoMessage() {}

func (x *GetOnlineStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_presence_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOnlineStatusRequest.ProtoReflect.Descriptor instead.
func (*GetOnlineStatusRequest) Descriptor() ([]byte, []int) {
	return file_presence_proto_rawDescGZIP(), []int{3}
}

func (x *GetOnlineStatusRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetOnlineStatusRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type GetOnlineStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Statuses      []*OnlineStatus        `protobuf:"bytes,1,rep,name=statuses,proto3" json:"statuses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOnlineStatusResponse) Reset() {
	*x = GetOnlineStatusResponse{}
	mi := &file_presence_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOnlineStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOnlineStatusResponse) ProtoMessage() {}

func (x *GetOnlineStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_presence_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOnlineStatusResponse.ProtoReflect.Descriptor instead.
func (*GetOnlineStatusResponse) Descriptor() ([]byte, []int) {
	return file_presence_proto_rawDescGZIP(), []int{4}
}

func (x *GetOnlineStatusResponse) GetStatuses() []*OnlineStatus {
	if x != nil {
		return x.Statuses
	}
	return nil
}

type BatchGetOnlineStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []int64                `protobuf:"varint,1,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetOnlineStatusRequest) Reset() {
	*x = BatchGetOnlineStatusRequest{}
	mi := &file_presence_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetOnlineStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetOnlineStatusRequest) ProtoMessage() {}

func (x *BatchGetOnlineStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_presence_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetOnlineStatusRequest.ProtoReflect.Descriptor instead.
func (*BatchGetOnlineStatusRequest) Descriptor() ([]byte, []int) {
	return file_presence_proto_rawDescGZIP(), []int{5}
}

func (x *BatchGetOnlineStatusRequest) GetUserIds() []int64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type BatchGetOnlineStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Statuses      []*OnlineStatus        `protobuf:"bytes,1,rep,name=statuses,proto3" json:"statuses,omitempty"` // 未在线的可不返回或 status=0
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetOnlineStatusResponse) Reset() {
	*x = BatchGetOnlineStatusResponse{}
	mi := &file_presence_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetOnlineStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetOnlineStatusResponse) ProtoMessage() {}

func (x *BatchGetOnlineStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_presence_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetOnlineStatusResponse.ProtoReflect.Descriptor instead.
func (*BatchGetOnlineStatusResponse) Descriptor() ([]byte, []int) {
	return file_presence_proto_rawDescGZIP(), []int{6}
}

func (x *BatchGetOnlineStatusResponse) GetStatuses() []*OnlineStatus {
	if x != nil {
		return x.Statuses
	}
	return nil
}

type KickDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"` // 空表示踢该用户全部设备
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickDeviceRequest) Reset() {
	*x = KickDeviceRequest{}
	mi := &file_presence_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickDeviceRequest) ProtoMessage() {}

func (x *KickDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_presence_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickDeviceRequest.ProtoReflect.Descriptor instead.
func (*KickDeviceRequest) Descriptor() ([]byte, []int) {
	return file_presence_proto_rawDescGZIP(), []int{7}
}

func (x *KickDeviceRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *KickDeviceRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type KickDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KickDeviceResponse) Reset() {
	*x = KickDeviceResponse{}
	mi := &file_presence_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KickDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KickDeviceResponse) ProtoMessage() {}

func (x *KickDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_presence_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KickDeviceResponse.ProtoReflect.Descriptor instead.
func (*KickDeviceResponse) Descriptor() ([]byte, []int) {
	return file_presence_proto_rawDescGZIP(), []int{8}
}

var File_presence_proto protoreflect.FileDescriptor

const file_presence_proto_rawDesc = "" +
	"\n" +
	"\x0epresence.proto\x12\bpresence\"\xe7\x01\n" +
	"\fOnlineStatus\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x12\x1f\n" +
	"\vdevice_type\x18\x04 \x01(\tR\n" +
	"deviceType\x12\x1b\n" +
	"\tclient_ip\x18\x05 \x01(\tR\bclientIp\x12*\n" +
	"\x11last_heartbeat_at\x18\x06 \x01(\x03R\x0flastHeartbeatAt\x12\x1f\n" +
	"\vupdate_time\x18\a \x01(\x03R\n" +
	"updateTime\"\x8c\x01\n" +
	"\x16ReportHeartbeatRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x1f\n" +
	"\vdevice_type\x18\x03 \x01(\tR\n" +
	"deviceType\x12\x1b\n" +
	"\tclient_ip\x18\x04 \x01(\tR\bclientIp\"\x19\n" +
	"\x17ReportHeartbeatResponse\"N\n" +
	"\x16GetOnlineStatusRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\"M\n" +
	"\x17GetOnlineStatusResponse\x122\n" +
	"\bstatuses\x18\x01 \x03(\v2\x16.presence.OnlineStatusR\bstatuses\"8\n" +
	"\x1bBatchGetOnlineStatusRequest\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\x03R\auserIds\"R\n" +
	"\x1cBatchGetOnlineStatusResponse\x122\n" +
	"\bstatuses\x18\x01 \x03(\v2\x16.presence.OnlineStatusR\bstatuses\"I\n" +
	"\x11KickDeviceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\"\x14\n" +
	"\x12KickDeviceResponse2\xf1\x02\n" +
	"\x0fPresenceService\x12V\n" +
	"\x0fReportHeartbeat\x12 .presence.ReportHeartbeatRequest\x1a!.presence.ReportHeartbeatResponse\x12V\n" +
	"\x0fGetOnlineStatus\x12 .presence.GetOnlineStatusRequest\x1a!.presence.GetOnlineStatusResponse\x12e\n" +
	"\x14BatchGetOnlineStatus\x12%.presence.BatchGetOnlineStatusRequest\x1a&.presence.BatchGetOnlineStatusResponse\x12G\n" +
	"\n" +
	"KickDevice\x12\x1b.presence.KickDeviceRequest\x1a\x1c.presence.KickDeviceResponseB\x16Z\x14services/presence/pbb\x06proto3"

var (
	file_presence_proto_rawDescOnce sync.Once
	file_presence_proto_rawDescData []byte
)

func file_presence_proto_rawDescGZIP() []byte {
	file_presence_proto_rawDescOnce.Do(func() {
		file_presence_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_presence_proto_rawDesc), len(file_presence_proto_rawDesc)))
	})
	return file_presence_proto_rawDescData
}

var file_presence_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_presence_proto_goTypes = []any{
	(*OnlineStatus)(nil),                 // 0: presence.OnlineStatus
	(*ReportHeartbeatRequest)(nil),       // 1: presence.ReportHeartbeatRequest
	(*ReportHeartbeatResponse)(nil),      // 2: presence.ReportHeartbeatResponse
	(*GetOnlineStatusRequest)(nil),       // 3: presence.GetOnlineStatusRequest
	(*GetOnlineStatusResponse)(nil),      // 4: presence.GetOnlineStatusResponse
	(*BatchGetOnlineStatusRequest)(nil),  // 5: presence.BatchGetOnlineStatusRequest
	(*BatchGetOnlineStatusResponse)(nil), // 6: presence.BatchGetOnlineStatusResponse
	(*KickDeviceRequest)(nil),            // 7: presence.KickDeviceRequest
	(*KickDeviceResponse)(nil),           // 8: presence.KickDeviceResponse
}
var file_presence_proto_depIdxs = []int32{
	0, // 0: presence.GetOnlineStatusResponse.statuses:type_name -> presence.OnlineStatus
	0, // 1: presence.BatchGetOnlineStatusResponse.statuses:type_name -> presence.OnlineStatus
	1, // 2: presence.PresenceService.ReportHeartbeat:input_type -> presence.ReportHeartbeatRequest
	3, // 3: presence.PresenceService.GetOnlineStatus:input_type -> presence.GetOnlineStatusRequest
	5, // 4: presence.PresenceService.BatchGetOnlineStatus:input_type -> presence.BatchGetOnlineStatusRequest
	7, // 5: presence.PresenceService.KickDevice:input_type -> presence.KickDeviceRequest
	2, // 6: presence.PresenceService.ReportHeartbeat:output_type -> presence.ReportHeartbeatResponse
	4, // 7: presence.PresenceService.GetOnlineStatus:output_type -> presence.GetOnlineStatusResponse
	6, // 8: presence.PresenceService.BatchGetOnlineStatus:output_type -> presence.BatchGetOnlineStatusResponse
	8, // 9: presence.PresenceService.KickDevice:output_type -> presence.KickDeviceResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_presence_proto_init() }
func file_presence_proto_init() {
	if File_presence_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_presence_proto_rawDesc), len(file_presence_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_presence_proto_goTypes,
		DependencyIndexes: file_presence_proto_depIdxs,
		MessageInfos:      file_presence_proto_msgTypes,
	}.Build()
	File_presence_proto = out.File
	file_presence_proto_goTypes = nil
	file_presence_proto_depIdxs = nil
}
