// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.4
// source: presence.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PresenceService_ReportHeartbeat_FullMethodName      = "/presence.PresenceService/ReportHeartbeat"
	PresenceService_GetOnlineStatus_FullMethodName      = "/presence.PresenceService/GetOnlineStatus"
	PresenceService_BatchGetOnlineStatus_FullMethodName = "/presence.PresenceService/BatchGetOnlineStatus"
	PresenceService_KickDevice_FullMethodName           = "/presence.PresenceService/KickDevice"
)

// PresenceServiceClient is the client API for PresenceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PresenceService 在线状态、心跳、踢下线
type PresenceServiceClient interface {
	ReportHeartbeat(ctx context.Context, in *ReportHeartbeatRequest, opts ...grpc.CallOption) (*ReportHeartbeatResponse, error)
	GetOnlineStatus(ctx context.Context, in *GetOnlineStatusRequest, opts ...grpc.CallOption) (*GetOnlineStatusResponse, error)
	BatchGetOnlineStatus(ctx context.Context, in *BatchGetOnlineStatusRequest, opts ...grpc.CallOption) (*BatchGetOnlineStatusResponse, error)
	KickDevice(ctx context.Context, in *KickDeviceRequest, opts ...grpc.CallOption) (*KickDeviceResponse, error)
}

type presenceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPresenceServiceClient(cc grpc.ClientConnInterface) PresenceServiceClient {
	return &presenceServiceClient{cc}
}

func (c *presenceServiceClient) ReportHeartbeat(ctx context.Context, in *ReportHeartbeatRequest, opts ...grpc.CallOption) (*ReportHeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportHeartbeatResponse)
	err := c.cc.Invoke(ctx, PresenceService_ReportHeartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *presenceServiceClient) GetOnlineStatus(ctx context.Context, in *GetOnlineStatusRequest, opts ...grpc.CallOption) (*GetOnlineStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOnlineStatusResponse)
	err := c.cc.Invoke(ctx, PresenceService_GetOnlineStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *presenceServiceClient) BatchGetOnlineStatus(ctx context.Context, in *BatchGetOnlineStatusRequest, opts ...grpc.CallOption) (*BatchGetOnlineStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchGetOnlineStatusResponse)
	err := c.cc.Invoke(ctx, PresenceService_BatchGetOnlineStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *presenceServiceClient) KickDevice(ctx context.Context, in *KickDeviceRequest, opts ...grpc.CallOption) (*KickDeviceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KickDeviceResponse)
	err := c.cc.Invoke(ctx, PresenceService_KickDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PresenceServiceServer is the server API for PresenceService service.
// All implementations must embed UnimplementedPresenceServiceServer
// for forward compatibility.
//
// PresenceService 在线状态、心跳、踢下线
type PresenceServiceServer interface {
	ReportHeartbeat(context.Context, *ReportHeartbeatRequest) (*ReportHeartbeatResponse, error)
	GetOnlineStatus(context.Context, *GetOnlineStatusRequest) (*GetOnlineStatusResponse, error)
	BatchGetOnlineStatus(context.Context, *BatchGetOnlineStatusRequest) (*BatchGetOnlineStatusResponse, error)
	KickDevice(context.Context, *KickDeviceRequest) (*KickDeviceResponse, error)
	mustEmbedUnimplementedPresenceServiceServer()
}

// UnimplementedPresenceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPresenceServiceServer struct{}

func (UnimplementedPresenceServiceServer) ReportHeartbeat(context.Context, *ReportHeartbeatRequest) (*ReportHeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportHeartbeat not implemented")
}
func (UnimplementedPresenceServiceServer) GetOnlineStatus(context.Context, *GetOnlineStatusRequest) (*GetOnlineStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOnlineStatus not implemented")
}
func (UnimplementedPresenceServiceServer) BatchGetOnlineStatus(context.Context, *BatchGetOnlineStatusRequest) (*BatchGetOnlineStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchGetOnlineStatus not implemented")
}
func (UnimplementedPresenceServiceServer) KickDevice(context.Context, *KickDeviceRequest) (*KickDeviceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method KickDevice not implemented")
}
func (UnimplementedPresenceServiceServer) mustEmbedUnimplementedPresenceServiceServer() {}
func (UnimplementedPresenceServiceServer) testEmbeddedByValue()                         {}

// UnsafePresenceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PresenceServiceServer will
// result in compilation errors.
type UnsafePresenceServiceServer interface {
	mustEmbedUnimplementedPresenceServiceServer()
}

func RegisterPresenceServiceServer(s grpc.ServiceRegistrar, srv PresenceServiceServer) {
	// If the following call panics, it indicates UnimplementedPresenceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PresenceService_ServiceDesc, srv)
}

func _PresenceService_ReportHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportHeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PresenceServiceServer).ReportHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PresenceService_ReportHeartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PresenceServiceServer).ReportHeartbeat(ctx, req.(*ReportHeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PresenceService_GetOnlineStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOnlineStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PresenceServiceServer).GetOnlineStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PresenceService_GetOnlineStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PresenceServiceServer).GetOnlineStatus(ctx, req.(*GetOnlineStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PresenceService_BatchGetOnlineStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchGetOnlineStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PresenceServiceServer).BatchGetOnlineStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PresenceService_BatchGetOnlineStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PresenceServiceServer).BatchGetOnlineStatus(ctx, req.(*BatchGetOnlineStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PresenceService_KickDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KickDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PresenceServiceServer).KickDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PresenceService_KickDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PresenceServiceServer).KickDevice(ctx, req.(*KickDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PresenceService_ServiceDesc is the grpc.ServiceDesc for PresenceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PresenceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "presence.PresenceService",
	HandlerType: (*PresenceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportHeartbeat",
			Handler:    _PresenceService_ReportHeartbeat_Handler,
		},
		{
			MethodName: "GetOnlineStatus",
			Handler:    _PresenceService_GetOnlineStatus_Handler,
		},
		{
			MethodName: "BatchGetOnlineStatus",
			Handler:    _PresenceService_BatchGetOnlineStatus_Handler,
		},
		{
			MethodName: "KickDevice",
			Handler:    _PresenceService_KickDevice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "presence.proto",
}
