// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: presence.proto

package server

import (
	"context"

	"github.com/HappyLadySauce/Beehive-M/services/presence/internal/logic/presenceservice"
	"github.com/HappyLadySauce/Beehive-M/services/presence/internal/svc"
	"github.com/HappyLadySauce/Beehive-M/services/presence/pb"
)

type PresenceServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedPresenceServiceServer
}

func NewPresenceServiceServer(svcCtx *svc.ServiceContext) *PresenceServiceServer {
	return &PresenceServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *PresenceServiceServer) ReportHeartbeat(ctx context.Context, in *pb.ReportHeartbeatRequest) (*pb.ReportHeartbeatResponse, error) {
	l := presenceservicelogic.NewReportHeartbeatLogic(ctx, s.svcCtx)
	return l.ReportHeartbeat(in)
}

func (s *PresenceServiceServer) GetOnlineStatus(ctx context.Context, in *pb.GetOnlineStatusRequest) (*pb.GetOnlineStatusResponse, error) {
	l := presenceservicelogic.NewGetOnlineStatusLogic(ctx, s.svcCtx)
	return l.GetOnlineStatus(in)
}

func (s *PresenceServiceServer) BatchGetOnlineStatus(ctx context.Context, in *pb.BatchGetOnlineStatusRequest) (*pb.BatchGetOnlineStatusResponse, error) {
	l := presenceservicelogic.NewBatchGetOnlineStatusLogic(ctx, s.svcCtx)
	return l.BatchGetOnlineStatus(in)
}

func (s *PresenceServiceServer) KickDevice(ctx context.Context, in *pb.KickDeviceRequest) (*pb.KickDeviceResponse, error) {
	l := presenceservicelogic.NewKickDeviceLogic(ctx, s.svcCtx)
	return l.KickDevice(in)
}
