// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: beehive-m-user.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 用户信息（脱敏，不含密码）
type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Account       string                 `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Phone         string                 `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`       // 可脱敏
	Email         string                 `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`       // 可脱敏
	Gender        int32                  `protobuf:"varint,7,opt,name=gender,proto3" json:"gender,omitempty"`    // 0未知 1男 2女
	Birthday      string                 `protobuf:"bytes,8,opt,name=birthday,proto3" json:"birthday,omitempty"` // YYYY-MM-DD
	Signature     string                 `protobuf:"bytes,9,opt,name=signature,proto3" json:"signature,omitempty"`
	Status        int32                  `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`                                // 1正常 2冻结
	LastLoginAt   int64                  `protobuf:"varint,11,opt,name=last_login_at,json=lastLoginAt,proto3" json:"last_login_at,omitempty"` // 时间戳
	CreatedAt     int64                  `protobuf:"varint,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_beehive_m_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_beehive_m_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *User) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *User) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *User) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *User) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *User) GetBirthday() string {
	if x != nil {
		return x.Birthday
	}
	return ""
}

func (x *User) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *User) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *User) GetLastLoginAt() int64 {
	if x != nil {
		return x.LastLoginAt
	}
	return 0
}

func (x *User) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *User) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// 供 auth 内部使用，含密码哈希
type UserForAuth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Account       string                 `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	PasswordHash  string                 `protobuf:"bytes,3,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Email         string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserForAuth) Reset() {
	*x = UserForAuth{}
	mi := &file_beehive_m_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserForAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserForAuth) ProtoMessage() {}

func (x *UserForAuth) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserForAuth.ProtoReflect.Descriptor instead.
func (*UserForAuth) Descriptor() ([]byte, []int) {
	return file_beehive_m_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserForAuth) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserForAuth) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *UserForAuth) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

func (x *UserForAuth) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserForAuth) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserForAuth) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_beehive_m_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_beehive_m_user_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []int64                `protobuf:"varint,1,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserBatchRequest) Reset() {
	*x = GetUserBatchRequest{}
	mi := &file_beehive_m_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBatchRequest) ProtoMessage() {}

func (x *GetUserBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBatchRequest.ProtoReflect.Descriptor instead.
func (*GetUserBatchRequest) Descriptor() ([]byte, []int) {
	return file_beehive_m_user_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserBatchRequest) GetUserIds() []int64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type GetUserBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"` // 未查到的 id 不返回，不保证顺序
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserBatchResponse) Reset() {
	*x = GetUserBatchResponse{}
	mi := &file_beehive_m_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserBatchResponse) ProtoMessage() {}

func (x *GetUserBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserBatchResponse.ProtoReflect.Descriptor instead.
func (*GetUserBatchResponse) Descriptor() ([]byte, []int) {
	return file_beehive_m_user_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserBatchResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type GetUserByAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByAccountRequest) Reset() {
	*x = GetUserByAccountRequest{}
	mi := &file_beehive_m_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByAccountRequest) ProtoMessage() {}

func (x *GetUserByAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByAccountRequest.ProtoReflect.Descriptor instead.
func (*GetUserByAccountRequest) Descriptor() ([]byte, []int) {
	return file_beehive_m_user_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserByAccountRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

type SearchUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyword       string                 `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"` // 从 1 开始
	Size          int32                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"` // 每页条数，建议 1–50
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUsersRequest) Reset() {
	*x = SearchUsersRequest{}
	mi := &file_beehive_m_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUsersRequest) ProtoMessage() {}

func (x *SearchUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUsersRequest.ProtoReflect.Descriptor instead.
func (*SearchUsersRequest) Descriptor() ([]byte, []int) {
	return file_beehive_m_user_proto_rawDescGZIP(), []int{6}
}

func (x *SearchUsersRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *SearchUsersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchUsersRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type SearchUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"` // 总条数，便于前端分页
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUsersResponse) Reset() {
	*x = SearchUsersResponse{}
	mi := &file_beehive_m_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUsersResponse) ProtoMessage() {}

func (x *SearchUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUsersResponse.ProtoReflect.Descriptor instead.
func (*SearchUsersResponse) Descriptor() ([]byte, []int) {
	return file_beehive_m_user_proto_rawDescGZIP(), []int{7}
}

func (x *SearchUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *SearchUsersResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type UpdateProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Nickname      *string                `protobuf:"bytes,2,opt,name=nickname,proto3,oneof" json:"nickname,omitempty"`
	Avatar        *string                `protobuf:"bytes,3,opt,name=avatar,proto3,oneof" json:"avatar,omitempty"`
	Signature     *string                `protobuf:"bytes,4,opt,name=signature,proto3,oneof" json:"signature,omitempty"`
	Gender        *int32                 `protobuf:"varint,5,opt,name=gender,proto3,oneof" json:"gender,omitempty"`
	Birthday      *string                `protobuf:"bytes,6,opt,name=birthday,proto3,oneof" json:"birthday,omitempty"`
	Phone         *string                `protobuf:"bytes,7,opt,name=phone,proto3,oneof" json:"phone,omitempty"`
	Email         *string                `protobuf:"bytes,8,opt,name=email,proto3,oneof" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileRequest) Reset() {
	*x = UpdateProfileRequest{}
	mi := &file_beehive_m_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileRequest) ProtoMessage() {}

func (x *UpdateProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateProfileRequest) Descriptor() ([]byte, []int) {
	return file_beehive_m_user_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateProfileRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateProfileRequest) GetNickname() string {
	if x != nil && x.Nickname != nil {
		return *x.Nickname
	}
	return ""
}

func (x *UpdateProfileRequest) GetAvatar() string {
	if x != nil && x.Avatar != nil {
		return *x.Avatar
	}
	return ""
}

func (x *UpdateProfileRequest) GetSignature() string {
	if x != nil && x.Signature != nil {
		return *x.Signature
	}
	return ""
}

func (x *UpdateProfileRequest) GetGender() int32 {
	if x != nil && x.Gender != nil {
		return *x.Gender
	}
	return 0
}

func (x *UpdateProfileRequest) GetBirthday() string {
	if x != nil && x.Birthday != nil {
		return *x.Birthday
	}
	return ""
}

func (x *UpdateProfileRequest) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

func (x *UpdateProfileRequest) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

type GetUserForAuthRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to By:
	//
	//	*GetUserForAuthRequest_Account
	//	*GetUserForAuthRequest_Phone
	//	*GetUserForAuthRequest_Email
	By            isGetUserForAuthRequest_By `protobuf_oneof:"by"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserForAuthRequest) Reset() {
	*x = GetUserForAuthRequest{}
	mi := &file_beehive_m_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserForAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserForAuthRequest) ProtoMessage() {}

func (x *GetUserForAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_beehive_m_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserForAuthRequest.ProtoReflect.Descriptor instead.
func (*GetUserForAuthRequest) Descriptor() ([]byte, []int) {
	return file_beehive_m_user_proto_rawDescGZIP(), []int{9}
}

func (x *GetUserForAuthRequest) GetBy() isGetUserForAuthRequest_By {
	if x != nil {
		return x.By
	}
	return nil
}

func (x *GetUserForAuthRequest) GetAccount() string {
	if x != nil {
		if x, ok := x.By.(*GetUserForAuthRequest_Account); ok {
			return x.Account
		}
	}
	return ""
}

func (x *GetUserForAuthRequest) GetPhone() string {
	if x != nil {
		if x, ok := x.By.(*GetUserForAuthRequest_Phone); ok {
			return x.Phone
		}
	}
	return ""
}

func (x *GetUserForAuthRequest) GetEmail() string {
	if x != nil {
		if x, ok := x.By.(*GetUserForAuthRequest_Email); ok {
			return x.Email
		}
	}
	return ""
}

type isGetUserForAuthRequest_By interface {
	isGetUserForAuthRequest_By()
}

type GetUserForAuthRequest_Account struct {
	Account string `protobuf:"bytes,1,opt,name=account,proto3,oneof"`
}

type GetUserForAuthRequest_Phone struct {
	Phone string `protobuf:"bytes,2,opt,name=phone,proto3,oneof"`
}

type GetUserForAuthRequest_Email struct {
	Email string `protobuf:"bytes,3,opt,name=email,proto3,oneof"`
}

func (*GetUserForAuthRequest_Account) isGetUserForAuthRequest_By() {}

func (*GetUserForAuthRequest_Phone) isGetUserForAuthRequest_By() {}

func (*GetUserForAuthRequest_Email) isGetUserForAuthRequest_By() {}

var File_beehive_m_user_proto protoreflect.FileDescriptor

const file_beehive_m_user_proto_rawDesc = "" +
	"\n" +
	"\x14beehive-m-user.proto\x12\x04user\"\xe5\x02\n" +
	"\x04User\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x18\n" +
	"\aaccount\x18\x02 \x01(\tR\aaccount\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\x12\x14\n" +
	"\x05phone\x18\x05 \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\x12\x16\n" +
	"\x06gender\x18\a \x01(\x05R\x06gender\x12\x1a\n" +
	"\bbirthday\x18\b \x01(\tR\bbirthday\x12\x1c\n" +
	"\tsignature\x18\t \x01(\tR\tsignature\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\x05R\x06status\x12\"\n" +
	"\rlast_login_at\x18\v \x01(\x03R\vlastLoginAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\r \x01(\x03R\tupdatedAt\"\xa9\x01\n" +
	"\vUserForAuth\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x18\n" +
	"\aaccount\x18\x02 \x01(\tR\aaccount\x12#\n" +
	"\rpassword_hash\x18\x03 \x01(\tR\fpasswordHash\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\")\n" +
	"\x0eGetUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"0\n" +
	"\x13GetUserBatchRequest\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\x03R\auserIds\"8\n" +
	"\x14GetUserBatchResponse\x12 \n" +
	"\x05users\x18\x01 \x03(\v2\n" +
	".user.UserR\x05users\"3\n" +
	"\x17GetUserByAccountRequest\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\"V\n" +
	"\x12SearchUsersRequest\x12\x18\n" +
	"\akeyword\x18\x01 \x01(\tR\akeyword\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x05R\x04size\"M\n" +
	"\x13SearchUsersResponse\x12 \n" +
	"\x05users\x18\x01 \x03(\v2\n" +
	".user.UserR\x05users\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xd6\x02\n" +
	"\x14UpdateProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1f\n" +
	"\bnickname\x18\x02 \x01(\tH\x00R\bnickname\x88\x01\x01\x12\x1b\n" +
	"\x06avatar\x18\x03 \x01(\tH\x01R\x06avatar\x88\x01\x01\x12!\n" +
	"\tsignature\x18\x04 \x01(\tH\x02R\tsignature\x88\x01\x01\x12\x1b\n" +
	"\x06gender\x18\x05 \x01(\x05H\x03R\x06gender\x88\x01\x01\x12\x1f\n" +
	"\bbirthday\x18\x06 \x01(\tH\x04R\bbirthday\x88\x01\x01\x12\x19\n" +
	"\x05phone\x18\a \x01(\tH\x05R\x05phone\x88\x01\x01\x12\x19\n" +
	"\x05email\x18\b \x01(\tH\x06R\x05email\x88\x01\x01B\v\n" +
	"\t_nicknameB\t\n" +
	"\a_avatarB\f\n" +
	"\n" +
	"_signatureB\t\n" +
	"\a_genderB\v\n" +
	"\t_birthdayB\b\n" +
	"\x06_phoneB\b\n" +
	"\x06_email\"i\n" +
	"\x15GetUserForAuthRequest\x12\x1a\n" +
	"\aaccount\x18\x01 \x01(\tH\x00R\aaccount\x12\x16\n" +
	"\x05phone\x18\x02 \x01(\tH\x00R\x05phone\x12\x16\n" +
	"\x05email\x18\x03 \x01(\tH\x00R\x05emailB\x04\n" +
	"\x02by2\xff\x02\n" +
	"\vUserService\x12+\n" +
	"\aGetUser\x12\x14.user.GetUserRequest\x1a\n" +
	".user.User\x12E\n" +
	"\fGetUserBatch\x12\x19.user.GetUserBatchRequest\x1a\x1a.user.GetUserBatchResponse\x12=\n" +
	"\x10GetUserByAccount\x12\x1d.user.GetUserByAccountRequest\x1a\n" +
	".user.User\x12B\n" +
	"\vSearchUsers\x12\x18.user.SearchUsersRequest\x1a\x19.user.SearchUsersResponse\x127\n" +
	"\rUpdateProfile\x12\x1a.user.UpdateProfileRequest\x1a\n" +
	".user.User\x12@\n" +
	"\x0eGetUserForAuth\x12\x1b.user.GetUserForAuthRequest\x1a\x11.user.UserForAuthB\x12Z\x10services/user/pbb\x06proto3"

var (
	file_beehive_m_user_proto_rawDescOnce sync.Once
	file_beehive_m_user_proto_rawDescData []byte
)

func file_beehive_m_user_proto_rawDescGZIP() []byte {
	file_beehive_m_user_proto_rawDescOnce.Do(func() {
		file_beehive_m_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_beehive_m_user_proto_rawDesc), len(file_beehive_m_user_proto_rawDesc)))
	})
	return file_beehive_m_user_proto_rawDescData
}

var file_beehive_m_user_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_beehive_m_user_proto_goTypes = []any{
	(*User)(nil),                    // 0: user.User
	(*UserForAuth)(nil),             // 1: user.UserForAuth
	(*GetUserRequest)(nil),          // 2: user.GetUserRequest
	(*GetUserBatchRequest)(nil),     // 3: user.GetUserBatchRequest
	(*GetUserBatchResponse)(nil),    // 4: user.GetUserBatchResponse
	(*GetUserByAccountRequest)(nil), // 5: user.GetUserByAccountRequest
	(*SearchUsersRequest)(nil),      // 6: user.SearchUsersRequest
	(*SearchUsersResponse)(nil),     // 7: user.SearchUsersResponse
	(*UpdateProfileRequest)(nil),    // 8: user.UpdateProfileRequest
	(*GetUserForAuthRequest)(nil),   // 9: user.GetUserForAuthRequest
}
var file_beehive_m_user_proto_depIdxs = []int32{
	0, // 0: user.GetUserBatchResponse.users:type_name -> user.User
	0, // 1: user.SearchUsersResponse.users:type_name -> user.User
	2, // 2: user.UserService.GetUser:input_type -> user.GetUserRequest
	3, // 3: user.UserService.GetUserBatch:input_type -> user.GetUserBatchRequest
	5, // 4: user.UserService.GetUserByAccount:input_type -> user.GetUserByAccountRequest
	6, // 5: user.UserService.SearchUsers:input_type -> user.SearchUsersRequest
	8, // 6: user.UserService.UpdateProfile:input_type -> user.UpdateProfileRequest
	9, // 7: user.UserService.GetUserForAuth:input_type -> user.GetUserForAuthRequest
	0, // 8: user.UserService.GetUser:output_type -> user.User
	4, // 9: user.UserService.GetUserBatch:output_type -> user.GetUserBatchResponse
	0, // 10: user.UserService.GetUserByAccount:output_type -> user.User
	7, // 11: user.UserService.SearchUsers:output_type -> user.SearchUsersResponse
	0, // 12: user.UserService.UpdateProfile:output_type -> user.User
	1, // 13: user.UserService.GetUserForAuth:output_type -> user.UserForAuth
	8, // [8:14] is the sub-list for method output_type
	2, // [2:8] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_beehive_m_user_proto_init() }
func file_beehive_m_user_proto_init() {
	if File_beehive_m_user_proto != nil {
		return
	}
	file_beehive_m_user_proto_msgTypes[8].OneofWrappers = []any{}
	file_beehive_m_user_proto_msgTypes[9].OneofWrappers = []any{
		(*GetUserForAuthRequest_Account)(nil),
		(*GetUserForAuthRequest_Phone)(nil),
		(*GetUserForAuthRequest_Email)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_beehive_m_user_proto_rawDesc), len(file_beehive_m_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_beehive_m_user_proto_goTypes,
		DependencyIndexes: file_beehive_m_user_proto_depIdxs,
		MessageInfos:      file_beehive_m_user_proto_msgTypes,
	}.Build()
	File_beehive_m_user_proto = out.File
	file_beehive_m_user_proto_goTypes = nil
	file_beehive_m_user_proto_depIdxs = nil
}
