// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: group.proto

package server

import (
	"context"

	"github.com/HappyLadySauce/Beehive-M/services/group/internal/logic/groupservice"
	"github.com/HappyLadySauce/Beehive-M/services/group/internal/svc"
	"github.com/HappyLadySauce/Beehive-M/services/group/pb"
)

type GroupServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedGroupServiceServer
}

func NewGroupServiceServer(svcCtx *svc.ServiceContext) *GroupServiceServer {
	return &GroupServiceServer{
		svcCtx: svcCtx,
	}
}

// 群
func (s *GroupServiceServer) CreateGroup(ctx context.Context, in *pb.CreateGroupRequest) (*pb.CreateGroupResponse, error) {
	l := groupservicelogic.NewCreateGroupLogic(ctx, s.svcCtx)
	return l.CreateGroup(in)
}

func (s *GroupServiceServer) GetGroup(ctx context.Context, in *pb.GetGroupRequest) (*pb.GetGroupResponse, error) {
	l := groupservicelogic.NewGetGroupLogic(ctx, s.svcCtx)
	return l.GetGroup(in)
}

func (s *GroupServiceServer) UpdateGroup(ctx context.Context, in *pb.UpdateGroupRequest) (*pb.UpdateGroupResponse, error) {
	l := groupservicelogic.NewUpdateGroupLogic(ctx, s.svcCtx)
	return l.UpdateGroup(in)
}

func (s *GroupServiceServer) DissolveGroup(ctx context.Context, in *pb.DissolveGroupRequest) (*pb.DissolveGroupResponse, error) {
	l := groupservicelogic.NewDissolveGroupLogic(ctx, s.svcCtx)
	return l.DissolveGroup(in)
}

func (s *GroupServiceServer) SearchGroups(ctx context.Context, in *pb.SearchGroupsRequest) (*pb.SearchGroupsResponse, error) {
	l := groupservicelogic.NewSearchGroupsLogic(ctx, s.svcCtx)
	return l.SearchGroups(in)
}

func (s *GroupServiceServer) ListMyGroups(ctx context.Context, in *pb.ListMyGroupsRequest) (*pb.ListMyGroupsResponse, error) {
	l := groupservicelogic.NewListMyGroupsLogic(ctx, s.svcCtx)
	return l.ListMyGroups(in)
}

// 成员
func (s *GroupServiceServer) JoinGroup(ctx context.Context, in *pb.JoinGroupRequest) (*pb.JoinGroupResponse, error) {
	l := groupservicelogic.NewJoinGroupLogic(ctx, s.svcCtx)
	return l.JoinGroup(in)
}

func (s *GroupServiceServer) LeaveGroup(ctx context.Context, in *pb.LeaveGroupRequest) (*pb.LeaveGroupResponse, error) {
	l := groupservicelogic.NewLeaveGroupLogic(ctx, s.svcCtx)
	return l.LeaveGroup(in)
}

func (s *GroupServiceServer) KickMember(ctx context.Context, in *pb.KickMemberRequest) (*pb.KickMemberResponse, error) {
	l := groupservicelogic.NewKickMemberLogic(ctx, s.svcCtx)
	return l.KickMember(in)
}

func (s *GroupServiceServer) ListMembers(ctx context.Context, in *pb.ListMembersRequest) (*pb.ListMembersResponse, error) {
	l := groupservicelogic.NewListMembersLogic(ctx, s.svcCtx)
	return l.ListMembers(in)
}

func (s *GroupServiceServer) UpdateMyNickname(ctx context.Context, in *pb.UpdateMyNicknameRequest) (*pb.UpdateMyNicknameResponse, error) {
	l := groupservicelogic.NewUpdateMyNicknameLogic(ctx, s.svcCtx)
	return l.UpdateMyNickname(in)
}

func (s *GroupServiceServer) SetMemberMuted(ctx context.Context, in *pb.SetMemberMutedRequest) (*pb.SetMemberMutedResponse, error) {
	l := groupservicelogic.NewSetMemberMutedLogic(ctx, s.svcCtx)
	return l.SetMemberMuted(in)
}

func (s *GroupServiceServer) SetMemberRole(ctx context.Context, in *pb.SetMemberRoleRequest) (*pb.SetMemberRoleResponse, error) {
	l := groupservicelogic.NewSetMemberRoleLogic(ctx, s.svcCtx)
	return l.SetMemberRole(in)
}

// 申请/邀请
func (s *GroupServiceServer) ApplyJoin(ctx context.Context, in *pb.ApplyJoinRequest) (*pb.ApplyJoinResponse, error) {
	l := groupservicelogic.NewApplyJoinLogic(ctx, s.svcCtx)
	return l.ApplyJoin(in)
}

func (s *GroupServiceServer) InviteJoin(ctx context.Context, in *pb.InviteJoinRequest) (*pb.InviteJoinResponse, error) {
	l := groupservicelogic.NewInviteJoinLogic(ctx, s.svcCtx)
	return l.InviteJoin(in)
}

func (s *GroupServiceServer) ListGroupRequests(ctx context.Context, in *pb.ListGroupRequestsRequest) (*pb.ListGroupRequestsResponse, error) {
	l := groupservicelogic.NewListGroupRequestsLogic(ctx, s.svcCtx)
	return l.ListGroupRequests(in)
}

func (s *GroupServiceServer) ListInvitations(ctx context.Context, in *pb.ListInvitationsRequest) (*pb.ListInvitationsResponse, error) {
	l := groupservicelogic.NewListInvitationsLogic(ctx, s.svcCtx)
	return l.ListInvitations(in)
}

func (s *GroupServiceServer) HandleGroupRequest(ctx context.Context, in *pb.HandleGroupRequestRequest) (*pb.HandleGroupRequestResponse, error) {
	l := groupservicelogic.NewHandleGroupRequestLogic(ctx, s.svcCtx)
	return l.HandleGroupRequest(in)
}

func (s *GroupServiceServer) HandleInvitation(ctx context.Context, in *pb.HandleInvitationRequest) (*pb.HandleInvitationResponse, error) {
	l := groupservicelogic.NewHandleInvitationLogic(ctx, s.svcCtx)
	return l.HandleInvitation(in)
}

// 公告
func (s *GroupServiceServer) CreateAnnouncement(ctx context.Context, in *pb.CreateAnnouncementRequest) (*pb.CreateAnnouncementResponse, error) {
	l := groupservicelogic.NewCreateAnnouncementLogic(ctx, s.svcCtx)
	return l.CreateAnnouncement(in)
}

func (s *GroupServiceServer) ListAnnouncements(ctx context.Context, in *pb.ListAnnouncementsRequest) (*pb.ListAnnouncementsResponse, error) {
	l := groupservicelogic.NewListAnnouncementsLogic(ctx, s.svcCtx)
	return l.ListAnnouncements(in)
}

func (s *GroupServiceServer) MarkAnnouncementRead(ctx context.Context, in *pb.MarkAnnouncementReadRequest) (*pb.MarkAnnouncementReadResponse, error) {
	l := groupservicelogic.NewMarkAnnouncementReadLogic(ctx, s.svcCtx)
	return l.MarkAnnouncementRead(in)
}

// 管理员角色权限
func (s *GroupServiceServer) ListAdminRoles(ctx context.Context, in *pb.ListAdminRolesRequest) (*pb.ListAdminRolesResponse, error) {
	l := groupservicelogic.NewListAdminRolesLogic(ctx, s.svcCtx)
	return l.ListAdminRoles(in)
}

func (s *GroupServiceServer) GrantRole(ctx context.Context, in *pb.GrantRoleRequest) (*pb.GrantRoleResponse, error) {
	l := groupservicelogic.NewGrantRoleLogic(ctx, s.svcCtx)
	return l.GrantRole(in)
}

func (s *GroupServiceServer) RevokeRole(ctx context.Context, in *pb.RevokeRoleRequest) (*pb.RevokeRoleResponse, error) {
	l := groupservicelogic.NewRevokeRoleLogic(ctx, s.svcCtx)
	return l.RevokeRole(in)
}

func (s *GroupServiceServer) GetMemberRole(ctx context.Context, in *pb.GetMemberRoleRequest) (*pb.GetMemberRoleResponse, error) {
	l := groupservicelogic.NewGetMemberRoleLogic(ctx, s.svcCtx)
	return l.GetMemberRole(in)
}
